// Auto-generated by ArtSource/Processing/city_ie_street_plan.py — do not edit.
// Re-run with --write after changing the plan; --check fails on drift.
import CoreGraphics

/// Irregular IE street plan shared by every Act I city ward.
///
/// Building masses are axis-aligned in BG:EE (u, v); world edges sit on
/// slopes ±0.75. Streets are the gaps. Replaces `CityBlockGrid` as the
/// source of ward obstacles, wall polygons and edge arrivals.
enum CityStreetPlan {
    struct Mass: Equatable {
        let id: String
        let u0: CGFloat
        let v0: CGFloat
        let u1: CGFloat
        let v1: CGFloat

        var centre: CGPoint {
            let u = (u0 + u1) * 0.5
            let v = (v0 + v1) * 0.5
            return CityStreetPlan.toWorld(u: u, v: v)
        }

        /// Near, right, far, left — camera-near tip first.
        var vertices: [CGPoint] {
            let pts = [
                CityStreetPlan.toWorld(u: u0, v: v0),
                CityStreetPlan.toWorld(u: u1, v: v0),
                CityStreetPlan.toWorld(u: u1, v: v1),
                CityStreetPlan.toWorld(u: u0, v: v1)
            ]
            let cx = pts.map(\.x).reduce(0, +) / 4
            let cy = pts.map(\.y).reduce(0, +) / 4
            let ordered = pts.sorted {
                atan2($0.y - cy, $0.x - cx) < atan2($1.y - cy, $1.x - cx)
            }
            let near = ordered.indices.min(by: { ordered[$0].y < ordered[$1].y })!
            return Array(ordered[near...]) + Array(ordered[..<near])
        }

        func contains(_ point: CGPoint) -> Bool {
            let uv = CityStreetPlan.toUV(point)
            return uv.u >= u0 && uv.u <= u1 && uv.v >= v0 && uv.v <= v1
        }

        static let bandCount = 16

        func obstacleBands() -> [CGRect] {
            let corners = [
                CityStreetPlan.toWorld(u: u0, v: v0),
                CityStreetPlan.toWorld(u: u1, v: v0),
                CityStreetPlan.toWorld(u: u1, v: v1),
                CityStreetPlan.toWorld(u: u0, v: v1)
            ]
            let yMin = corners.map(\.y).min()!
            let yMax = corners.map(\.y).max()!
            guard yMax - yMin > 1 else { return [] }
            let bandHeight = (yMax - yMin) / CGFloat(Self.bandCount)
            var rects: [CGRect] = []
            rects.reserveCapacity(Self.bandCount)
            let edges: [(CGPoint, CGPoint)] = [
                (CityStreetPlan.toWorld(u: u0, v: v0), CityStreetPlan.toWorld(u: u1, v: v0)),
                (CityStreetPlan.toWorld(u: u1, v: v0), CityStreetPlan.toWorld(u: u1, v: v1)),
                (CityStreetPlan.toWorld(u: u1, v: v1), CityStreetPlan.toWorld(u: u0, v: v1)),
                (CityStreetPlan.toWorld(u: u0, v: v1), CityStreetPlan.toWorld(u: u0, v: v0))
            ]
            for index in 0..<Self.bandCount {
                let bottom = yMin + bandHeight * CGFloat(index)
                let top = bottom + bandHeight
                // Min width across the band — midline AABB overhangs the
                // diamond and seals radius-16 street corridors.
                var leftBound: CGFloat = -.greatestFiniteMagnitude
                var rightBound: CGFloat = .greatestFiniteMagnitude
                var sawSample = false
                for sample in [bottom, (bottom + top) * 0.5, top] {
                    var xs: [CGFloat] = []
                    for (p0, p1) in edges {
                        let dy = p1.y - p0.y
                        guard abs(dy) > 1e-9 else { continue }
                        let t = (sample - p0.y) / dy
                        if t >= 0 && t <= 1 {
                            xs.append(p0.x + t * (p1.x - p0.x))
                        }
                    }
                    guard let left = xs.min(), let right = xs.max() else { continue }
                    leftBound = max(leftBound, left)
                    rightBound = min(rightBound, right)
                    sawSample = true
                }
                guard sawSample, rightBound > leftBound else { continue }
                rects.append(CGRect(x: leftBound, y: bottom, width: rightBound - leftBound, height: bandHeight))
            }
            return rects
        }
    }

    static let groundSlope: CGFloat = 0.75

    static func toUV(_ point: CGPoint) -> (u: CGFloat, v: CGFloat) {
        (
            0.5 * (point.x + point.y / groundSlope),
            0.5 * (-point.x + point.y / groundSlope)
        )
    }

    static func toWorld(u: CGFloat, v: CGFloat) -> CGPoint {
        CGPoint(x: u - v, y: groundSlope * (u + v))
    }

    static let all: [Mass] = [
        Mass(id: "m.00", u0: -441.3679, v0: -906.0895, u1: 669.4379, v1: -785.7136),
        Mass(id: "m.01", u0: -99.4975, v0: -514.9983, u1: 756.7164, v1: -355.1004),
        Mass(id: "m.02", u0: -400.231, v0: -23.35, u1: 439.3337, v1: 126.3625),
        Mass(id: "m.03", u0: -94.6807, v0: 192.4901, u1: 275.5113, v1: 605.2356),
        Mass(id: "m.04", u0: -230.1061, v0: 853.5681, u1: 736.0802, v1: 967.9722),
        Mass(id: "m.05", u0: -41.6847, v0: -1167.1674, u1: 859.1724, v1: -1005.8787),
        Mass(id: "m.06", u0: -128.6021, v0: 634.6946, u1: 575.075, v1: 791.8384),
        Mass(id: "m.07", u0: 167.4779, v0: -1372.2028, u1: 1031.1283, v1: -1251.682),
        Mass(id: "m.08", u0: -62.5542, v0: -719.7503, u1: 908.6122, v1: -538.9761),
        Mass(id: "m.09", u0: 459.5123, v0: -39.9536, u1: 986.0896, v1: 223.793),
        Mass(id: "m.10", u0: 604.1008, v0: 312.7606, u1: 1024.1295, v1: 558.1258),
        Mass(id: "m.11", u0: 389.8471, v0: 1112.0349, u1: 1108.0175, v1: 1359.1536),
        Mass(id: "m.12", u0: 517.047, v0: -1847.2364, u1: 1427.9009, v1: -1664.4105),
        Mass(id: "m.13", u0: 815.8045, v0: -287.9175, u1: 1239.4933, v1: -100.8464),
        Mass(id: "m.14", u0: 907.4586, v0: -1213.8797, u1: 1456.6773, v1: -1031.1855),
        Mass(id: "m.15", u0: 955.1984, v0: 730.5924, u1: 1596.5625, v1: 887.1891),
        Mass(id: "m.16", u0: 1116.1697, v0: -954.2974, u1: 1542.1842, v1: -663.2172),
        Mass(id: "m.17", u0: 1218.6371, v0: 249.3636, u1: 1742.5798, v1: 509.5304),
        Mass(id: "m.18", u0: 1142.8688, v0: -1630.6226, u1: 1837.027, v1: -1487.7791),
        Mass(id: "m.19", u0: 1318.2854, v0: -230.7806, u1: 1895.4154, v1: 41.7587),
        Mass(id: "m.20", u0: 1114.929, v0: 976.8382, u1: 2090.9348, v1: 1083.9251),
        Mass(id: "m.21", u0: 1383.4096, v0: 1180.2366, u1: 1664.5098, v1: 1460.3614),
        Mass(id: "m.22", u0: 1462.2924, v0: -566.7557, u1: 2127.9111, v1: -395.2579),
        Mass(id: "m.23", u0: 1151.6804, v0: 123.0719, u1: 2185.9576, v1: 210.9535),
        Mass(id: "m.24", u0: 1474.6056, v0: -1845.4995, u1: 2511.3018, v1: -1745.234),
        Mass(id: "m.25", u0: 1862.8397, v0: 1281.0309, u1: 2356.248, v1: 1490.7202),
        Mass(id: "m.26", u0: 1575.0977, v0: -1448.1592, u1: 2599.731, v1: -1311.4489),
        Mass(id: "m.27", u0: 1943.9984, v0: 448.0611, u1: 2294.1825, v1: 778.4782),
        Mass(id: "m.28", u0: 1973.3695, v0: -1121.7676, u1: 2795.9355, v1: -971.2716),
        Mass(id: "m.29", u0: 2205.3799, v0: -594.0445, u1: 2678.3463, v1: -409.5095),
        Mass(id: "m.30", u0: 1838.7186, v0: 238.3281, u1: 2670.8525, v1: 390.275),
        Mass(id: "m.31", u0: 1935.1406, v0: -717.0738, u1: 3165.1666, v1: -645.6068),
        Mass(id: "m.32", u0: 2254.4674, v0: -378.8641, u1: 2675.4479, v1: -35.2181),
        Mass(id: "m.33", u0: 2448.0553, v0: 1215.5357, u1: 2940.3697, v1: 1449.0137),
        Mass(id: "m.34", u0: 2199.954, v0: -1669.8275, u1: 3145.9694, v1: -1540.4462),
        Mass(id: "m.35", u0: 2241.3388, v0: -904.2855, u1: 3232.9131, v1: -775.4464),
        Mass(id: "m.36", u0: 2440.1827, v0: -4.3736, u1: 3145.906, v1: 141.3091),
        Mass(id: "m.37", u0: 2618.3705, v0: 623.5666, u1: 3172.3367, v1: 834.7838),
        Mass(id: "m.38", u0: 2878.5901, v0: -457.1342, u1: 3312.0614, v1: -156.7477),
        Mass(id: "m.39", u0: 2354.4961, v0: 939.464, u1: 3252.7003, v1: 1110.0214),
        Mass(id: "m.40", u0: 2656.7137, v0: -1301.6563, u1: 3513.3571, v1: -1155.243),
        Mass(id: "m.41", u0: 2708.6051, v0: 387.8355, u1: 3578.5441, v1: 581.6539),
        Mass(id: "m.42", u0: 3228.6706, v0: -1093.5151, u1: 3813.4941, v1: -950.1166),
        Mass(id: "m.43", u0: 3413.4644, v0: -868.2967, u1: 3829.5693, v1: -499.8029),
        Mass(id: "m.fill.44", u0: 38.1038, v0: -334.3976, u1: 299.3157, v1: -49.638),
        Mass(id: "m.fill.45", u0: 1615.5158, v0: 562.1091, u1: 1842.5911, v1: 868.0714),
        Mass(id: "m.fill.46", u0: 3391.6772, v0: 652.1114, u1: 3651.2725, v1: 971.6209),
        Mass(id: "m.fill.47", u0: 3394.9729, v0: -283.3187, u1: 3689.4862, v1: -17.3323),
        Mass(id: "m.pin.ironStairs", u0: 1677.5, v0: -1123.5, u1: 1857.5, v1: -883.5),
        Mass(id: "x.49", u0: 1176.1438, v0: -2406.4905, u1: 2149.1595, v1: -2331.1934),
        Mass(id: "x.50", u0: 1568.8459, v0: -2147.3911, u1: 2068.9985, v1: -1980.0744),
        Mass(id: "x.51", u0: 1512.3584, v0: 1855.3894, u1: 1910.495, v1: 2183.7912),
        Mass(id: "x.52", u0: 1536.3265, v0: 2220.0674, u1: 2275.7045, v1: 2372.5234),
        Mass(id: "x.53", u0: 1855.5964, v0: -2748.4559, u1: 2296.0061, v1: -2479.3226),
        Mass(id: "x.54", u0: 2006.6948, v0: 1592.5583, u1: 2274.7739, v1: 2072.6984),
        Mass(id: "x.55", u0: 2315.681, v0: 2069.1469, u1: 2708.3218, v1: 2389.5672),
        Mass(id: "x.56", u0: 2514.2179, v0: -2678.2011, u1: 2870.0726, v1: -2377.3628),
        Mass(id: "x.57", u0: 2197.2515, v0: -2305.3656, u1: 3001.1831, v1: -2210.8509),
        Mass(id: "x.58", u0: 2110.031, v0: -2039.8143, u1: 3022.4762, v1: -1940.0347),
        Mass(id: "x.59", u0: 2389.4378, v0: 1494.7661, u1: 2841.1348, v1: 1771.4716),
        Mass(id: "x.60", u0: 2774.1935, v0: 2273.2152, u1: 3134.3474, v1: 2608.4059),
        Mass(id: "x.61", u0: 3096.3178, v0: 1485.0011, u1: 3442.0775, v1: 1840.0258),
        Mass(id: "x.62", u0: 2723.7885, v0: 1884.0003, u1: 3551.198, v1: 2005.4318),
        Mass(id: "x.63", u0: 3113.822, v0: -2312.6941, u1: 3446.007, v1: -1985.6389),
        Mass(id: "x.64", u0: 3171.5631, v0: -1649.7663, u1: 3778.0382, v1: -1485.8115),
        Mass(id: "x.65", u0: 3143.1073, v0: 1253.9841, u1: 3794.9661, v1: 1376.5286),
        Mass(id: "x.66", u0: 3217.7346, v0: 190.1655, u1: 3977.6677, v1: 310.8826),
        Mass(id: "x.67", u0: 3446.3369, v0: -1903.9267, u1: 3921.003, v1: -1692.9914),
        Mass(id: "x.68", u0: 3708.8593, v0: 774.1286, u1: 4093.5449, v1: 960.3865),
        Mass(id: "x.69", u0: 3373.7261, v0: 999.2111, u1: 3924.9884, v1: 1226.6432),
        Mass(id: "x.70", u0: 3491.8288, v0: 1681.7178, u1: 4214.6121, v1: 1860.6232),
        Mass(id: "x.71", u0: 3601.205, v0: -1369.8651, u1: 4156.6423, v1: -1236.9879),
        Mass(id: "x.72", u0: 3617.1158, v0: 1541.4984, u1: 4363.592, v1: 1651.4289),
        Mass(id: "x.73", u0: 3975.7474, v0: -1108.0249, u1: 4639.5492, v1: -969.6218),
        Mass(id: "x.74", u0: 3987.7723, v0: -272.3403, u1: 4575.8942, v1: -32.2079),
        Mass(id: "x.75", u0: 3612.5431, v0: 80.2743, u1: 4739.1211, v1: 149.1648),
        Mass(id: "x.76", u0: 3815.6544, v0: 353.2966, u1: 4411.8831, v1: 481.7518),
        Mass(id: "x.77", u0: 3813.3478, v0: 535.106, u1: 4551.9569, v1: 696.9932),
        Mass(id: "x.78", u0: 3947.5741, v0: 1147.44, u1: 4488.5288, v1: 1377.5372),
        Mass(id: "x.79", u0: 3871.3966, v0: -851.9652, u1: 4834.4589, v1: -769.0605),
        Mass(id: "x.80", u0: 4208.8594, v0: -622.3915, u1: 4661.1309, v1: -398.2097),
        Mass(id: "x.81", u0: 4172.6325, v0: 743.7124, u1: 4851.6628, v1: 873.5713),
        Mass(id: "x.82", u0: 4252.5258, v0: 913.7099, u1: 4794.6956, v1: 1072.6301),
        Mass(id: "x.83", u0: 4640.136, v0: -94.4939, u1: 5153.4255, v1: 59.7361),
        Mass(id: "x.84", u0: 4576.9988, v0: 244.8947, u1: 5153.9881, v1: 377.9587),
        Mass(id: "x.85", u0: 4714.2199, v0: 418.5954, u1: 5282.7763, v1: 625.2658),
    ]

    /// Painted masses as nav obstacles — min-width horizontal AABB bands
    /// (midline bands overhang diamonds and seal radius-16 corridors).
    static var wardObstacles: [CGRect] { all.flatMap { $0.obstacleBands() } }

    static func massContaining(_ point: CGPoint) -> Mass? {
        all.first { $0.contains(point) }
    }

    static func isOnStreet(_ point: CGPoint) -> Bool {
        massContaining(point) == nil
    }

    enum PlateEdge: String, CaseIterable {
        case south, north, west, east
    }

    static func arrivalPoint(from edge: PlateEdge, margin: CGFloat = 220) -> CGPoint {
        switch edge {
        case .south:
            return CGPoint(x: 680, y: 220)
        case .north:
            // Moved west onto the north-south street at column 210. The old
            // x = 4160 sat in the north-east plaza, which the block grid closes
            // off with a diagonal run of lots that meet corner to corner: the
            // widest gap between them is 11.6 units, narrower than one 16x12
            // search cell and far narrower than a person. Centre-sampled
            // rasterisation left the odd cell centre free in that seam, so the
            // plaza read as connected; a conservative raster does not, and the
            // arrival was stranded in a 1,569-cell pocket. This is the only
            // authored city point that was ever on the wrong side of it.
            return CGPoint(x: 3368, y: 3620)
        case .west:
            return CGPoint(x: 220, y: 2620)
        case .east:
            return CGPoint(x: 4900, y: 960)
        }
    }

    /// Street junctions used for kerb lamps.
    static let crossings: [CGPoint] = [
        CGPoint(x: 2365.699, y: 2059.0022),
        CGPoint(x: 4724.5499, y: 355.4136),
        CGPoint(x: 4461.0302, y: 3641.3173),
        CGPoint(x: 805.6413, y: 307.9405),
        CGPoint(x: 628.5706, y: 3351.8918),
        CGPoint(x: 2984.9744, y: 412.5192),
        CGPoint(x: 4145.0603, y: 1875.9879),
        CGPoint(x: 423.7321, y: 1715.8196),
        CGPoint(x: 3262.3056, y: 3098.9197),
        CGPoint(x: 2015.9011, y: 3284.9299),
        CGPoint(x: 1524.4351, y: 1266.9493),
        CGPoint(x: 1192.3338, y: 2439.8229),
    ]

    /// Closest plan crossing to a legacy lattice point (840/630 ring).
    static func nearestCrossing(to point: CGPoint) -> CGPoint {
        crossings.min { lhs, rhs in
            let dl = hypot(lhs.x - point.x, lhs.y - point.y)
            let dr = hypot(rhs.x - point.x, rhs.y - point.y)
            return dl < dr
        }!
    }

    /// Sable crossroads plaza — nearest junction to the old mid-ward hub.
    static let wardPlaza = CGPoint(x: 1524.4351, y: 1266.9493)
}
