import CoreGraphics

/// Generated by `ArtSource/Processing/office_layout_plan.py` — edit the
/// layout there and re-run, so art, navigation and previews stay in step.
///
/// Placements are authored in the shell's floor-plan basis: every prop sits on
/// a measured room axis, so furniture lines up with the painted walls.
enum OfficeNavigationLayout {
    enum Architecture {
        /// Exterior leaf closed inside the shell's baked opening.
        static let entranceAnchor = CGPoint(x: 3_138, y: 1_776)
        /// Window insert centre on the shell's left-wall recess.
        static let windowAnchor = CGPoint(x: 1_220, y: 1_812)
        /// Interior partition: one wall on the room's north-east axis (a = 0.36),
        /// with a single framed doorway as the only connection between rooms.
        static let partitionLineA: CGFloat = 0.36
        static let partitionThicknessA: CGFloat = 0.005018169305952131
        static let partitionDoorB0: CGFloat = 0.078
        static let partitionDoorB1: CGFloat = 0.17099999999999999
        static let partitionReturnB1: CGFloat = 0.205
        static let wallThicknessPx: CGFloat = 12.0
        static let axisNW = CGVector(dx: -2206.0, dy: 923.0)
        static let axisNE = CGVector(dx: 1650.0, dy: 763.0)
        static let rearCorner = CGPoint(x: 2446.0, y: 2104.0)

        /// Partition plate geometry in shell art pixels (y down), so the scene can
        /// slice the painted wall into depth-sorted columns that sort like props
        /// standing on the wall's own ground line.
        static let partitionPlateX0: CGFloat = 1621
        static let partitionPlateX1: CGFloat = 2598
        static let partitionPlateFaceHeight: CGFloat = 440
        static let partitionPlateCapHeight: CGFloat = 4

        /// Ground line of the partition face at a shell-art x (y down).
        static func partitionPlateBaseY(atPlateX x: CGFloat) -> CGFloat {
            527.8 + (x - 1621) * 0.4624
        }

        /// Exterior leaf closed inside the shell's baked opening.
        static let entranceLeafDisplayScale: CGFloat = 0.2162
    }

    private static let authoredActorStart = CGPoint(
        x: AuthoredPlacement.deskChair.x,
        y: AuthoredPlacement.deskChair.y + 208
    )

    // MARK: - Obstacles (authored AABBs around each floor footprint)

    /// One cell of the camera-near boundary, kept named for the layout tests.
    static let authoredForegroundWallObstacle = CGRect(x: 2325, y: 1235, width: 104, height: 52)
    static let authoredDoorObstacle = CGRect(x: 3029, y: 1539, width: 170, height: 140)

    /// Room boundary: the rear and side walls plus the camera-near cutaway
    /// wall, one solid per navigation cell outside the painted floor.
    static let authoredBoundarySegments: [CGRect] = [
        CGRect(x: 1996, y: 284, width: 104, height: 52),
        CGRect(x: 1932, y: 316, width: 104, height: 52),
        CGRect(x: 1868, y: 348, width: 104, height: 52),
        CGRect(x: 1804, y: 380, width: 104, height: 52),
        CGRect(x: 1740, y: 412, width: 104, height: 52),
        CGRect(x: 1676, y: 444, width: 104, height: 52),
        CGRect(x: 1612, y: 476, width: 104, height: 52),
        CGRect(x: 1548, y: 508, width: 104, height: 52),
        CGRect(x: 1484, y: 540, width: 104, height: 52),
        CGRect(x: 1420, y: 572, width: 104, height: 52),
        CGRect(x: 1356, y: 604, width: 104, height: 52),
        CGRect(x: 1292, y: 636, width: 104, height: 52),
        CGRect(x: 1228, y: 668, width: 104, height: 52),
        CGRect(x: 1164, y: 700, width: 104, height: 52),
        CGRect(x: 1100, y: 732, width: 104, height: 52),
        CGRect(x: 1036, y: 764, width: 104, height: 52),
        CGRect(x: 972, y: 796, width: 104, height: 52),
        CGRect(x: 908, y: 828, width: 104, height: 52),
        CGRect(x: 844, y: 860, width: 104, height: 52),
        CGRect(x: 780, y: 892, width: 104, height: 52),
        CGRect(x: 716, y: 924, width: 104, height: 52),
        CGRect(x: 652, y: 956, width: 104, height: 52),
        CGRect(x: 588, y: 988, width: 104, height: 52),
        CGRect(x: 524, y: 1020, width: 104, height: 52),
        CGRect(x: 460, y: 1052, width: 104, height: 52),
        CGRect(x: 396, y: 1084, width: 104, height: 52),
        CGRect(x: 332, y: 1116, width: 104, height: 52),
        CGRect(x: 268, y: 1148, width: 104, height: 52),
        CGRect(x: 204, y: 1180, width: 104, height: 52),
        CGRect(x: 140, y: 1212, width: 104, height: 52),
        CGRect(x: 76, y: 1244, width: 104, height: 52),
        CGRect(x: 2060, y: 316, width: 104, height: 52),
        CGRect(x: 1996, y: 348, width: 104, height: 52),
        CGRect(x: 1932, y: 380, width: 104, height: 52),
        CGRect(x: 1868, y: 412, width: 104, height: 52),
        CGRect(x: 1804, y: 444, width: 104, height: 52),
        CGRect(x: 1740, y: 476, width: 104, height: 52),
        CGRect(x: 1676, y: 508, width: 104, height: 52),
        CGRect(x: 1612, y: 540, width: 104, height: 52),
        CGRect(x: 1548, y: 572, width: 104, height: 52),
        CGRect(x: 1484, y: 604, width: 104, height: 52),
        CGRect(x: 1420, y: 636, width: 104, height: 52),
        CGRect(x: 1356, y: 668, width: 104, height: 52),
        CGRect(x: 1292, y: 700, width: 104, height: 52),
        CGRect(x: 1228, y: 732, width: 104, height: 52),
        CGRect(x: 1164, y: 764, width: 104, height: 52),
        CGRect(x: 1100, y: 796, width: 104, height: 52),
        CGRect(x: 1036, y: 828, width: 104, height: 52),
        CGRect(x: 972, y: 860, width: 104, height: 52),
        CGRect(x: 908, y: 892, width: 104, height: 52),
        CGRect(x: 844, y: 924, width: 104, height: 52),
        CGRect(x: 780, y: 956, width: 104, height: 52),
        CGRect(x: 716, y: 988, width: 104, height: 52),
        CGRect(x: 652, y: 1020, width: 104, height: 52),
        CGRect(x: 588, y: 1052, width: 104, height: 52),
        CGRect(x: 524, y: 1084, width: 104, height: 52),
        CGRect(x: 460, y: 1116, width: 104, height: 52),
        CGRect(x: 332, y: 1180, width: 104, height: 52),
        CGRect(x: 268, y: 1212, width: 104, height: 52),
        CGRect(x: 204, y: 1244, width: 104, height: 52),
        CGRect(x: 140, y: 1276, width: 104, height: 52),
        CGRect(x: 2124, y: 348, width: 104, height: 52),
        CGRect(x: 2060, y: 380, width: 104, height: 52),
        CGRect(x: 1996, y: 412, width: 104, height: 52),
        CGRect(x: 1932, y: 444, width: 104, height: 52),
        CGRect(x: 1868, y: 476, width: 104, height: 52),
        CGRect(x: 1804, y: 508, width: 104, height: 52),
        CGRect(x: 1740, y: 540, width: 104, height: 52),
        CGRect(x: 1676, y: 572, width: 104, height: 52),
        CGRect(x: 1612, y: 604, width: 104, height: 52),
        CGRect(x: 1548, y: 636, width: 104, height: 52),
        CGRect(x: 1484, y: 668, width: 104, height: 52),
        CGRect(x: 1420, y: 700, width: 104, height: 52),
        CGRect(x: 1356, y: 732, width: 104, height: 52),
        CGRect(x: 1292, y: 764, width: 104, height: 52),
        CGRect(x: 1228, y: 796, width: 104, height: 52),
        CGRect(x: 396, y: 1212, width: 104, height: 52),
        CGRect(x: 332, y: 1244, width: 104, height: 52),
        CGRect(x: 268, y: 1276, width: 104, height: 52),
        CGRect(x: 204, y: 1308, width: 104, height: 52),
        CGRect(x: 2188, y: 380, width: 104, height: 52),
        CGRect(x: 2124, y: 412, width: 104, height: 52),
        CGRect(x: 2060, y: 444, width: 104, height: 52),
        CGRect(x: 1996, y: 476, width: 104, height: 52),
        CGRect(x: 1932, y: 508, width: 104, height: 52),
        CGRect(x: 1868, y: 540, width: 104, height: 52),
        CGRect(x: 1804, y: 572, width: 104, height: 52),
        CGRect(x: 1740, y: 604, width: 104, height: 52),
        CGRect(x: 1676, y: 636, width: 104, height: 52),
        CGRect(x: 1612, y: 668, width: 104, height: 52),
        CGRect(x: 1548, y: 700, width: 104, height: 52),
        CGRect(x: 1484, y: 732, width: 104, height: 52),
        CGRect(x: 1420, y: 764, width: 104, height: 52),
        CGRect(x: 1356, y: 796, width: 104, height: 52),
        CGRect(x: 1292, y: 828, width: 104, height: 52),
        CGRect(x: 460, y: 1244, width: 104, height: 52),
        CGRect(x: 396, y: 1276, width: 104, height: 52),
        CGRect(x: 332, y: 1308, width: 104, height: 52),
        CGRect(x: 268, y: 1340, width: 104, height: 52),
        CGRect(x: 2252, y: 412, width: 104, height: 52),
        CGRect(x: 2188, y: 444, width: 104, height: 52),
        CGRect(x: 2124, y: 476, width: 104, height: 52),
        CGRect(x: 2060, y: 508, width: 104, height: 52),
        CGRect(x: 1996, y: 540, width: 104, height: 52),
        CGRect(x: 1932, y: 572, width: 104, height: 52),
        CGRect(x: 1868, y: 604, width: 104, height: 52),
        CGRect(x: 1804, y: 636, width: 104, height: 52),
        CGRect(x: 1740, y: 668, width: 104, height: 52),
        CGRect(x: 1676, y: 700, width: 104, height: 52),
        CGRect(x: 1612, y: 732, width: 104, height: 52),
        CGRect(x: 1548, y: 764, width: 104, height: 52),
        CGRect(x: 1484, y: 796, width: 104, height: 52),
        CGRect(x: 1420, y: 828, width: 104, height: 52),
        CGRect(x: 1356, y: 860, width: 104, height: 52),
        CGRect(x: 524, y: 1276, width: 104, height: 52),
        CGRect(x: 460, y: 1308, width: 104, height: 52),
        CGRect(x: 396, y: 1340, width: 104, height: 52),
        CGRect(x: 332, y: 1372, width: 104, height: 52),
        CGRect(x: 2316, y: 444, width: 104, height: 52),
        CGRect(x: 2252, y: 476, width: 104, height: 52),
        CGRect(x: 2188, y: 508, width: 104, height: 52),
        CGRect(x: 2124, y: 540, width: 104, height: 52),
        CGRect(x: 2060, y: 572, width: 104, height: 52),
        CGRect(x: 1996, y: 604, width: 104, height: 52),
        CGRect(x: 1932, y: 636, width: 104, height: 52),
        CGRect(x: 1868, y: 668, width: 104, height: 52),
        CGRect(x: 1804, y: 700, width: 104, height: 52),
        CGRect(x: 1740, y: 732, width: 104, height: 52),
        CGRect(x: 1676, y: 764, width: 104, height: 52),
        CGRect(x: 1612, y: 796, width: 104, height: 52),
        CGRect(x: 1548, y: 828, width: 104, height: 52),
        CGRect(x: 1484, y: 860, width: 104, height: 52),
        CGRect(x: 1420, y: 892, width: 104, height: 52),
        CGRect(x: 588, y: 1308, width: 104, height: 52),
        CGRect(x: 524, y: 1340, width: 104, height: 52),
        CGRect(x: 460, y: 1372, width: 104, height: 52),
        CGRect(x: 396, y: 1404, width: 104, height: 52),
        CGRect(x: 2380, y: 476, width: 104, height: 52),
        CGRect(x: 2316, y: 508, width: 104, height: 52),
        CGRect(x: 2252, y: 540, width: 104, height: 52),
        CGRect(x: 2188, y: 572, width: 104, height: 52),
        CGRect(x: 2124, y: 604, width: 104, height: 52),
        CGRect(x: 2060, y: 636, width: 104, height: 52),
        CGRect(x: 1996, y: 668, width: 104, height: 52),
        CGRect(x: 1932, y: 700, width: 104, height: 52),
        CGRect(x: 1868, y: 732, width: 104, height: 52),
        CGRect(x: 1804, y: 764, width: 104, height: 52),
        CGRect(x: 1740, y: 796, width: 104, height: 52),
        CGRect(x: 1676, y: 828, width: 104, height: 52),
        CGRect(x: 1612, y: 860, width: 104, height: 52),
        CGRect(x: 1548, y: 892, width: 104, height: 52),
        CGRect(x: 1484, y: 924, width: 104, height: 52),
        CGRect(x: 652, y: 1340, width: 104, height: 52),
        CGRect(x: 588, y: 1372, width: 104, height: 52),
        CGRect(x: 524, y: 1404, width: 104, height: 52),
        CGRect(x: 460, y: 1436, width: 104, height: 52),
        CGRect(x: 2444, y: 508, width: 104, height: 52),
        CGRect(x: 2380, y: 540, width: 104, height: 52),
        CGRect(x: 2316, y: 572, width: 104, height: 52),
        CGRect(x: 2252, y: 604, width: 104, height: 52),
        CGRect(x: 2188, y: 636, width: 104, height: 52),
        CGRect(x: 2124, y: 668, width: 104, height: 52),
        CGRect(x: 2060, y: 700, width: 104, height: 52),
        CGRect(x: 1996, y: 732, width: 104, height: 52),
        CGRect(x: 1932, y: 764, width: 104, height: 52),
        CGRect(x: 1868, y: 796, width: 104, height: 52),
        CGRect(x: 1804, y: 828, width: 104, height: 52),
        CGRect(x: 1740, y: 860, width: 104, height: 52),
        CGRect(x: 1676, y: 892, width: 104, height: 52),
        CGRect(x: 1612, y: 924, width: 104, height: 52),
        CGRect(x: 716, y: 1372, width: 104, height: 52),
        CGRect(x: 652, y: 1404, width: 104, height: 52),
        CGRect(x: 588, y: 1436, width: 104, height: 52),
        CGRect(x: 524, y: 1468, width: 104, height: 52),
        CGRect(x: 2508, y: 540, width: 104, height: 52),
        CGRect(x: 2444, y: 572, width: 104, height: 52),
        CGRect(x: 2380, y: 604, width: 104, height: 52),
        CGRect(x: 2316, y: 636, width: 104, height: 52),
        CGRect(x: 2252, y: 668, width: 104, height: 52),
        CGRect(x: 2188, y: 700, width: 104, height: 52),
        CGRect(x: 2124, y: 732, width: 104, height: 52),
        CGRect(x: 2060, y: 764, width: 104, height: 52),
        CGRect(x: 1996, y: 796, width: 104, height: 52),
        CGRect(x: 1932, y: 828, width: 104, height: 52),
        CGRect(x: 1868, y: 860, width: 104, height: 52),
        CGRect(x: 1804, y: 892, width: 104, height: 52),
        CGRect(x: 1740, y: 924, width: 104, height: 52),
        CGRect(x: 1676, y: 956, width: 104, height: 52),
        CGRect(x: 844, y: 1372, width: 104, height: 52),
        CGRect(x: 780, y: 1404, width: 104, height: 52),
        CGRect(x: 716, y: 1436, width: 104, height: 52),
        CGRect(x: 652, y: 1468, width: 104, height: 52),
        CGRect(x: 588, y: 1500, width: 104, height: 52),
        CGRect(x: 2572, y: 572, width: 104, height: 52),
        CGRect(x: 2508, y: 604, width: 104, height: 52),
        CGRect(x: 2444, y: 636, width: 104, height: 52),
        CGRect(x: 2380, y: 668, width: 104, height: 52),
        CGRect(x: 2316, y: 700, width: 104, height: 52),
        CGRect(x: 2252, y: 732, width: 104, height: 52),
        CGRect(x: 2188, y: 764, width: 104, height: 52),
        CGRect(x: 2124, y: 796, width: 104, height: 52),
        CGRect(x: 2060, y: 828, width: 104, height: 52),
        CGRect(x: 1996, y: 860, width: 104, height: 52),
        CGRect(x: 1932, y: 892, width: 104, height: 52),
        CGRect(x: 1868, y: 924, width: 104, height: 52),
        CGRect(x: 1804, y: 956, width: 104, height: 52),
        CGRect(x: 1740, y: 988, width: 104, height: 52),
        CGRect(x: 908, y: 1404, width: 104, height: 52),
        CGRect(x: 844, y: 1436, width: 104, height: 52),
        CGRect(x: 780, y: 1468, width: 104, height: 52),
        CGRect(x: 716, y: 1500, width: 104, height: 52),
        CGRect(x: 652, y: 1532, width: 104, height: 52),
        CGRect(x: 2636, y: 604, width: 104, height: 52),
        CGRect(x: 2572, y: 636, width: 104, height: 52),
        CGRect(x: 2508, y: 668, width: 104, height: 52),
        CGRect(x: 2444, y: 700, width: 104, height: 52),
        CGRect(x: 2380, y: 732, width: 104, height: 52),
        CGRect(x: 2316, y: 764, width: 104, height: 52),
        CGRect(x: 2252, y: 796, width: 104, height: 52),
        CGRect(x: 2188, y: 828, width: 104, height: 52),
        CGRect(x: 2124, y: 860, width: 104, height: 52),
        CGRect(x: 2060, y: 892, width: 104, height: 52),
        CGRect(x: 1996, y: 924, width: 104, height: 52),
        CGRect(x: 1932, y: 956, width: 104, height: 52),
        CGRect(x: 1868, y: 988, width: 104, height: 52),
        CGRect(x: 1804, y: 1020, width: 104, height: 52),
        CGRect(x: 972, y: 1436, width: 104, height: 52),
        CGRect(x: 908, y: 1468, width: 104, height: 52),
        CGRect(x: 844, y: 1500, width: 104, height: 52),
        CGRect(x: 780, y: 1532, width: 104, height: 52),
        CGRect(x: 716, y: 1564, width: 104, height: 52),
        CGRect(x: 2700, y: 636, width: 104, height: 52),
        CGRect(x: 2636, y: 668, width: 104, height: 52),
        CGRect(x: 2572, y: 700, width: 104, height: 52),
        CGRect(x: 2508, y: 732, width: 104, height: 52),
        CGRect(x: 2444, y: 764, width: 104, height: 52),
        CGRect(x: 2380, y: 796, width: 104, height: 52),
        CGRect(x: 2316, y: 828, width: 104, height: 52),
        CGRect(x: 2252, y: 860, width: 104, height: 52),
        CGRect(x: 2188, y: 892, width: 104, height: 52),
        CGRect(x: 2124, y: 924, width: 104, height: 52),
        CGRect(x: 2060, y: 956, width: 104, height: 52),
        CGRect(x: 1996, y: 988, width: 104, height: 52),
        CGRect(x: 1932, y: 1020, width: 104, height: 52),
        CGRect(x: 1868, y: 1052, width: 104, height: 52),
        CGRect(x: 1036, y: 1468, width: 104, height: 52),
        CGRect(x: 972, y: 1500, width: 104, height: 52),
        CGRect(x: 908, y: 1532, width: 104, height: 52),
        CGRect(x: 844, y: 1564, width: 104, height: 52),
        CGRect(x: 780, y: 1596, width: 104, height: 52),
        CGRect(x: 2764, y: 668, width: 104, height: 52),
        CGRect(x: 2700, y: 700, width: 104, height: 52),
        CGRect(x: 2636, y: 732, width: 104, height: 52),
        CGRect(x: 2572, y: 764, width: 104, height: 52),
        CGRect(x: 2508, y: 796, width: 104, height: 52),
        CGRect(x: 2444, y: 828, width: 104, height: 52),
        CGRect(x: 2380, y: 860, width: 104, height: 52),
        CGRect(x: 2316, y: 892, width: 104, height: 52),
        CGRect(x: 2252, y: 924, width: 104, height: 52),
        CGRect(x: 2188, y: 956, width: 104, height: 52),
        CGRect(x: 2124, y: 988, width: 104, height: 52),
        CGRect(x: 2060, y: 1020, width: 104, height: 52),
        CGRect(x: 1996, y: 1052, width: 104, height: 52),
        CGRect(x: 1932, y: 1084, width: 104, height: 52),
        CGRect(x: 1100, y: 1500, width: 104, height: 52),
        CGRect(x: 1036, y: 1532, width: 104, height: 52),
        CGRect(x: 972, y: 1564, width: 104, height: 52),
        CGRect(x: 908, y: 1596, width: 104, height: 52),
        CGRect(x: 844, y: 1628, width: 104, height: 52),
        CGRect(x: 2828, y: 700, width: 104, height: 52),
        CGRect(x: 2764, y: 732, width: 104, height: 52),
        CGRect(x: 2700, y: 764, width: 104, height: 52),
        CGRect(x: 2636, y: 796, width: 104, height: 52),
        CGRect(x: 2572, y: 828, width: 104, height: 52),
        CGRect(x: 2508, y: 860, width: 104, height: 52),
        CGRect(x: 2444, y: 892, width: 104, height: 52),
        CGRect(x: 2380, y: 924, width: 104, height: 52),
        CGRect(x: 2316, y: 956, width: 104, height: 52),
        CGRect(x: 2252, y: 988, width: 104, height: 52),
        CGRect(x: 2188, y: 1020, width: 104, height: 52),
        CGRect(x: 2124, y: 1052, width: 104, height: 52),
        CGRect(x: 2060, y: 1084, width: 104, height: 52),
        CGRect(x: 1996, y: 1116, width: 104, height: 52),
        CGRect(x: 1164, y: 1532, width: 104, height: 52),
        CGRect(x: 1100, y: 1564, width: 104, height: 52),
        CGRect(x: 1036, y: 1596, width: 104, height: 52),
        CGRect(x: 972, y: 1628, width: 104, height: 52),
        CGRect(x: 908, y: 1660, width: 104, height: 52),
        CGRect(x: 2892, y: 732, width: 104, height: 52),
        CGRect(x: 2828, y: 764, width: 104, height: 52),
        CGRect(x: 2764, y: 796, width: 104, height: 52),
        CGRect(x: 2700, y: 828, width: 104, height: 52),
        CGRect(x: 2636, y: 860, width: 104, height: 52),
        CGRect(x: 2572, y: 892, width: 104, height: 52),
        CGRect(x: 2508, y: 924, width: 104, height: 52),
        CGRect(x: 2444, y: 956, width: 104, height: 52),
        CGRect(x: 2380, y: 988, width: 104, height: 52),
        CGRect(x: 2316, y: 1020, width: 104, height: 52),
        CGRect(x: 2252, y: 1052, width: 104, height: 52),
        CGRect(x: 2188, y: 1084, width: 104, height: 52),
        CGRect(x: 2124, y: 1116, width: 104, height: 52),
        CGRect(x: 2060, y: 1148, width: 104, height: 52),
        CGRect(x: 1228, y: 1564, width: 104, height: 52),
        CGRect(x: 1164, y: 1596, width: 104, height: 52),
        CGRect(x: 1100, y: 1628, width: 104, height: 52),
        CGRect(x: 1036, y: 1660, width: 104, height: 52),
        CGRect(x: 972, y: 1692, width: 104, height: 52),
        CGRect(x: 2956, y: 764, width: 104, height: 52),
        CGRect(x: 2892, y: 796, width: 104, height: 52),
        CGRect(x: 2828, y: 828, width: 104, height: 52),
        CGRect(x: 2764, y: 860, width: 104, height: 52),
        CGRect(x: 2700, y: 892, width: 104, height: 52),
        CGRect(x: 2636, y: 924, width: 104, height: 52),
        CGRect(x: 2572, y: 956, width: 104, height: 52),
        CGRect(x: 2508, y: 988, width: 104, height: 52),
        CGRect(x: 2444, y: 1020, width: 104, height: 52),
        CGRect(x: 2380, y: 1052, width: 104, height: 52),
        CGRect(x: 2316, y: 1084, width: 104, height: 52),
        CGRect(x: 2252, y: 1116, width: 104, height: 52),
        CGRect(x: 2188, y: 1148, width: 104, height: 52),
        CGRect(x: 2124, y: 1180, width: 104, height: 52),
        CGRect(x: 1292, y: 1596, width: 104, height: 52),
        CGRect(x: 1228, y: 1628, width: 104, height: 52),
        CGRect(x: 1164, y: 1660, width: 104, height: 52),
        CGRect(x: 1100, y: 1692, width: 104, height: 52),
        CGRect(x: 1036, y: 1724, width: 104, height: 52),
        CGRect(x: 3020, y: 796, width: 104, height: 52),
        CGRect(x: 2956, y: 828, width: 104, height: 52),
        CGRect(x: 2892, y: 860, width: 104, height: 52),
        CGRect(x: 2828, y: 892, width: 104, height: 52),
        CGRect(x: 2764, y: 924, width: 104, height: 52),
        CGRect(x: 2700, y: 956, width: 104, height: 52),
        CGRect(x: 2636, y: 988, width: 104, height: 52),
        CGRect(x: 2572, y: 1020, width: 104, height: 52),
        CGRect(x: 2508, y: 1052, width: 104, height: 52),
        CGRect(x: 2444, y: 1084, width: 104, height: 52),
        CGRect(x: 2380, y: 1116, width: 104, height: 52),
        CGRect(x: 2316, y: 1148, width: 104, height: 52),
        CGRect(x: 2252, y: 1180, width: 104, height: 52),
        CGRect(x: 2188, y: 1212, width: 104, height: 52),
        CGRect(x: 1356, y: 1628, width: 104, height: 52),
        CGRect(x: 1292, y: 1660, width: 104, height: 52),
        CGRect(x: 1228, y: 1692, width: 104, height: 52),
        CGRect(x: 1164, y: 1724, width: 104, height: 52),
        CGRect(x: 1100, y: 1756, width: 104, height: 52),
        CGRect(x: 3084, y: 828, width: 104, height: 52),
        CGRect(x: 3020, y: 860, width: 104, height: 52),
        CGRect(x: 2956, y: 892, width: 104, height: 52),
        CGRect(x: 2892, y: 924, width: 104, height: 52),
        CGRect(x: 2828, y: 956, width: 104, height: 52),
        CGRect(x: 2764, y: 988, width: 104, height: 52),
        CGRect(x: 2700, y: 1020, width: 104, height: 52),
        CGRect(x: 2636, y: 1052, width: 104, height: 52),
        CGRect(x: 2572, y: 1084, width: 104, height: 52),
        CGRect(x: 2508, y: 1116, width: 104, height: 52),
        CGRect(x: 2444, y: 1148, width: 104, height: 52),
        CGRect(x: 2380, y: 1180, width: 104, height: 52),
        CGRect(x: 2316, y: 1212, width: 104, height: 52),
        CGRect(x: 2252, y: 1244, width: 104, height: 52),
        CGRect(x: 1420, y: 1660, width: 104, height: 52),
        CGRect(x: 1356, y: 1692, width: 104, height: 52),
        CGRect(x: 1292, y: 1724, width: 104, height: 52),
        CGRect(x: 1228, y: 1756, width: 104, height: 52),
        CGRect(x: 1164, y: 1788, width: 104, height: 52),
        CGRect(x: 3148, y: 860, width: 104, height: 52),
        CGRect(x: 3084, y: 892, width: 104, height: 52),
        CGRect(x: 3020, y: 924, width: 104, height: 52),
        CGRect(x: 2956, y: 956, width: 104, height: 52),
        CGRect(x: 2892, y: 988, width: 104, height: 52),
        CGRect(x: 2828, y: 1020, width: 104, height: 52),
        CGRect(x: 2764, y: 1052, width: 104, height: 52),
        CGRect(x: 2700, y: 1084, width: 104, height: 52),
        CGRect(x: 2636, y: 1116, width: 104, height: 52),
        CGRect(x: 2572, y: 1148, width: 104, height: 52),
        CGRect(x: 2508, y: 1180, width: 104, height: 52),
        CGRect(x: 2444, y: 1212, width: 104, height: 52),
        CGRect(x: 2380, y: 1244, width: 104, height: 52),
        CGRect(x: 1484, y: 1692, width: 104, height: 52),
        CGRect(x: 1420, y: 1724, width: 104, height: 52),
        CGRect(x: 1356, y: 1756, width: 104, height: 52),
        CGRect(x: 1292, y: 1788, width: 104, height: 52),
        CGRect(x: 1228, y: 1820, width: 104, height: 52),
        CGRect(x: 3212, y: 892, width: 104, height: 52),
        CGRect(x: 3148, y: 924, width: 104, height: 52),
        CGRect(x: 3084, y: 956, width: 104, height: 52),
        CGRect(x: 3020, y: 988, width: 104, height: 52),
        CGRect(x: 2956, y: 1020, width: 104, height: 52),
        CGRect(x: 2892, y: 1052, width: 104, height: 52),
        CGRect(x: 2828, y: 1084, width: 104, height: 52),
        CGRect(x: 2764, y: 1116, width: 104, height: 52),
        CGRect(x: 2700, y: 1148, width: 104, height: 52),
        CGRect(x: 2636, y: 1180, width: 104, height: 52),
        CGRect(x: 2572, y: 1212, width: 104, height: 52),
        CGRect(x: 2508, y: 1244, width: 104, height: 52),
        CGRect(x: 2444, y: 1276, width: 104, height: 52),
        CGRect(x: 1548, y: 1724, width: 104, height: 52),
        CGRect(x: 1484, y: 1756, width: 104, height: 52),
        CGRect(x: 1420, y: 1788, width: 104, height: 52),
        CGRect(x: 1356, y: 1820, width: 104, height: 52),
        CGRect(x: 1292, y: 1852, width: 104, height: 52),
        CGRect(x: 3276, y: 924, width: 104, height: 52),
        CGRect(x: 3212, y: 956, width: 104, height: 52),
        CGRect(x: 3148, y: 988, width: 104, height: 52),
        CGRect(x: 3084, y: 1020, width: 104, height: 52),
        CGRect(x: 3020, y: 1052, width: 104, height: 52),
        CGRect(x: 2956, y: 1084, width: 104, height: 52),
        CGRect(x: 2892, y: 1116, width: 104, height: 52),
        CGRect(x: 2828, y: 1148, width: 104, height: 52),
        CGRect(x: 2764, y: 1180, width: 104, height: 52),
        CGRect(x: 2700, y: 1212, width: 104, height: 52),
        CGRect(x: 2636, y: 1244, width: 104, height: 52),
        CGRect(x: 2572, y: 1276, width: 104, height: 52),
        CGRect(x: 2508, y: 1308, width: 104, height: 52),
        CGRect(x: 1676, y: 1724, width: 104, height: 52),
        CGRect(x: 1612, y: 1756, width: 104, height: 52),
        CGRect(x: 1548, y: 1788, width: 104, height: 52),
        CGRect(x: 1484, y: 1820, width: 104, height: 52),
        CGRect(x: 1420, y: 1852, width: 104, height: 52),
        CGRect(x: 1356, y: 1884, width: 104, height: 52),
        CGRect(x: 3340, y: 956, width: 104, height: 52),
        CGRect(x: 3276, y: 988, width: 104, height: 52),
        CGRect(x: 3212, y: 1020, width: 104, height: 52),
        CGRect(x: 3148, y: 1052, width: 104, height: 52),
        CGRect(x: 3084, y: 1084, width: 104, height: 52),
        CGRect(x: 3020, y: 1116, width: 104, height: 52),
        CGRect(x: 2956, y: 1148, width: 104, height: 52),
        CGRect(x: 2892, y: 1180, width: 104, height: 52),
        CGRect(x: 2828, y: 1212, width: 104, height: 52),
        CGRect(x: 2764, y: 1244, width: 104, height: 52),
        CGRect(x: 2700, y: 1276, width: 104, height: 52),
        CGRect(x: 2636, y: 1308, width: 104, height: 52),
        CGRect(x: 2572, y: 1340, width: 104, height: 52),
        CGRect(x: 1740, y: 1756, width: 104, height: 52),
        CGRect(x: 1676, y: 1788, width: 104, height: 52),
        CGRect(x: 1612, y: 1820, width: 104, height: 52),
        CGRect(x: 1548, y: 1852, width: 104, height: 52),
        CGRect(x: 1484, y: 1884, width: 104, height: 52),
        CGRect(x: 1420, y: 1916, width: 104, height: 52),
        CGRect(x: 3404, y: 988, width: 104, height: 52),
        CGRect(x: 3340, y: 1020, width: 104, height: 52),
        CGRect(x: 3276, y: 1052, width: 104, height: 52),
        CGRect(x: 3212, y: 1084, width: 104, height: 52),
        CGRect(x: 3148, y: 1116, width: 104, height: 52),
        CGRect(x: 3084, y: 1148, width: 104, height: 52),
        CGRect(x: 3020, y: 1180, width: 104, height: 52),
        CGRect(x: 2956, y: 1212, width: 104, height: 52),
        CGRect(x: 2892, y: 1244, width: 104, height: 52),
        CGRect(x: 2828, y: 1276, width: 104, height: 52),
        CGRect(x: 2764, y: 1308, width: 104, height: 52),
        CGRect(x: 2700, y: 1340, width: 104, height: 52),
        CGRect(x: 2636, y: 1372, width: 104, height: 52),
        CGRect(x: 1804, y: 1788, width: 104, height: 52),
        CGRect(x: 1740, y: 1820, width: 104, height: 52),
        CGRect(x: 1676, y: 1852, width: 104, height: 52),
        CGRect(x: 1612, y: 1884, width: 104, height: 52),
        CGRect(x: 1548, y: 1916, width: 104, height: 52),
        CGRect(x: 1484, y: 1948, width: 104, height: 52),
        CGRect(x: 3468, y: 1020, width: 104, height: 52),
        CGRect(x: 3404, y: 1052, width: 104, height: 52),
        CGRect(x: 3340, y: 1084, width: 104, height: 52),
        CGRect(x: 3276, y: 1116, width: 104, height: 52),
        CGRect(x: 3212, y: 1148, width: 104, height: 52),
        CGRect(x: 3148, y: 1180, width: 104, height: 52),
        CGRect(x: 3084, y: 1212, width: 104, height: 52),
        CGRect(x: 3020, y: 1244, width: 104, height: 52),
        CGRect(x: 2956, y: 1276, width: 104, height: 52),
        CGRect(x: 2892, y: 1308, width: 104, height: 52),
        CGRect(x: 2828, y: 1340, width: 104, height: 52),
        CGRect(x: 2764, y: 1372, width: 104, height: 52),
        CGRect(x: 2700, y: 1404, width: 104, height: 52),
        CGRect(x: 1868, y: 1820, width: 104, height: 52),
        CGRect(x: 1804, y: 1852, width: 104, height: 52),
        CGRect(x: 1740, y: 1884, width: 104, height: 52),
        CGRect(x: 1676, y: 1916, width: 104, height: 52),
        CGRect(x: 1612, y: 1948, width: 104, height: 52),
        CGRect(x: 1548, y: 1980, width: 104, height: 52),
        CGRect(x: 3532, y: 1052, width: 104, height: 52),
        CGRect(x: 3468, y: 1084, width: 104, height: 52),
        CGRect(x: 3404, y: 1116, width: 104, height: 52),
        CGRect(x: 3340, y: 1148, width: 104, height: 52),
        CGRect(x: 3276, y: 1180, width: 104, height: 52),
        CGRect(x: 3212, y: 1212, width: 104, height: 52),
        CGRect(x: 3148, y: 1244, width: 104, height: 52),
        CGRect(x: 3084, y: 1276, width: 104, height: 52),
        CGRect(x: 3020, y: 1308, width: 104, height: 52),
        CGRect(x: 2956, y: 1340, width: 104, height: 52),
        CGRect(x: 2892, y: 1372, width: 104, height: 52),
        CGRect(x: 2828, y: 1404, width: 104, height: 52),
        CGRect(x: 2764, y: 1436, width: 104, height: 52),
        CGRect(x: 1932, y: 1852, width: 104, height: 52),
        CGRect(x: 1868, y: 1884, width: 104, height: 52),
        CGRect(x: 1804, y: 1916, width: 104, height: 52),
        CGRect(x: 1740, y: 1948, width: 104, height: 52),
        CGRect(x: 1676, y: 1980, width: 104, height: 52),
        CGRect(x: 1612, y: 2012, width: 104, height: 52),
        CGRect(x: 3596, y: 1084, width: 104, height: 52),
        CGRect(x: 3532, y: 1116, width: 104, height: 52),
        CGRect(x: 3468, y: 1148, width: 104, height: 52),
        CGRect(x: 3404, y: 1180, width: 104, height: 52),
        CGRect(x: 3340, y: 1212, width: 104, height: 52),
        CGRect(x: 3276, y: 1244, width: 104, height: 52),
        CGRect(x: 3212, y: 1276, width: 104, height: 52),
        CGRect(x: 3148, y: 1308, width: 104, height: 52),
        CGRect(x: 3084, y: 1340, width: 104, height: 52),
        CGRect(x: 3020, y: 1372, width: 104, height: 52),
        CGRect(x: 2956, y: 1404, width: 104, height: 52),
        CGRect(x: 2892, y: 1436, width: 104, height: 52),
        CGRect(x: 2828, y: 1468, width: 104, height: 52),
        CGRect(x: 1996, y: 1884, width: 104, height: 52),
        CGRect(x: 1932, y: 1916, width: 104, height: 52),
        CGRect(x: 1868, y: 1948, width: 104, height: 52),
        CGRect(x: 1804, y: 1980, width: 104, height: 52),
        CGRect(x: 1740, y: 2012, width: 104, height: 52),
        CGRect(x: 1676, y: 2044, width: 104, height: 52),
        CGRect(x: 3660, y: 1116, width: 104, height: 52),
        CGRect(x: 3596, y: 1148, width: 104, height: 52),
        CGRect(x: 3532, y: 1180, width: 104, height: 52),
        CGRect(x: 3468, y: 1212, width: 104, height: 52),
        CGRect(x: 3404, y: 1244, width: 104, height: 52),
        CGRect(x: 3340, y: 1276, width: 104, height: 52),
        CGRect(x: 3276, y: 1308, width: 104, height: 52),
        CGRect(x: 3212, y: 1340, width: 104, height: 52),
        CGRect(x: 3148, y: 1372, width: 104, height: 52),
        CGRect(x: 3084, y: 1404, width: 104, height: 52),
        CGRect(x: 3020, y: 1436, width: 104, height: 52),
        CGRect(x: 2956, y: 1468, width: 104, height: 52),
        CGRect(x: 2892, y: 1500, width: 104, height: 52),
        CGRect(x: 2060, y: 1916, width: 104, height: 52),
        CGRect(x: 1996, y: 1948, width: 104, height: 52),
        CGRect(x: 1932, y: 1980, width: 104, height: 52),
        CGRect(x: 1868, y: 2012, width: 104, height: 52),
        CGRect(x: 1804, y: 2044, width: 104, height: 52),
        CGRect(x: 1740, y: 2076, width: 104, height: 52),
        CGRect(x: 3724, y: 1148, width: 104, height: 52),
        CGRect(x: 3660, y: 1180, width: 104, height: 52),
        CGRect(x: 3596, y: 1212, width: 104, height: 52),
        CGRect(x: 3532, y: 1244, width: 104, height: 52),
        CGRect(x: 3468, y: 1276, width: 104, height: 52),
        CGRect(x: 3404, y: 1308, width: 104, height: 52),
        CGRect(x: 3340, y: 1340, width: 104, height: 52),
        CGRect(x: 3276, y: 1372, width: 104, height: 52),
        CGRect(x: 3212, y: 1404, width: 104, height: 52),
        CGRect(x: 3148, y: 1436, width: 104, height: 52),
        CGRect(x: 3084, y: 1468, width: 104, height: 52),
        CGRect(x: 3020, y: 1500, width: 104, height: 52),
        CGRect(x: 2956, y: 1532, width: 104, height: 52),
        CGRect(x: 2124, y: 1948, width: 104, height: 52),
        CGRect(x: 2060, y: 1980, width: 104, height: 52),
        CGRect(x: 1996, y: 2012, width: 104, height: 52),
        CGRect(x: 1932, y: 2044, width: 104, height: 52),
        CGRect(x: 1868, y: 2076, width: 104, height: 52),
        CGRect(x: 1804, y: 2108, width: 104, height: 52),
        CGRect(x: 3788, y: 1180, width: 104, height: 52),
        CGRect(x: 3724, y: 1212, width: 104, height: 52),
        CGRect(x: 3660, y: 1244, width: 104, height: 52),
        CGRect(x: 3596, y: 1276, width: 104, height: 52),
        CGRect(x: 3532, y: 1308, width: 104, height: 52),
        CGRect(x: 3468, y: 1340, width: 104, height: 52),
        CGRect(x: 3404, y: 1372, width: 104, height: 52),
        CGRect(x: 3340, y: 1404, width: 104, height: 52),
        CGRect(x: 3276, y: 1436, width: 104, height: 52),
        CGRect(x: 3212, y: 1468, width: 104, height: 52),
        CGRect(x: 3148, y: 1500, width: 104, height: 52),
        CGRect(x: 3084, y: 1532, width: 104, height: 52),
        CGRect(x: 3020, y: 1564, width: 104, height: 52),
        CGRect(x: 2188, y: 1980, width: 104, height: 52),
        CGRect(x: 2124, y: 2012, width: 104, height: 52),
        CGRect(x: 2060, y: 2044, width: 104, height: 52),
        CGRect(x: 1996, y: 2076, width: 104, height: 52),
        CGRect(x: 1932, y: 2108, width: 104, height: 52),
        CGRect(x: 1868, y: 2140, width: 104, height: 52),
        CGRect(x: 3852, y: 1212, width: 104, height: 52),
        CGRect(x: 3788, y: 1244, width: 104, height: 52),
        CGRect(x: 3724, y: 1276, width: 104, height: 52),
        CGRect(x: 3660, y: 1308, width: 104, height: 52),
        CGRect(x: 3596, y: 1340, width: 104, height: 52),
        CGRect(x: 3532, y: 1372, width: 104, height: 52),
        CGRect(x: 3468, y: 1404, width: 104, height: 52),
        CGRect(x: 3404, y: 1436, width: 104, height: 52),
        CGRect(x: 3340, y: 1468, width: 104, height: 52),
        CGRect(x: 3276, y: 1500, width: 104, height: 52),
        CGRect(x: 3212, y: 1532, width: 104, height: 52),
        CGRect(x: 3148, y: 1564, width: 104, height: 52),
        CGRect(x: 3084, y: 1596, width: 104, height: 52),
        CGRect(x: 2252, y: 2012, width: 104, height: 52),
        CGRect(x: 2188, y: 2044, width: 104, height: 52),
        CGRect(x: 2124, y: 2076, width: 104, height: 52),
        CGRect(x: 2060, y: 2108, width: 104, height: 52),
        CGRect(x: 1996, y: 2140, width: 104, height: 52),
        CGRect(x: 1932, y: 2172, width: 104, height: 52),
        CGRect(x: 3916, y: 1244, width: 104, height: 52),
        CGRect(x: 3852, y: 1276, width: 104, height: 52),
        CGRect(x: 3788, y: 1308, width: 104, height: 52),
        CGRect(x: 3724, y: 1340, width: 104, height: 52),
        CGRect(x: 3660, y: 1372, width: 104, height: 52),
        CGRect(x: 3596, y: 1404, width: 104, height: 52),
        CGRect(x: 3532, y: 1436, width: 104, height: 52),
        CGRect(x: 3468, y: 1468, width: 104, height: 52),
        CGRect(x: 3404, y: 1500, width: 104, height: 52),
        CGRect(x: 3340, y: 1532, width: 104, height: 52),
        CGRect(x: 3276, y: 1564, width: 104, height: 52),
        CGRect(x: 3212, y: 1596, width: 104, height: 52),
        CGRect(x: 2764, y: 1820, width: 104, height: 52),
        CGRect(x: 2700, y: 1852, width: 104, height: 52),
        CGRect(x: 2636, y: 1884, width: 104, height: 52),
        CGRect(x: 2572, y: 1916, width: 104, height: 52),
        CGRect(x: 2508, y: 1948, width: 104, height: 52),
        CGRect(x: 2444, y: 1980, width: 104, height: 52),
        CGRect(x: 2380, y: 2012, width: 104, height: 52),
        CGRect(x: 2316, y: 2044, width: 104, height: 52),
        CGRect(x: 2252, y: 2076, width: 104, height: 52),
        CGRect(x: 2188, y: 2108, width: 104, height: 52),
        CGRect(x: 2124, y: 2140, width: 104, height: 52),
        CGRect(x: 2060, y: 2172, width: 104, height: 52),
        CGRect(x: 1996, y: 2204, width: 104, height: 52),
    ]

    /// Partition solids, one per navigation cell, doorway cells omitted.
    static let authoredPartitionWallNorthObstacle = CGRect(x: 2572, y: 1276, width: 104, height: 52)
    static let authoredPartitionWallSouthObstacle = CGRect(x: 1612, y: 1756, width: 104, height: 52)
    static let authoredPartitionSegments: [CGRect] = [
        CGRect(x: 2572, y: 1276, width: 104, height: 52),
        CGRect(x: 2508, y: 1308, width: 104, height: 52),
        CGRect(x: 2444, y: 1340, width: 104, height: 52),
        CGRect(x: 2380, y: 1372, width: 104, height: 52),
        CGRect(x: 2316, y: 1404, width: 104, height: 52),
        CGRect(x: 2252, y: 1436, width: 104, height: 52),
        CGRect(x: 2188, y: 1468, width: 104, height: 52),
        CGRect(x: 2124, y: 1500, width: 104, height: 52),
        CGRect(x: 2060, y: 1532, width: 104, height: 52),
        CGRect(x: 1996, y: 1564, width: 104, height: 52),
        CGRect(x: 1932, y: 1596, width: 104, height: 52),
        CGRect(x: 1676, y: 1724, width: 104, height: 52),
        CGRect(x: 1612, y: 1756, width: 104, height: 52),
    ]

    static let authoredSafeObstacle = CGRect(x: 1027, y: 1439, width: 173, height: 76)
    static let authoredFilingCabinetBObstacle = CGRect(x: 900, y: 1386, width: 161, height: 71)
    static let authoredFilingCabinetObstacle = CGRect(x: 764, y: 1329, width: 161, height: 71)
    static let authoredBookshelfObstacle = CGRect(x: 583, y: 1251, width: 223, height: 101)
    static let authoredArchiveBoxAObstacle = CGRect(x: 782, y: 1253, width: 137, height: 60)
    static let authoredRadiatorObstacle = CGRect(x: 1202, y: 1519, width: 173, height: 79)
    static let authoredPersonalSideboardObstacle = CGRect(x: 1465, y: 1620, width: 245, height: 110)
    static let authoredPersonalWashbasinObstacle = CGRect(x: 1402, y: 1595, width: 173, height: 77)
    static let authoredPersonalFanObstacle = CGRect(x: 1621, y: 1634, width: 144, height: 63)
    static let authoredDeskEnsembleObstacle = CGRect(x: 1218, y: 1229, width: 374, height: 167)
    static let authoredVisitorArmchairObstacle = CGRect(x: 1412, y: 1400, width: 230, height: 101)
    static let authoredVisitorArmchairBObstacle = CGRect(x: 1618, y: 1304, width: 230, height: 101)
    static let authoredWastebasketObstacle = CGRect(x: 1064, y: 1292, width: 115, height: 51)
    static let authoredCoatRackObstacle = CGRect(x: 2985, y: 1637, width: 173, height: 76)
    static let authoredUmbrellaStandObstacle = CGRect(x: 3136, y: 1639, width: 101, height: 44)
    static let authoredWaitingChairAObstacle = CGRect(x: 2907, y: 1590, width: 158, height: 70)
    static let authoredWaitingTableObstacle = CGRect(x: 2973, y: 1560, width: 158, height: 70)
    static let authoredWaitingChairBObstacle = CGRect(x: 3034, y: 1531, width: 158, height: 70)

    private static var authoredObstacles: [CGRect] {
        [authoredDoorObstacle, authoredForegroundWallObstacle]
            + authoredBoundarySegments
            + authoredPartitionSegments
            + [
                authoredSafeObstacle,
                authoredFilingCabinetBObstacle,
                authoredFilingCabinetObstacle,
                authoredBookshelfObstacle,
                authoredArchiveBoxAObstacle,
                authoredRadiatorObstacle,
                authoredPersonalSideboardObstacle,
                authoredPersonalWashbasinObstacle,
                authoredPersonalFanObstacle,
                authoredDeskEnsembleObstacle,
                authoredVisitorArmchairObstacle,
                authoredVisitorArmchairBObstacle,
                authoredWastebasketObstacle,
                authoredCoatRackObstacle,
                authoredUmbrellaStandObstacle,
                authoredWaitingChairAObstacle,
                authoredWaitingTableObstacle,
                authoredWaitingChairBObstacle,
            ]
    }

    // MARK: - Sample points (interior to each obstacle)

    static let authoredSafeSamplePoints: [CGPoint] = [
        CGPoint(x: 1_113, y: 1_477),
        CGPoint(x: 1_079, y: 1_465),
        CGPoint(x: 1_148, y: 1_488),
    ]
    static let authoredFilingCabinetBSamplePoints: [CGPoint] = [
        CGPoint(x: 981, y: 1_421),
        CGPoint(x: 949, y: 1_411),
        CGPoint(x: 1_013, y: 1_432),
    ]
    static let authoredFilingCabinetSamplePoints: [CGPoint] = [
        CGPoint(x: 844, y: 1_364),
        CGPoint(x: 812, y: 1_353),
        CGPoint(x: 876, y: 1_375),
    ]
    static let authoredBookshelfSamplePoints: [CGPoint] = [
        CGPoint(x: 694, y: 1_301),
        CGPoint(x: 650, y: 1_286),
        CGPoint(x: 739, y: 1_316),
    ]
    static let authoredArchiveBoxASamplePoints: [CGPoint] = [
        CGPoint(x: 850, y: 1_284),
        CGPoint(x: 823, y: 1_275),
        CGPoint(x: 877, y: 1_293),
    ]
    static let authoredRadiatorSamplePoints: [CGPoint] = [
        CGPoint(x: 1_289, y: 1_559),
        CGPoint(x: 1_254, y: 1_547),
        CGPoint(x: 1_323, y: 1_571),
    ]
    static let authoredPersonalSideboardSamplePoints: [CGPoint] = [
        CGPoint(x: 1_588, y: 1_675),
        CGPoint(x: 1_539, y: 1_659),
        CGPoint(x: 1_637, y: 1_692),
    ]
    static let authoredPersonalWashbasinSamplePoints: [CGPoint] = [
        CGPoint(x: 1_488, y: 1_634),
        CGPoint(x: 1_454, y: 1_622),
        CGPoint(x: 1_523, y: 1_645),
    ]
    static let authoredPersonalFanSamplePoints: [CGPoint] = [
        CGPoint(x: 1_693, y: 1_665),
        CGPoint(x: 1_664, y: 1_656),
        CGPoint(x: 1_722, y: 1_675),
    ]
    static let authoredDeskEnsembleSamplePoints: [CGPoint] = [
        CGPoint(x: 1_405, y: 1_312),
        CGPoint(x: 1_330, y: 1_287),
        CGPoint(x: 1_480, y: 1_338),
    ]
    static let authoredVisitorArmchairSamplePoints: [CGPoint] = [
        CGPoint(x: 1_527, y: 1_451),
        CGPoint(x: 1_481, y: 1_435),
        CGPoint(x: 1_573, y: 1_466),
    ]
    static let authoredVisitorArmchairBSamplePoints: [CGPoint] = [
        CGPoint(x: 1_733, y: 1_355),
        CGPoint(x: 1_687, y: 1_340),
        CGPoint(x: 1_779, y: 1_370),
    ]
    static let authoredWastebasketSamplePoints: [CGPoint] = [
        CGPoint(x: 1_122, y: 1_317),
        CGPoint(x: 1_099, y: 1_310),
        CGPoint(x: 1_145, y: 1_325),
    ]
    static let authoredCoatRackSamplePoints: [CGPoint] = [
        CGPoint(x: 3_071, y: 1_675),
        CGPoint(x: 3_036, y: 1_664),
        CGPoint(x: 3_105, y: 1_687),
    ]
    static let authoredUmbrellaStandSamplePoints: [CGPoint] = [
        CGPoint(x: 3_186, y: 1_661),
        CGPoint(x: 3_166, y: 1_654),
        CGPoint(x: 3_206, y: 1_667),
    ]
    static let authoredWaitingChairASamplePoints: [CGPoint] = [
        CGPoint(x: 2_986, y: 1_625),
        CGPoint(x: 2_954, y: 1_615),
        CGPoint(x: 3_018, y: 1_635),
    ]
    static let authoredWaitingTableSamplePoints: [CGPoint] = [
        CGPoint(x: 3_052, y: 1_595),
        CGPoint(x: 3_020, y: 1_584),
        CGPoint(x: 3_084, y: 1_605),
    ]
    static let authoredWaitingChairBSamplePoints: [CGPoint] = [
        CGPoint(x: 3_113, y: 1_566),
        CGPoint(x: 3_081, y: 1_556),
        CGPoint(x: 3_145, y: 1_577),
    ]
    static let authoredDoorLeafSamplePoints: [CGPoint] = [
        CGPoint(x: 3_114, y: 1_609),
        CGPoint(x: 3_080, y: 1_588),
        CGPoint(x: 3_148, y: 1_630),
    ]
    static let authoredForegroundWallSamplePoints: [CGPoint] = [
        CGPoint(x: 2_377, y: 1_261),
        CGPoint(x: 2_356, y: 1_254),
        CGPoint(x: 2_398, y: 1_269),
    ]
    static let authoredPartitionWallNorthSamplePoints: [CGPoint] = [
        CGPoint(x: 2_624, y: 1_302),
        CGPoint(x: 2_603, y: 1_294),
        CGPoint(x: 2_645, y: 1_310),
    ]
    static let authoredPartitionWallSouthSamplePoints: [CGPoint] = [
        CGPoint(x: 1_664, y: 1_782),
        CGPoint(x: 1_643, y: 1_774),
        CGPoint(x: 1_685, y: 1_790),
    ]

    // MARK: - Placements

    enum AuthoredPlacement {
        static let doorLeaf = Architecture.entranceAnchor
        static let window = Architecture.windowAnchor
        static let windowBlinds = window
        static let windowRotation: CGFloat = -0.105
        static let windowRainMask = CGRect(x: 1_182, y: 1_744, width: 76, height: 136)
        static let windowRainEmitter = CGPoint(x: 1_220, y: 1_884)
        /// Recentred on the shrunken room (the plate's lower floor is gone).
        static let camera = CGPoint(x: 1_960, y: 1_340)

        static let safe = CGPoint(x: 1_113, y: 1_477)  // records run, east end
        static let filingCabinetB = CGPoint(x: 981, y: 1_421)
        static let filingCabinet = CGPoint(x: 844, y: 1_364)  // drawer half open
        static let bookshelf = CGPoint(x: 694, y: 1_301)
        static let archiveBoxOnCabinet = CGPoint(x: 981, y: 1_421)  // on cabinet B
        static let archiveStackOnCabinet = CGPoint(x: 844, y: 1_364)  // on cabinet A
        static let archiveBoxA = CGPoint(x: 850, y: 1_284)  // only floor stack
        static let radiator = CGPoint(x: 1_289, y: 1_559)
        static let personalSideboard = CGPoint(x: 1_588, y: 1_675)
        static let personalWashbasin = CGPoint(x: 1_488, y: 1_634)
        static let personalFan = CGPoint(x: 1_693, y: 1_665)
        static let personalBottle = CGPoint(x: 1_574, y: 1_664)  // on sideboard
        static let personalGlass = CGPoint(x: 1_614, y: 1_680)  // on sideboard
        static let deskEnsemble = CGPoint(x: 1_405, y: 1_312)
        static let deskChair = CGPoint(x: 1_251, y: 1_248)
        static let visitorArmchair = CGPoint(x: 1_527, y: 1_451)
        static let visitorArmchairB = CGPoint(x: 1_733, y: 1_355)
        static let wastebasket = CGPoint(x: 1_122, y: 1_317)
        static let coatRack = CGPoint(x: 3_071, y: 1_675)
        static let umbrellaStand = CGPoint(x: 3_186, y: 1_661)
        static let waitingChairA = CGPoint(x: 2_986, y: 1_625)
        static let waitingTable = CGPoint(x: 3_052, y: 1_595)
        static let waitingChairB = CGPoint(x: 3_113, y: 1_566)
        static let newspaper = CGPoint(x: 3_055, y: 1_605)  // on table
        static let waitingAshtray = CGPoint(x: 3_046, y: 1_582)  // on table

        static let wornRug = CGPoint(x: 1_443, y: 1_324)
        static let floorWear = deskEnsemble
        static let caseBoard = CGPoint(x: 900, y: 1_784)
        static let wallCityMap = CGPoint(x: 1_070, y: 1_834)
        static let wallPhotos = CGPoint(x: 760, y: 1_714)
        static let windowSpill = CGPoint(x: 1_240, y: 1_504)
        static let blindStripes = CGPoint(x: 1_330, y: 1_374)
        static let hallwayLight = CGPoint(x: 3_130, y: 1_664)
        static let lampPool = deskEnsemble
        /// Leaf swung 90° into the private office, hinged on the up-run jamb.
        static let internalDoorLeaf = CGPoint(x: 1_693, y: 1_662)
    }

    private static let authoredApproachPoints: [String: CGPoint] = [
        "office.window": CGPoint(x: 1_533, y: 1_551),
        "office.desk": CGPoint(x: 1_760, y: 1_236),
        "office.phone": CGPoint(x: 1_672, y: 1_199),
        "office.files": CGPoint(x: 1_042, y: 1_272),
        "office.door": CGPoint(x: 2_882, y: 1_661),
    ]

    private static let authoredProjectionOrigin = CGPoint(x: 2_048, y: 310)
    private static let authoredTileSize = CGSize(width: 128, height: 64)

    static var actorStart: CGPoint { OfficeInteriorScale.mapPoint(authoredActorStart) }

    static var emptyDeskChairWorldPosition: CGPoint {
        let baseline = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
        let nudge = OfficeInteriorScale.ActorDisplay.seatedDeskNudge
        return CGPoint(x: baseline.x + nudge.x, y: baseline.y + nudge.y)
    }

    /// Exterior door → waiting room → internal doorway → client chair.
    static let clientArrivalPath: [CGPoint] = [
        CGPoint(x: 3_041, y: 1_728),
        CGPoint(x: 2_544, y: 1_709),
        CGPoint(x: 2_125, y: 1_708),
        CGPoint(x: 1_780, y: 1_644),
        CGPoint(x: 1_984, y: 1_366),
    ].map(OfficeInteriorScale.mapPoint)

    static var clientDeparturePath: [CGPoint] { Array(clientArrivalPath.reversed()) }

    static let exteriorToInternalDoorPath: [CGPoint] = [
        CGPoint(x: 3_041, y: 1_728),
        CGPoint(x: 2_544, y: 1_709),
        CGPoint(x: 2_125, y: 1_708),
    ].map(OfficeInteriorScale.mapPoint)

    static let internalDoorToClientPath: [CGPoint] = [
        CGPoint(x: 2_125, y: 1_708),
        CGPoint(x: 1_780, y: 1_644),
        CGPoint(x: 1_984, y: 1_366),
    ].map(OfficeInteriorScale.mapPoint)

    static let recordsApproachPath: [CGPoint] = [
        CGPoint(x: 1_507, y: 1_217),
        CGPoint(x: 1_221, y: 1_272),
        CGPoint(x: 1_042, y: 1_272),
    ].map(OfficeInteriorScale.mapPoint)

    static var obstacles: [CGRect] { authoredObstacles.map(OfficeInteriorScale.mapRect) }

    static var safeObstacle: CGRect { OfficeInteriorScale.mapRect(authoredSafeObstacle) }
    static var filingCabinetBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetBObstacle) }
    static var filingCabinetObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetObstacle) }
    static var bookshelfObstacle: CGRect { OfficeInteriorScale.mapRect(authoredBookshelfObstacle) }
    static var archiveBoxAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredArchiveBoxAObstacle) }
    static var radiatorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredRadiatorObstacle) }
    static var personalSideboardObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalSideboardObstacle) }
    static var personalWashbasinObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalWashbasinObstacle) }
    static var personalFanObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalFanObstacle) }
    static var deskEnsembleObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDeskEnsembleObstacle) }
    static var visitorArmchairObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairObstacle) }
    static var visitorArmchairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairBObstacle) }
    static var wastebasketObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWastebasketObstacle) }
    static var coatRackObstacle: CGRect { OfficeInteriorScale.mapRect(authoredCoatRackObstacle) }
    static var umbrellaStandObstacle: CGRect { OfficeInteriorScale.mapRect(authoredUmbrellaStandObstacle) }
    static var waitingChairAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairAObstacle) }
    static var waitingTableObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingTableObstacle) }
    static var waitingChairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairBObstacle) }
    static var doorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDoorObstacle) }
    static var foregroundWallObstacle: CGRect { OfficeInteriorScale.mapRect(authoredForegroundWallObstacle) }
    static var partitionWallNorthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallNorthObstacle) }
    static var partitionWallSouthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallSouthObstacle) }

    static var safeSamplePoints: [CGPoint] { authoredSafeSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetBSamplePoints: [CGPoint] { authoredFilingCabinetBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetSamplePoints: [CGPoint] { authoredFilingCabinetSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var bookshelfSamplePoints: [CGPoint] { authoredBookshelfSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var archiveBoxASamplePoints: [CGPoint] { authoredArchiveBoxASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var radiatorSamplePoints: [CGPoint] { authoredRadiatorSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalSideboardSamplePoints: [CGPoint] { authoredPersonalSideboardSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalWashbasinSamplePoints: [CGPoint] { authoredPersonalWashbasinSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalFanSamplePoints: [CGPoint] { authoredPersonalFanSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var deskEnsembleSamplePoints: [CGPoint] { authoredDeskEnsembleSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairSamplePoints: [CGPoint] { authoredVisitorArmchairSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairBSamplePoints: [CGPoint] { authoredVisitorArmchairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var wastebasketSamplePoints: [CGPoint] { authoredWastebasketSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var coatRackSamplePoints: [CGPoint] { authoredCoatRackSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var umbrellaStandSamplePoints: [CGPoint] { authoredUmbrellaStandSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairASamplePoints: [CGPoint] { authoredWaitingChairASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingTableSamplePoints: [CGPoint] { authoredWaitingTableSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairBSamplePoints: [CGPoint] { authoredWaitingChairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var doorLeafSamplePoints: [CGPoint] { authoredDoorLeafSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var foregroundWallSamplePoints: [CGPoint] { authoredForegroundWallSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallNorthSamplePoints: [CGPoint] { authoredPartitionWallNorthSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallSouthSamplePoints: [CGPoint] { authoredPartitionWallSouthSamplePoints.map(OfficeInteriorScale.mapPoint) }

    static var majorPropSamplePoints: [CGPoint] {
        safeSamplePoints
            + filingCabinetBSamplePoints
            + filingCabinetSamplePoints
            + bookshelfSamplePoints
            + archiveBoxASamplePoints
            + radiatorSamplePoints
            + personalSideboardSamplePoints
            + personalWashbasinSamplePoints
            + personalFanSamplePoints
            + deskEnsembleSamplePoints
            + visitorArmchairSamplePoints
            + visitorArmchairBSamplePoints
            + wastebasketSamplePoints
            + coatRackSamplePoints
            + umbrellaStandSamplePoints
            + waitingChairASamplePoints
            + waitingTableSamplePoints
            + waitingChairBSamplePoints
            + doorLeafSamplePoints
            + foregroundWallSamplePoints
            + partitionWallNorthSamplePoints
            + partitionWallSouthSamplePoints
    }

    static var approachPoints: [String: CGPoint] {
        authoredApproachPoints.mapValues(OfficeInteriorScale.mapPoint)
    }

    /// Stand points for the architecture visibility capture: behind the desk,
    /// in the internal doorway, and beside the waiting chair.
    static let authoredScaleReferenceStands: [CGPoint] = [
        CGPoint(x: 1_174, y: 1_216),
        CGPoint(x: 1_780, y: 1_644),
        CGPoint(x: 2_907, y: 1_570),
    ]

    static var scaleReferenceStands: [CGPoint] {
        authoredScaleReferenceStands.map(OfficeInteriorScale.mapPoint)
    }

    static var deskSamplePoints: [CGPoint] { deskEnsembleSamplePoints }
    static var deskObstacle: CGRect { deskEnsembleObstacle }
    static var authoredDeskObstacle: CGRect { authoredDeskEnsembleObstacle }

    static let authoredHotspots: [(id: String, name: String, hitArea: CGRect, observation: String)] = [
        (
            "office.window",
            "Rain-streaked window",
            CGRect(x: 1_174, y: 1_758, width: 92, height: 160),
            "The rain had been working the glass harder than I had worked a case."
        ),
        (
            "office.desk",
            "Desk",
            deskHitArea,
            "Three old cases, two unpaid bills, one clean page."
        ),
        (
            "office.phone",
            "Telephone",
            phoneHitArea,
            "Quiet. For once it had the decency to look guilty."
        ),
        (
            "office.files",
            "Case files",
            filesHitArea,
            "Closed, abandoned, and one I still lied about."
        ),
        (
            "office.door",
            "Office door",
            CGRect(x: 3_000, y: 1_400, width: 240, height: 480),
            "The hall smelled worse, but at least it led somewhere."
        )
    ]

    private static var deskHitArea: CGRect {
        authoredDeskEnsembleObstacle.insetBy(dx: -90, dy: -70)
    }

    private static var phoneHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.deskEnsemble.x - 40,
            y: AuthoredPlacement.deskEnsemble.y + 40,
            width: 200,
            height: 150
        )
    }

    private static var filesHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.filingCabinet.x - 110,
            y: AuthoredPlacement.filingCabinet.y - 20,
            width: 300,
            height: 220
        )
    }


    enum DialogueCameraFraming {
        static let legacyDownwardOffset: CGFloat = 55
        static let priorDownwardOffset: CGFloat = 28
        static let cameraBelowActorMidpoint: CGFloat = 110
        static let lateralBiasTowardClient: CGFloat = 24

        static var actorFocusPoint: CGPoint {
            let voss = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
            let lila = clientArrivalPath.last
                ?? OfficeInteriorScale.mapPoint(AuthoredPlacement.visitorArmchair)
            return CGPoint(
                x: (voss.x + lila.x) * 0.5 + lateralBiasTowardClient,
                y: (voss.y + lila.y) * 0.5
            )
        }

        static var dialogueCameraWorldPosition: CGPoint {
            let focus = actorFocusPoint
            return CGPoint(x: focus.x, y: focus.y - cameraBelowActorMidpoint)
        }

        static func dialogueCameraPosition(playCamera: CGPoint) -> CGPoint {
            _ = playCamera
            return dialogueCameraWorldPosition
        }

        static var downwardOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return play.y - dialogueCameraWorldPosition.y
        }

        static var lateralOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return dialogueCameraWorldPosition.x - play.x
        }
    }

    static func makeGrid() -> NavigationGrid {
        NavigationGrid(
            projection: .dimetric(
                origin: OfficeInteriorScale.mapPoint(authoredProjectionOrigin),
                tileSize: OfficeInteriorScale.mapSize(authoredTileSize)
            ),
            columns: 31,
            rows: 31,
            obstacles: obstacles,
            agentProfile: .officeDetective
        )
    }

    static func isBlocked(_ point: CGPoint) -> Bool {
        obstacles.contains { $0.contains(point) }
    }
}

