import CoreGraphics

/// Generated by `generate_highlight_outline_polygons.py`. Do not hand-edit.
///
/// Rings drawn by hand over `office_suite_plate.png` and mapped through
/// `OfficeInteriorScale.mapPoint`, the way an area designer authored the
/// vertex rings an ARE stores for its doors, containers and regions.
extension OfficeHighlightOutlines {
    static let refinedPolygons: [String: [CGPoint]] = [
        "office.window": [CGPoint(x: 1733.5800, y: 1245.2200), CGPoint(x: 1763.2050, y: 1258.6500), CGPoint(x: 1765.5750, y: 1208.8800), CGPoint(x: 1735.5550, y: 1195.4500)],
        "office.desk": [CGPoint(x: 2017.9800, y: 1111.3150), CGPoint(x: 2069.7250, y: 1145.2850), CGPoint(x: 2107.6450, y: 1126.7200), CGPoint(x: 2108.8300, y: 1102.2300), CGPoint(x: 2051.9500, y: 1078.9250), CGPoint(x: 2017.9800, y: 1091.9600)],
        "office.phone": [CGPoint(x: 2083.5500, y: 1129.8800), CGPoint(x: 2093.4250, y: 1136.5950), CGPoint(x: 2106.4600, y: 1129.8800), CGPoint(x: 2096.5850, y: 1123.1650)],
        "office.files": [CGPoint(x: 2166.5000, y: 1471.9500), CGPoint(x: 2187.0400, y: 1484.9850), CGPoint(x: 2203.6300, y: 1468.3950), CGPoint(x: 2203.6300, y: 1404.0100), CGPoint(x: 2182.6950, y: 1390.9750), CGPoint(x: 2166.5000, y: 1407.9600)],
        "office.door": [CGPoint(x: 2152.2800, y: 941.8600), CGPoint(x: 2246.6850, y: 1002.6900), CGPoint(x: 2250.6350, y: 994.0000), CGPoint(x: 2156.2300, y: 933.1700)],
    ]
}
