import CoreGraphics

/// Generated by `ArtSource/Processing/office_layout_plan.py` — edit the
/// layout there and re-run, so art, navigation and previews stay in step.
///
/// Placements are authored in the shell's floor-plan basis: every prop sits on
/// a measured room axis, so furniture lines up with the painted walls.
enum OfficeNavigationLayout {
    enum Architecture {
        /// Shell-authoritative centre of the painted exterior threshold.
        static let entranceAnchor = CGPoint(x: 2_598.129, y: 1_234.916)
        /// Window insert centre on the painted left-wall recess.
        static let windowAnchor = CGPoint(x: 1_768.500, y: 1_705.000)
        /// Interior partition: one wall on the room's north-east axis (a = 0.39),
        /// with a single framed doorway as the only connection between rooms.
        static let partitionLineA: CGFloat = 0.39
        static let partitionThicknessA: CGFloat = 0.05336780838072318
        static let partitionDoorB0: CGFloat = 0.078
        static let partitionDoorB1: CGFloat = 0.21589197641062258
        static let partitionReturnB1: CGFloat = 0.24989197641062258
        static let wallThicknessPx: CGFloat = 12.0
        static let axisNW = CGVector(dx: -555.5, dy: 311.9)
        static let axisNE = CGVector(dx: 812.2, dy: 386.2)
        static let rearCorner = CGPoint(x: 1932.1, y: 1551.6)

        /// Partition plate geometry in shell art pixels (y down), so the scene can
        /// slice the painted wall into depth-sorted columns that sort like props
        /// standing on the wall's own ground line.
        static let partitionPlateX0: CGFloat = 1676
        static let partitionPlateX1: CGFloat = 2498
        static let partitionPlateFaceHeight: CGFloat = 309
        static let partitionPlateCapHeight: CGFloat = 5

        /// Ground line of the partition face at a shell-art x (y down).
        static func partitionPlateBaseY(atPlateX x: CGFloat) -> CGFloat {
            886.0 + (x - 1676) * 0.4755
        }

        /// Clear exterior opening measured from the shipping suite plate.
        static let entranceOpeningPlateSize = CGSize(width: 93.000, height: 206.0)
        static let entranceOpeningToDetectiveRatio: CGFloat = 0.90
        static let entranceHandleHeightToDetective: CGFloat = 0.333

        /// Exterior leaf/frame projected onto the sloped NE wall opening.
        /// Uniform height-fit (keeps sheared master aspect; no X-squash).
        static let entranceLeafDisplayScale: CGFloat = 0.1275
        static let entranceLeafDisplayScaleX: CGFloat = entranceLeafDisplayScale
        static let entranceLeafDisplayScaleY: CGFloat = entranceLeafDisplayScale
        static let entranceLeafAnchorY: CGFloat = 0.08903
        static let entranceLeafAnchor = CGPoint(x: 2_600.650, y: 1_344.000)
        static let entranceFrameDisplayScale: CGFloat = 0.1273
        static let entranceFrameDisplayScaleX: CGFloat = entranceFrameDisplayScale
        static let entranceFrameDisplayScaleY: CGFloat = entranceFrameDisplayScale
        static let entranceFrameAnchorX: CGFloat = 0.49155
        static let entranceFrameAnchorY: CGFloat = 0.11529
        /// Floor-projected presentation used after the leaf breaks free.
        static let entranceFallenLeafScaleRatio: CGFloat = 0.92
        /// Internal open leaf registered to the shipping partition hinge.
        static let internalHingePlateX: CGFloat = 2202.0
        static let internalHingePlateHeight: CGFloat = 220.0
        static let internalLeafDisplayScale: CGFloat = 0.2234
        static let internalLeafAnchor = CGPoint(x: 2_151.949, y: 1_002.148)
    }

    private static let authoredActorStart = CGPoint(
        x: AuthoredPlacement.deskChair.x,
        y: AuthoredPlacement.deskChair.y + 208
    )

    // MARK: - Obstacles (authored AABBs around each floor footprint)

    /// One cell of the camera-near boundary, kept named for the layout tests.
    static let authoredForegroundWallObstacle = CGRect(x: 2426, y: 1007, width: 104, height: 52)
    static let authoredDoorObstacle = CGRect(x: 2503, y: 1175, width: 190, height: 119)

    /// Room boundary: the rear and side walls plus the camera-near cutaway
    /// wall, one solid per navigation cell outside the painted floor.
    static let authoredBoundarySegments: [CGRect] = [
        CGRect(x: 1996, y: 129, width: 104, height: 52),
        CGRect(x: 1932, y: 161, width: 104, height: 52),
        CGRect(x: 1868, y: 193, width: 104, height: 52),
        CGRect(x: 1804, y: 225, width: 104, height: 52),
        CGRect(x: 1740, y: 257, width: 104, height: 52),
        CGRect(x: 1676, y: 289, width: 104, height: 52),
        CGRect(x: 1612, y: 321, width: 104, height: 52),
        CGRect(x: 1548, y: 353, width: 104, height: 52),
        CGRect(x: 1484, y: 385, width: 104, height: 52),
        CGRect(x: 1420, y: 417, width: 104, height: 52),
        CGRect(x: 1356, y: 449, width: 104, height: 52),
        CGRect(x: 1292, y: 481, width: 104, height: 52),
        CGRect(x: 1228, y: 513, width: 104, height: 52),
        CGRect(x: 1164, y: 545, width: 104, height: 52),
        CGRect(x: 1100, y: 577, width: 104, height: 52),
        CGRect(x: 1036, y: 609, width: 104, height: 52),
        CGRect(x: 972, y: 641, width: 104, height: 52),
        CGRect(x: 908, y: 673, width: 104, height: 52),
        CGRect(x: 844, y: 705, width: 104, height: 52),
        CGRect(x: 780, y: 737, width: 104, height: 52),
        CGRect(x: 716, y: 769, width: 104, height: 52),
        CGRect(x: 652, y: 801, width: 104, height: 52),
        CGRect(x: 588, y: 833, width: 104, height: 52),
        CGRect(x: 524, y: 865, width: 104, height: 52),
        CGRect(x: 460, y: 897, width: 104, height: 52),
        CGRect(x: 396, y: 929, width: 104, height: 52),
        CGRect(x: 332, y: 961, width: 104, height: 52),
        CGRect(x: 268, y: 993, width: 104, height: 52),
        CGRect(x: 204, y: 1025, width: 104, height: 52),
        CGRect(x: 140, y: 1057, width: 104, height: 52),
        CGRect(x: 76, y: 1089, width: 104, height: 52),
        CGRect(x: 2060, y: 161, width: 104, height: 52),
        CGRect(x: 1996, y: 193, width: 104, height: 52),
        CGRect(x: 1932, y: 225, width: 104, height: 52),
        CGRect(x: 1868, y: 257, width: 104, height: 52),
        CGRect(x: 1804, y: 289, width: 104, height: 52),
        CGRect(x: 1740, y: 321, width: 104, height: 52),
        CGRect(x: 1676, y: 353, width: 104, height: 52),
        CGRect(x: 1612, y: 385, width: 104, height: 52),
        CGRect(x: 1548, y: 417, width: 104, height: 52),
        CGRect(x: 1484, y: 449, width: 104, height: 52),
        CGRect(x: 1420, y: 481, width: 104, height: 52),
        CGRect(x: 1356, y: 513, width: 104, height: 52),
        CGRect(x: 1292, y: 545, width: 104, height: 52),
        CGRect(x: 1228, y: 577, width: 104, height: 52),
        CGRect(x: 1164, y: 609, width: 104, height: 52),
        CGRect(x: 1100, y: 641, width: 104, height: 52),
        CGRect(x: 1036, y: 673, width: 104, height: 52),
        CGRect(x: 972, y: 705, width: 104, height: 52),
        CGRect(x: 908, y: 737, width: 104, height: 52),
        CGRect(x: 844, y: 769, width: 104, height: 52),
        CGRect(x: 780, y: 801, width: 104, height: 52),
        CGRect(x: 716, y: 833, width: 104, height: 52),
        CGRect(x: 652, y: 865, width: 104, height: 52),
        CGRect(x: 588, y: 897, width: 104, height: 52),
        CGRect(x: 524, y: 929, width: 104, height: 52),
        CGRect(x: 460, y: 961, width: 104, height: 52),
        CGRect(x: 396, y: 993, width: 104, height: 52),
        CGRect(x: 332, y: 1025, width: 104, height: 52),
        CGRect(x: 268, y: 1057, width: 104, height: 52),
        CGRect(x: 204, y: 1089, width: 104, height: 52),
        CGRect(x: 140, y: 1121, width: 104, height: 52),
        CGRect(x: 2124, y: 193, width: 104, height: 52),
        CGRect(x: 2060, y: 225, width: 104, height: 52),
        CGRect(x: 1996, y: 257, width: 104, height: 52),
        CGRect(x: 1932, y: 289, width: 104, height: 52),
        CGRect(x: 1868, y: 321, width: 104, height: 52),
        CGRect(x: 1804, y: 353, width: 104, height: 52),
        CGRect(x: 1740, y: 385, width: 104, height: 52),
        CGRect(x: 1676, y: 417, width: 104, height: 52),
        CGRect(x: 1612, y: 449, width: 104, height: 52),
        CGRect(x: 1548, y: 481, width: 104, height: 52),
        CGRect(x: 1484, y: 513, width: 104, height: 52),
        CGRect(x: 1420, y: 545, width: 104, height: 52),
        CGRect(x: 1356, y: 577, width: 104, height: 52),
        CGRect(x: 1292, y: 609, width: 104, height: 52),
        CGRect(x: 1228, y: 641, width: 104, height: 52),
        CGRect(x: 1164, y: 673, width: 104, height: 52),
        CGRect(x: 1100, y: 705, width: 104, height: 52),
        CGRect(x: 1036, y: 737, width: 104, height: 52),
        CGRect(x: 972, y: 769, width: 104, height: 52),
        CGRect(x: 908, y: 801, width: 104, height: 52),
        CGRect(x: 844, y: 833, width: 104, height: 52),
        CGRect(x: 780, y: 865, width: 104, height: 52),
        CGRect(x: 716, y: 897, width: 104, height: 52),
        CGRect(x: 652, y: 929, width: 104, height: 52),
        CGRect(x: 588, y: 961, width: 104, height: 52),
        CGRect(x: 524, y: 993, width: 104, height: 52),
        CGRect(x: 460, y: 1025, width: 104, height: 52),
        CGRect(x: 396, y: 1057, width: 104, height: 52),
        CGRect(x: 332, y: 1089, width: 104, height: 52),
        CGRect(x: 268, y: 1121, width: 104, height: 52),
        CGRect(x: 204, y: 1153, width: 104, height: 52),
        CGRect(x: 2188, y: 225, width: 104, height: 52),
        CGRect(x: 2124, y: 257, width: 104, height: 52),
        CGRect(x: 2060, y: 289, width: 104, height: 52),
        CGRect(x: 1996, y: 321, width: 104, height: 52),
        CGRect(x: 1932, y: 353, width: 104, height: 52),
        CGRect(x: 1868, y: 385, width: 104, height: 52),
        CGRect(x: 1804, y: 417, width: 104, height: 52),
        CGRect(x: 1740, y: 449, width: 104, height: 52),
        CGRect(x: 1676, y: 481, width: 104, height: 52),
        CGRect(x: 1612, y: 513, width: 104, height: 52),
        CGRect(x: 1548, y: 545, width: 104, height: 52),
        CGRect(x: 1484, y: 577, width: 104, height: 52),
        CGRect(x: 1420, y: 609, width: 104, height: 52),
        CGRect(x: 1356, y: 641, width: 104, height: 52),
        CGRect(x: 1292, y: 673, width: 104, height: 52),
        CGRect(x: 1228, y: 705, width: 104, height: 52),
        CGRect(x: 1164, y: 737, width: 104, height: 52),
        CGRect(x: 1100, y: 769, width: 104, height: 52),
        CGRect(x: 1036, y: 801, width: 104, height: 52),
        CGRect(x: 972, y: 833, width: 104, height: 52),
        CGRect(x: 908, y: 865, width: 104, height: 52),
        CGRect(x: 844, y: 897, width: 104, height: 52),
        CGRect(x: 780, y: 929, width: 104, height: 52),
        CGRect(x: 716, y: 961, width: 104, height: 52),
        CGRect(x: 652, y: 993, width: 104, height: 52),
        CGRect(x: 588, y: 1025, width: 104, height: 52),
        CGRect(x: 524, y: 1057, width: 104, height: 52),
        CGRect(x: 460, y: 1089, width: 104, height: 52),
        CGRect(x: 396, y: 1121, width: 104, height: 52),
        CGRect(x: 332, y: 1153, width: 104, height: 52),
        CGRect(x: 268, y: 1185, width: 104, height: 52),
        CGRect(x: 2252, y: 257, width: 104, height: 52),
        CGRect(x: 2188, y: 289, width: 104, height: 52),
        CGRect(x: 2124, y: 321, width: 104, height: 52),
        CGRect(x: 2060, y: 353, width: 104, height: 52),
        CGRect(x: 1996, y: 385, width: 104, height: 52),
        CGRect(x: 1932, y: 417, width: 104, height: 52),
        CGRect(x: 1868, y: 449, width: 104, height: 52),
        CGRect(x: 1804, y: 481, width: 104, height: 52),
        CGRect(x: 1740, y: 513, width: 104, height: 52),
        CGRect(x: 1676, y: 545, width: 104, height: 52),
        CGRect(x: 1612, y: 577, width: 104, height: 52),
        CGRect(x: 1548, y: 609, width: 104, height: 52),
        CGRect(x: 1484, y: 641, width: 104, height: 52),
        CGRect(x: 1420, y: 673, width: 104, height: 52),
        CGRect(x: 1356, y: 705, width: 104, height: 52),
        CGRect(x: 1292, y: 737, width: 104, height: 52),
        CGRect(x: 1228, y: 769, width: 104, height: 52),
        CGRect(x: 1164, y: 801, width: 104, height: 52),
        CGRect(x: 1100, y: 833, width: 104, height: 52),
        CGRect(x: 1036, y: 865, width: 104, height: 52),
        CGRect(x: 972, y: 897, width: 104, height: 52),
        CGRect(x: 908, y: 929, width: 104, height: 52),
        CGRect(x: 844, y: 961, width: 104, height: 52),
        CGRect(x: 780, y: 993, width: 104, height: 52),
        CGRect(x: 716, y: 1025, width: 104, height: 52),
        CGRect(x: 652, y: 1057, width: 104, height: 52),
        CGRect(x: 588, y: 1089, width: 104, height: 52),
        CGRect(x: 524, y: 1121, width: 104, height: 52),
        CGRect(x: 460, y: 1153, width: 104, height: 52),
        CGRect(x: 396, y: 1185, width: 104, height: 52),
        CGRect(x: 332, y: 1217, width: 104, height: 52),
        CGRect(x: 2316, y: 289, width: 104, height: 52),
        CGRect(x: 2252, y: 321, width: 104, height: 52),
        CGRect(x: 2188, y: 353, width: 104, height: 52),
        CGRect(x: 2124, y: 385, width: 104, height: 52),
        CGRect(x: 2060, y: 417, width: 104, height: 52),
        CGRect(x: 1996, y: 449, width: 104, height: 52),
        CGRect(x: 1932, y: 481, width: 104, height: 52),
        CGRect(x: 1868, y: 513, width: 104, height: 52),
        CGRect(x: 1804, y: 545, width: 104, height: 52),
        CGRect(x: 1740, y: 577, width: 104, height: 52),
        CGRect(x: 1676, y: 609, width: 104, height: 52),
        CGRect(x: 1612, y: 641, width: 104, height: 52),
        CGRect(x: 1548, y: 673, width: 104, height: 52),
        CGRect(x: 1484, y: 705, width: 104, height: 52),
        CGRect(x: 1420, y: 737, width: 104, height: 52),
        CGRect(x: 1356, y: 769, width: 104, height: 52),
        CGRect(x: 1292, y: 801, width: 104, height: 52),
        CGRect(x: 1228, y: 833, width: 104, height: 52),
        CGRect(x: 1164, y: 865, width: 104, height: 52),
        CGRect(x: 1100, y: 897, width: 104, height: 52),
        CGRect(x: 1036, y: 929, width: 104, height: 52),
        CGRect(x: 972, y: 961, width: 104, height: 52),
        CGRect(x: 908, y: 993, width: 104, height: 52),
        CGRect(x: 844, y: 1025, width: 104, height: 52),
        CGRect(x: 780, y: 1057, width: 104, height: 52),
        CGRect(x: 716, y: 1089, width: 104, height: 52),
        CGRect(x: 652, y: 1121, width: 104, height: 52),
        CGRect(x: 588, y: 1153, width: 104, height: 52),
        CGRect(x: 524, y: 1185, width: 104, height: 52),
        CGRect(x: 460, y: 1217, width: 104, height: 52),
        CGRect(x: 396, y: 1249, width: 104, height: 52),
        CGRect(x: 2380, y: 321, width: 104, height: 52),
        CGRect(x: 2316, y: 353, width: 104, height: 52),
        CGRect(x: 2252, y: 385, width: 104, height: 52),
        CGRect(x: 2188, y: 417, width: 104, height: 52),
        CGRect(x: 2124, y: 449, width: 104, height: 52),
        CGRect(x: 2060, y: 481, width: 104, height: 52),
        CGRect(x: 1996, y: 513, width: 104, height: 52),
        CGRect(x: 1932, y: 545, width: 104, height: 52),
        CGRect(x: 1868, y: 577, width: 104, height: 52),
        CGRect(x: 1804, y: 609, width: 104, height: 52),
        CGRect(x: 1740, y: 641, width: 104, height: 52),
        CGRect(x: 1676, y: 673, width: 104, height: 52),
        CGRect(x: 1612, y: 705, width: 104, height: 52),
        CGRect(x: 1548, y: 737, width: 104, height: 52),
        CGRect(x: 1484, y: 769, width: 104, height: 52),
        CGRect(x: 1420, y: 801, width: 104, height: 52),
        CGRect(x: 1356, y: 833, width: 104, height: 52),
        CGRect(x: 1292, y: 865, width: 104, height: 52),
        CGRect(x: 1228, y: 897, width: 104, height: 52),
        CGRect(x: 1164, y: 929, width: 104, height: 52),
        CGRect(x: 1100, y: 961, width: 104, height: 52),
        CGRect(x: 1036, y: 993, width: 104, height: 52),
        CGRect(x: 972, y: 1025, width: 104, height: 52),
        CGRect(x: 908, y: 1057, width: 104, height: 52),
        CGRect(x: 844, y: 1089, width: 104, height: 52),
        CGRect(x: 780, y: 1121, width: 104, height: 52),
        CGRect(x: 716, y: 1153, width: 104, height: 52),
        CGRect(x: 652, y: 1185, width: 104, height: 52),
        CGRect(x: 588, y: 1217, width: 104, height: 52),
        CGRect(x: 524, y: 1249, width: 104, height: 52),
        CGRect(x: 460, y: 1281, width: 104, height: 52),
        CGRect(x: 2444, y: 353, width: 104, height: 52),
        CGRect(x: 2380, y: 385, width: 104, height: 52),
        CGRect(x: 2316, y: 417, width: 104, height: 52),
        CGRect(x: 2252, y: 449, width: 104, height: 52),
        CGRect(x: 2188, y: 481, width: 104, height: 52),
        CGRect(x: 2124, y: 513, width: 104, height: 52),
        CGRect(x: 2060, y: 545, width: 104, height: 52),
        CGRect(x: 1996, y: 577, width: 104, height: 52),
        CGRect(x: 1932, y: 609, width: 104, height: 52),
        CGRect(x: 1868, y: 641, width: 104, height: 52),
        CGRect(x: 1804, y: 673, width: 104, height: 52),
        CGRect(x: 1740, y: 705, width: 104, height: 52),
        CGRect(x: 1676, y: 737, width: 104, height: 52),
        CGRect(x: 1612, y: 769, width: 104, height: 52),
        CGRect(x: 1548, y: 801, width: 104, height: 52),
        CGRect(x: 1484, y: 833, width: 104, height: 52),
        CGRect(x: 1420, y: 865, width: 104, height: 52),
        CGRect(x: 1356, y: 897, width: 104, height: 52),
        CGRect(x: 1292, y: 929, width: 104, height: 52),
        CGRect(x: 1228, y: 961, width: 104, height: 52),
        CGRect(x: 1164, y: 993, width: 104, height: 52),
        CGRect(x: 1100, y: 1025, width: 104, height: 52),
        CGRect(x: 1036, y: 1057, width: 104, height: 52),
        CGRect(x: 972, y: 1089, width: 104, height: 52),
        CGRect(x: 908, y: 1121, width: 104, height: 52),
        CGRect(x: 844, y: 1153, width: 104, height: 52),
        CGRect(x: 780, y: 1185, width: 104, height: 52),
        CGRect(x: 716, y: 1217, width: 104, height: 52),
        CGRect(x: 652, y: 1249, width: 104, height: 52),
        CGRect(x: 588, y: 1281, width: 104, height: 52),
        CGRect(x: 524, y: 1313, width: 104, height: 52),
        CGRect(x: 2508, y: 385, width: 104, height: 52),
        CGRect(x: 2444, y: 417, width: 104, height: 52),
        CGRect(x: 2380, y: 449, width: 104, height: 52),
        CGRect(x: 2316, y: 481, width: 104, height: 52),
        CGRect(x: 2252, y: 513, width: 104, height: 52),
        CGRect(x: 2188, y: 545, width: 104, height: 52),
        CGRect(x: 2124, y: 577, width: 104, height: 52),
        CGRect(x: 2060, y: 609, width: 104, height: 52),
        CGRect(x: 1996, y: 641, width: 104, height: 52),
        CGRect(x: 1932, y: 673, width: 104, height: 52),
        CGRect(x: 1868, y: 705, width: 104, height: 52),
        CGRect(x: 1804, y: 737, width: 104, height: 52),
        CGRect(x: 1740, y: 769, width: 104, height: 52),
        CGRect(x: 1676, y: 801, width: 104, height: 52),
        CGRect(x: 1612, y: 833, width: 104, height: 52),
        CGRect(x: 1548, y: 865, width: 104, height: 52),
        CGRect(x: 1484, y: 897, width: 104, height: 52),
        CGRect(x: 1420, y: 929, width: 104, height: 52),
        CGRect(x: 1356, y: 961, width: 104, height: 52),
        CGRect(x: 1292, y: 993, width: 104, height: 52),
        CGRect(x: 1228, y: 1025, width: 104, height: 52),
        CGRect(x: 1164, y: 1057, width: 104, height: 52),
        CGRect(x: 1100, y: 1089, width: 104, height: 52),
        CGRect(x: 1036, y: 1121, width: 104, height: 52),
        CGRect(x: 972, y: 1153, width: 104, height: 52),
        CGRect(x: 908, y: 1185, width: 104, height: 52),
        CGRect(x: 844, y: 1217, width: 104, height: 52),
        CGRect(x: 780, y: 1249, width: 104, height: 52),
        CGRect(x: 716, y: 1281, width: 104, height: 52),
        CGRect(x: 652, y: 1313, width: 104, height: 52),
        CGRect(x: 588, y: 1345, width: 104, height: 52),
        CGRect(x: 2572, y: 417, width: 104, height: 52),
        CGRect(x: 2508, y: 449, width: 104, height: 52),
        CGRect(x: 2444, y: 481, width: 104, height: 52),
        CGRect(x: 2380, y: 513, width: 104, height: 52),
        CGRect(x: 2316, y: 545, width: 104, height: 52),
        CGRect(x: 2252, y: 577, width: 104, height: 52),
        CGRect(x: 2188, y: 609, width: 104, height: 52),
        CGRect(x: 2124, y: 641, width: 104, height: 52),
        CGRect(x: 2060, y: 673, width: 104, height: 52),
        CGRect(x: 1996, y: 705, width: 104, height: 52),
        CGRect(x: 1932, y: 737, width: 104, height: 52),
        CGRect(x: 1868, y: 769, width: 104, height: 52),
        CGRect(x: 1804, y: 801, width: 104, height: 52),
        CGRect(x: 1740, y: 833, width: 104, height: 52),
        CGRect(x: 1676, y: 865, width: 104, height: 52),
        CGRect(x: 1612, y: 897, width: 104, height: 52),
        CGRect(x: 1548, y: 929, width: 104, height: 52),
        CGRect(x: 1484, y: 961, width: 104, height: 52),
        CGRect(x: 1420, y: 993, width: 104, height: 52),
        CGRect(x: 1356, y: 1025, width: 104, height: 52),
        CGRect(x: 1292, y: 1057, width: 104, height: 52),
        CGRect(x: 1228, y: 1089, width: 104, height: 52),
        CGRect(x: 1164, y: 1121, width: 104, height: 52),
        CGRect(x: 1100, y: 1153, width: 104, height: 52),
        CGRect(x: 1036, y: 1185, width: 104, height: 52),
        CGRect(x: 972, y: 1217, width: 104, height: 52),
        CGRect(x: 908, y: 1249, width: 104, height: 52),
        CGRect(x: 844, y: 1281, width: 104, height: 52),
        CGRect(x: 780, y: 1313, width: 104, height: 52),
        CGRect(x: 716, y: 1345, width: 104, height: 52),
        CGRect(x: 652, y: 1377, width: 104, height: 52),
        CGRect(x: 2636, y: 449, width: 104, height: 52),
        CGRect(x: 2572, y: 481, width: 104, height: 52),
        CGRect(x: 2508, y: 513, width: 104, height: 52),
        CGRect(x: 2444, y: 545, width: 104, height: 52),
        CGRect(x: 2380, y: 577, width: 104, height: 52),
        CGRect(x: 2316, y: 609, width: 104, height: 52),
        CGRect(x: 2252, y: 641, width: 104, height: 52),
        CGRect(x: 2188, y: 673, width: 104, height: 52),
        CGRect(x: 2124, y: 705, width: 104, height: 52),
        CGRect(x: 2060, y: 737, width: 104, height: 52),
        CGRect(x: 1996, y: 769, width: 104, height: 52),
        CGRect(x: 1932, y: 801, width: 104, height: 52),
        CGRect(x: 1868, y: 833, width: 104, height: 52),
        CGRect(x: 1804, y: 865, width: 104, height: 52),
        CGRect(x: 1740, y: 897, width: 104, height: 52),
        CGRect(x: 1676, y: 929, width: 104, height: 52),
        CGRect(x: 1612, y: 961, width: 104, height: 52),
        CGRect(x: 1548, y: 993, width: 104, height: 52),
        CGRect(x: 1484, y: 1025, width: 104, height: 52),
        CGRect(x: 1420, y: 1057, width: 104, height: 52),
        CGRect(x: 1356, y: 1089, width: 104, height: 52),
        CGRect(x: 1292, y: 1121, width: 104, height: 52),
        CGRect(x: 1228, y: 1153, width: 104, height: 52),
        CGRect(x: 1164, y: 1185, width: 104, height: 52),
        CGRect(x: 1100, y: 1217, width: 104, height: 52),
        CGRect(x: 1036, y: 1249, width: 104, height: 52),
        CGRect(x: 972, y: 1281, width: 104, height: 52),
        CGRect(x: 908, y: 1313, width: 104, height: 52),
        CGRect(x: 844, y: 1345, width: 104, height: 52),
        CGRect(x: 780, y: 1377, width: 104, height: 52),
        CGRect(x: 716, y: 1409, width: 104, height: 52),
        CGRect(x: 2700, y: 481, width: 104, height: 52),
        CGRect(x: 2636, y: 513, width: 104, height: 52),
        CGRect(x: 2572, y: 545, width: 104, height: 52),
        CGRect(x: 2508, y: 577, width: 104, height: 52),
        CGRect(x: 2444, y: 609, width: 104, height: 52),
        CGRect(x: 2380, y: 641, width: 104, height: 52),
        CGRect(x: 2316, y: 673, width: 104, height: 52),
        CGRect(x: 2252, y: 705, width: 104, height: 52),
        CGRect(x: 2188, y: 737, width: 104, height: 52),
        CGRect(x: 2124, y: 769, width: 104, height: 52),
        CGRect(x: 2060, y: 801, width: 104, height: 52),
        CGRect(x: 1996, y: 833, width: 104, height: 52),
        CGRect(x: 1932, y: 865, width: 104, height: 52),
        CGRect(x: 1868, y: 897, width: 104, height: 52),
        CGRect(x: 1804, y: 929, width: 104, height: 52),
        CGRect(x: 1740, y: 961, width: 104, height: 52),
        CGRect(x: 1676, y: 993, width: 104, height: 52),
        CGRect(x: 1612, y: 1025, width: 104, height: 52),
        CGRect(x: 1548, y: 1057, width: 104, height: 52),
        CGRect(x: 1484, y: 1089, width: 104, height: 52),
        CGRect(x: 1420, y: 1121, width: 104, height: 52),
        CGRect(x: 1356, y: 1153, width: 104, height: 52),
        CGRect(x: 1292, y: 1185, width: 104, height: 52),
        CGRect(x: 1228, y: 1217, width: 104, height: 52),
        CGRect(x: 1164, y: 1249, width: 104, height: 52),
        CGRect(x: 1100, y: 1281, width: 104, height: 52),
        CGRect(x: 1036, y: 1313, width: 104, height: 52),
        CGRect(x: 972, y: 1345, width: 104, height: 52),
        CGRect(x: 908, y: 1377, width: 104, height: 52),
        CGRect(x: 844, y: 1409, width: 104, height: 52),
        CGRect(x: 780, y: 1441, width: 104, height: 52),
        CGRect(x: 2764, y: 513, width: 104, height: 52),
        CGRect(x: 2700, y: 545, width: 104, height: 52),
        CGRect(x: 2636, y: 577, width: 104, height: 52),
        CGRect(x: 2572, y: 609, width: 104, height: 52),
        CGRect(x: 2508, y: 641, width: 104, height: 52),
        CGRect(x: 2444, y: 673, width: 104, height: 52),
        CGRect(x: 2380, y: 705, width: 104, height: 52),
        CGRect(x: 2316, y: 737, width: 104, height: 52),
        CGRect(x: 2252, y: 769, width: 104, height: 52),
        CGRect(x: 2188, y: 801, width: 104, height: 52),
        CGRect(x: 2124, y: 833, width: 104, height: 52),
        CGRect(x: 2060, y: 865, width: 104, height: 52),
        CGRect(x: 1996, y: 897, width: 104, height: 52),
        CGRect(x: 1932, y: 929, width: 104, height: 52),
        CGRect(x: 1868, y: 961, width: 104, height: 52),
        CGRect(x: 1804, y: 993, width: 104, height: 52),
        CGRect(x: 1740, y: 1025, width: 104, height: 52),
        CGRect(x: 1676, y: 1057, width: 104, height: 52),
        CGRect(x: 1612, y: 1089, width: 104, height: 52),
        CGRect(x: 1548, y: 1121, width: 104, height: 52),
        CGRect(x: 1484, y: 1153, width: 104, height: 52),
        CGRect(x: 1420, y: 1185, width: 104, height: 52),
        CGRect(x: 1356, y: 1217, width: 104, height: 52),
        CGRect(x: 1292, y: 1249, width: 104, height: 52),
        CGRect(x: 1228, y: 1281, width: 104, height: 52),
        CGRect(x: 1164, y: 1313, width: 104, height: 52),
        CGRect(x: 1100, y: 1345, width: 104, height: 52),
        CGRect(x: 1036, y: 1377, width: 104, height: 52),
        CGRect(x: 972, y: 1409, width: 104, height: 52),
        CGRect(x: 908, y: 1441, width: 104, height: 52),
        CGRect(x: 844, y: 1473, width: 104, height: 52),
        CGRect(x: 2828, y: 545, width: 104, height: 52),
        CGRect(x: 2764, y: 577, width: 104, height: 52),
        CGRect(x: 2700, y: 609, width: 104, height: 52),
        CGRect(x: 2636, y: 641, width: 104, height: 52),
        CGRect(x: 2572, y: 673, width: 104, height: 52),
        CGRect(x: 2508, y: 705, width: 104, height: 52),
        CGRect(x: 2444, y: 737, width: 104, height: 52),
        CGRect(x: 2380, y: 769, width: 104, height: 52),
        CGRect(x: 2316, y: 801, width: 104, height: 52),
        CGRect(x: 2252, y: 833, width: 104, height: 52),
        CGRect(x: 2188, y: 865, width: 104, height: 52),
        CGRect(x: 1420, y: 1249, width: 104, height: 52),
        CGRect(x: 1356, y: 1281, width: 104, height: 52),
        CGRect(x: 1292, y: 1313, width: 104, height: 52),
        CGRect(x: 1228, y: 1345, width: 104, height: 52),
        CGRect(x: 1164, y: 1377, width: 104, height: 52),
        CGRect(x: 1100, y: 1409, width: 104, height: 52),
        CGRect(x: 1036, y: 1441, width: 104, height: 52),
        CGRect(x: 972, y: 1473, width: 104, height: 52),
        CGRect(x: 908, y: 1505, width: 104, height: 52),
        CGRect(x: 2892, y: 577, width: 104, height: 52),
        CGRect(x: 2828, y: 609, width: 104, height: 52),
        CGRect(x: 2764, y: 641, width: 104, height: 52),
        CGRect(x: 2700, y: 673, width: 104, height: 52),
        CGRect(x: 2636, y: 705, width: 104, height: 52),
        CGRect(x: 2572, y: 737, width: 104, height: 52),
        CGRect(x: 2508, y: 769, width: 104, height: 52),
        CGRect(x: 2444, y: 801, width: 104, height: 52),
        CGRect(x: 2380, y: 833, width: 104, height: 52),
        CGRect(x: 2316, y: 865, width: 104, height: 52),
        CGRect(x: 2252, y: 897, width: 104, height: 52),
        CGRect(x: 1484, y: 1281, width: 104, height: 52),
        CGRect(x: 1420, y: 1313, width: 104, height: 52),
        CGRect(x: 1356, y: 1345, width: 104, height: 52),
        CGRect(x: 1292, y: 1377, width: 104, height: 52),
        CGRect(x: 1228, y: 1409, width: 104, height: 52),
        CGRect(x: 1164, y: 1441, width: 104, height: 52),
        CGRect(x: 1100, y: 1473, width: 104, height: 52),
        CGRect(x: 1036, y: 1505, width: 104, height: 52),
        CGRect(x: 972, y: 1537, width: 104, height: 52),
        CGRect(x: 2956, y: 609, width: 104, height: 52),
        CGRect(x: 2892, y: 641, width: 104, height: 52),
        CGRect(x: 2828, y: 673, width: 104, height: 52),
        CGRect(x: 2764, y: 705, width: 104, height: 52),
        CGRect(x: 2700, y: 737, width: 104, height: 52),
        CGRect(x: 2636, y: 769, width: 104, height: 52),
        CGRect(x: 2572, y: 801, width: 104, height: 52),
        CGRect(x: 2508, y: 833, width: 104, height: 52),
        CGRect(x: 2444, y: 865, width: 104, height: 52),
        CGRect(x: 2380, y: 897, width: 104, height: 52),
        CGRect(x: 2316, y: 929, width: 104, height: 52),
        CGRect(x: 1548, y: 1313, width: 104, height: 52),
        CGRect(x: 1484, y: 1345, width: 104, height: 52),
        CGRect(x: 1420, y: 1377, width: 104, height: 52),
        CGRect(x: 1356, y: 1409, width: 104, height: 52),
        CGRect(x: 1292, y: 1441, width: 104, height: 52),
        CGRect(x: 1228, y: 1473, width: 104, height: 52),
        CGRect(x: 1164, y: 1505, width: 104, height: 52),
        CGRect(x: 1100, y: 1537, width: 104, height: 52),
        CGRect(x: 1036, y: 1569, width: 104, height: 52),
        CGRect(x: 3020, y: 641, width: 104, height: 52),
        CGRect(x: 2956, y: 673, width: 104, height: 52),
        CGRect(x: 2892, y: 705, width: 104, height: 52),
        CGRect(x: 2828, y: 737, width: 104, height: 52),
        CGRect(x: 2764, y: 769, width: 104, height: 52),
        CGRect(x: 2700, y: 801, width: 104, height: 52),
        CGRect(x: 2636, y: 833, width: 104, height: 52),
        CGRect(x: 2572, y: 865, width: 104, height: 52),
        CGRect(x: 2508, y: 897, width: 104, height: 52),
        CGRect(x: 2444, y: 929, width: 104, height: 52),
        CGRect(x: 2380, y: 961, width: 104, height: 52),
        CGRect(x: 1612, y: 1345, width: 104, height: 52),
        CGRect(x: 1548, y: 1377, width: 104, height: 52),
        CGRect(x: 1484, y: 1409, width: 104, height: 52),
        CGRect(x: 1420, y: 1441, width: 104, height: 52),
        CGRect(x: 1356, y: 1473, width: 104, height: 52),
        CGRect(x: 1292, y: 1505, width: 104, height: 52),
        CGRect(x: 1228, y: 1537, width: 104, height: 52),
        CGRect(x: 1164, y: 1569, width: 104, height: 52),
        CGRect(x: 1100, y: 1601, width: 104, height: 52),
        CGRect(x: 3084, y: 673, width: 104, height: 52),
        CGRect(x: 3020, y: 705, width: 104, height: 52),
        CGRect(x: 2956, y: 737, width: 104, height: 52),
        CGRect(x: 2892, y: 769, width: 104, height: 52),
        CGRect(x: 2828, y: 801, width: 104, height: 52),
        CGRect(x: 2764, y: 833, width: 104, height: 52),
        CGRect(x: 2700, y: 865, width: 104, height: 52),
        CGRect(x: 2636, y: 897, width: 104, height: 52),
        CGRect(x: 2572, y: 929, width: 104, height: 52),
        CGRect(x: 2508, y: 961, width: 104, height: 52),
        CGRect(x: 2444, y: 993, width: 104, height: 52),
        CGRect(x: 1612, y: 1409, width: 104, height: 52),
        CGRect(x: 1548, y: 1441, width: 104, height: 52),
        CGRect(x: 1484, y: 1473, width: 104, height: 52),
        CGRect(x: 1420, y: 1505, width: 104, height: 52),
        CGRect(x: 1356, y: 1537, width: 104, height: 52),
        CGRect(x: 1292, y: 1569, width: 104, height: 52),
        CGRect(x: 1228, y: 1601, width: 104, height: 52),
        CGRect(x: 1164, y: 1633, width: 104, height: 52),
        CGRect(x: 3148, y: 705, width: 104, height: 52),
        CGRect(x: 3084, y: 737, width: 104, height: 52),
        CGRect(x: 3020, y: 769, width: 104, height: 52),
        CGRect(x: 2956, y: 801, width: 104, height: 52),
        CGRect(x: 2892, y: 833, width: 104, height: 52),
        CGRect(x: 2828, y: 865, width: 104, height: 52),
        CGRect(x: 2764, y: 897, width: 104, height: 52),
        CGRect(x: 2700, y: 929, width: 104, height: 52),
        CGRect(x: 2636, y: 961, width: 104, height: 52),
        CGRect(x: 2572, y: 993, width: 104, height: 52),
        CGRect(x: 2508, y: 1025, width: 104, height: 52),
        CGRect(x: 1676, y: 1441, width: 104, height: 52),
        CGRect(x: 1612, y: 1473, width: 104, height: 52),
        CGRect(x: 1548, y: 1505, width: 104, height: 52),
        CGRect(x: 1484, y: 1537, width: 104, height: 52),
        CGRect(x: 1420, y: 1569, width: 104, height: 52),
        CGRect(x: 1356, y: 1601, width: 104, height: 52),
        CGRect(x: 1292, y: 1633, width: 104, height: 52),
        CGRect(x: 1228, y: 1665, width: 104, height: 52),
        CGRect(x: 3212, y: 737, width: 104, height: 52),
        CGRect(x: 3148, y: 769, width: 104, height: 52),
        CGRect(x: 3084, y: 801, width: 104, height: 52),
        CGRect(x: 3020, y: 833, width: 104, height: 52),
        CGRect(x: 2956, y: 865, width: 104, height: 52),
        CGRect(x: 2892, y: 897, width: 104, height: 52),
        CGRect(x: 2828, y: 929, width: 104, height: 52),
        CGRect(x: 2764, y: 961, width: 104, height: 52),
        CGRect(x: 2700, y: 993, width: 104, height: 52),
        CGRect(x: 2636, y: 1025, width: 104, height: 52),
        CGRect(x: 2572, y: 1057, width: 104, height: 52),
        CGRect(x: 1740, y: 1473, width: 104, height: 52),
        CGRect(x: 1676, y: 1505, width: 104, height: 52),
        CGRect(x: 1612, y: 1537, width: 104, height: 52),
        CGRect(x: 1548, y: 1569, width: 104, height: 52),
        CGRect(x: 1484, y: 1601, width: 104, height: 52),
        CGRect(x: 1420, y: 1633, width: 104, height: 52),
        CGRect(x: 1356, y: 1665, width: 104, height: 52),
        CGRect(x: 1292, y: 1697, width: 104, height: 52),
        CGRect(x: 3276, y: 769, width: 104, height: 52),
        CGRect(x: 3212, y: 801, width: 104, height: 52),
        CGRect(x: 3148, y: 833, width: 104, height: 52),
        CGRect(x: 3084, y: 865, width: 104, height: 52),
        CGRect(x: 3020, y: 897, width: 104, height: 52),
        CGRect(x: 2956, y: 929, width: 104, height: 52),
        CGRect(x: 2892, y: 961, width: 104, height: 52),
        CGRect(x: 2828, y: 993, width: 104, height: 52),
        CGRect(x: 2764, y: 1025, width: 104, height: 52),
        CGRect(x: 2700, y: 1057, width: 104, height: 52),
        CGRect(x: 2636, y: 1089, width: 104, height: 52),
        CGRect(x: 1804, y: 1505, width: 104, height: 52),
        CGRect(x: 1740, y: 1537, width: 104, height: 52),
        CGRect(x: 1676, y: 1569, width: 104, height: 52),
        CGRect(x: 1612, y: 1601, width: 104, height: 52),
        CGRect(x: 1548, y: 1633, width: 104, height: 52),
        CGRect(x: 1484, y: 1665, width: 104, height: 52),
        CGRect(x: 1420, y: 1697, width: 104, height: 52),
        CGRect(x: 1356, y: 1729, width: 104, height: 52),
        CGRect(x: 3340, y: 801, width: 104, height: 52),
        CGRect(x: 3276, y: 833, width: 104, height: 52),
        CGRect(x: 3212, y: 865, width: 104, height: 52),
        CGRect(x: 3148, y: 897, width: 104, height: 52),
        CGRect(x: 3084, y: 929, width: 104, height: 52),
        CGRect(x: 3020, y: 961, width: 104, height: 52),
        CGRect(x: 2956, y: 993, width: 104, height: 52),
        CGRect(x: 2892, y: 1025, width: 104, height: 52),
        CGRect(x: 2828, y: 1057, width: 104, height: 52),
        CGRect(x: 2764, y: 1089, width: 104, height: 52),
        CGRect(x: 2700, y: 1121, width: 104, height: 52),
        CGRect(x: 2636, y: 1153, width: 104, height: 52),
        CGRect(x: 2572, y: 1185, width: 104, height: 52),
        CGRect(x: 2508, y: 1217, width: 104, height: 52),
        CGRect(x: 2444, y: 1249, width: 104, height: 52),
        CGRect(x: 2380, y: 1281, width: 104, height: 52),
        CGRect(x: 2316, y: 1313, width: 104, height: 52),
        CGRect(x: 2252, y: 1345, width: 104, height: 52),
        CGRect(x: 2188, y: 1377, width: 104, height: 52),
        CGRect(x: 2124, y: 1409, width: 104, height: 52),
        CGRect(x: 2060, y: 1441, width: 104, height: 52),
        CGRect(x: 1996, y: 1473, width: 104, height: 52),
        CGRect(x: 1932, y: 1505, width: 104, height: 52),
        CGRect(x: 1868, y: 1537, width: 104, height: 52),
        CGRect(x: 1804, y: 1569, width: 104, height: 52),
        CGRect(x: 1740, y: 1601, width: 104, height: 52),
        CGRect(x: 1676, y: 1633, width: 104, height: 52),
        CGRect(x: 1612, y: 1665, width: 104, height: 52),
        CGRect(x: 1548, y: 1697, width: 104, height: 52),
        CGRect(x: 1484, y: 1729, width: 104, height: 52),
        CGRect(x: 1420, y: 1761, width: 104, height: 52),
        CGRect(x: 3404, y: 833, width: 104, height: 52),
        CGRect(x: 3340, y: 865, width: 104, height: 52),
        CGRect(x: 3276, y: 897, width: 104, height: 52),
        CGRect(x: 3212, y: 929, width: 104, height: 52),
        CGRect(x: 3148, y: 961, width: 104, height: 52),
        CGRect(x: 3084, y: 993, width: 104, height: 52),
        CGRect(x: 3020, y: 1025, width: 104, height: 52),
        CGRect(x: 2956, y: 1057, width: 104, height: 52),
        CGRect(x: 2892, y: 1089, width: 104, height: 52),
        CGRect(x: 2828, y: 1121, width: 104, height: 52),
        CGRect(x: 2764, y: 1153, width: 104, height: 52),
        CGRect(x: 2700, y: 1185, width: 104, height: 52),
        CGRect(x: 2636, y: 1217, width: 104, height: 52),
        CGRect(x: 2572, y: 1249, width: 104, height: 52),
        CGRect(x: 2508, y: 1281, width: 104, height: 52),
        CGRect(x: 2444, y: 1313, width: 104, height: 52),
        CGRect(x: 2380, y: 1345, width: 104, height: 52),
        CGRect(x: 2316, y: 1377, width: 104, height: 52),
        CGRect(x: 2252, y: 1409, width: 104, height: 52),
        CGRect(x: 2188, y: 1441, width: 104, height: 52),
        CGRect(x: 2124, y: 1473, width: 104, height: 52),
        CGRect(x: 2060, y: 1505, width: 104, height: 52),
        CGRect(x: 1996, y: 1537, width: 104, height: 52),
        CGRect(x: 1932, y: 1569, width: 104, height: 52),
        CGRect(x: 1868, y: 1601, width: 104, height: 52),
        CGRect(x: 1804, y: 1633, width: 104, height: 52),
        CGRect(x: 1740, y: 1665, width: 104, height: 52),
        CGRect(x: 1676, y: 1697, width: 104, height: 52),
        CGRect(x: 1612, y: 1729, width: 104, height: 52),
        CGRect(x: 1548, y: 1761, width: 104, height: 52),
        CGRect(x: 1484, y: 1793, width: 104, height: 52),
        CGRect(x: 3468, y: 865, width: 104, height: 52),
        CGRect(x: 3404, y: 897, width: 104, height: 52),
        CGRect(x: 3340, y: 929, width: 104, height: 52),
        CGRect(x: 3276, y: 961, width: 104, height: 52),
        CGRect(x: 3212, y: 993, width: 104, height: 52),
        CGRect(x: 3148, y: 1025, width: 104, height: 52),
        CGRect(x: 3084, y: 1057, width: 104, height: 52),
        CGRect(x: 3020, y: 1089, width: 104, height: 52),
        CGRect(x: 2956, y: 1121, width: 104, height: 52),
        CGRect(x: 2892, y: 1153, width: 104, height: 52),
        CGRect(x: 2828, y: 1185, width: 104, height: 52),
        CGRect(x: 2764, y: 1217, width: 104, height: 52),
        CGRect(x: 2700, y: 1249, width: 104, height: 52),
        CGRect(x: 2636, y: 1281, width: 104, height: 52),
        CGRect(x: 2572, y: 1313, width: 104, height: 52),
        CGRect(x: 2508, y: 1345, width: 104, height: 52),
        CGRect(x: 2444, y: 1377, width: 104, height: 52),
        CGRect(x: 2380, y: 1409, width: 104, height: 52),
        CGRect(x: 2316, y: 1441, width: 104, height: 52),
        CGRect(x: 2252, y: 1473, width: 104, height: 52),
        CGRect(x: 2188, y: 1505, width: 104, height: 52),
        CGRect(x: 2124, y: 1537, width: 104, height: 52),
        CGRect(x: 2060, y: 1569, width: 104, height: 52),
        CGRect(x: 1996, y: 1601, width: 104, height: 52),
        CGRect(x: 1932, y: 1633, width: 104, height: 52),
        CGRect(x: 1868, y: 1665, width: 104, height: 52),
        CGRect(x: 1804, y: 1697, width: 104, height: 52),
        CGRect(x: 1740, y: 1729, width: 104, height: 52),
        CGRect(x: 1676, y: 1761, width: 104, height: 52),
        CGRect(x: 1612, y: 1793, width: 104, height: 52),
        CGRect(x: 1548, y: 1825, width: 104, height: 52),
        CGRect(x: 3532, y: 897, width: 104, height: 52),
        CGRect(x: 3468, y: 929, width: 104, height: 52),
        CGRect(x: 3404, y: 961, width: 104, height: 52),
        CGRect(x: 3340, y: 993, width: 104, height: 52),
        CGRect(x: 3276, y: 1025, width: 104, height: 52),
        CGRect(x: 3212, y: 1057, width: 104, height: 52),
        CGRect(x: 3148, y: 1089, width: 104, height: 52),
        CGRect(x: 3084, y: 1121, width: 104, height: 52),
        CGRect(x: 3020, y: 1153, width: 104, height: 52),
        CGRect(x: 2956, y: 1185, width: 104, height: 52),
        CGRect(x: 2892, y: 1217, width: 104, height: 52),
        CGRect(x: 2828, y: 1249, width: 104, height: 52),
        CGRect(x: 2764, y: 1281, width: 104, height: 52),
        CGRect(x: 2700, y: 1313, width: 104, height: 52),
        CGRect(x: 2636, y: 1345, width: 104, height: 52),
        CGRect(x: 2572, y: 1377, width: 104, height: 52),
        CGRect(x: 2508, y: 1409, width: 104, height: 52),
        CGRect(x: 2444, y: 1441, width: 104, height: 52),
        CGRect(x: 2380, y: 1473, width: 104, height: 52),
        CGRect(x: 2316, y: 1505, width: 104, height: 52),
        CGRect(x: 2252, y: 1537, width: 104, height: 52),
        CGRect(x: 2188, y: 1569, width: 104, height: 52),
        CGRect(x: 2124, y: 1601, width: 104, height: 52),
        CGRect(x: 2060, y: 1633, width: 104, height: 52),
        CGRect(x: 1996, y: 1665, width: 104, height: 52),
        CGRect(x: 1932, y: 1697, width: 104, height: 52),
        CGRect(x: 1868, y: 1729, width: 104, height: 52),
        CGRect(x: 1804, y: 1761, width: 104, height: 52),
        CGRect(x: 1740, y: 1793, width: 104, height: 52),
        CGRect(x: 1676, y: 1825, width: 104, height: 52),
        CGRect(x: 1612, y: 1857, width: 104, height: 52),
        CGRect(x: 3596, y: 929, width: 104, height: 52),
        CGRect(x: 3532, y: 961, width: 104, height: 52),
        CGRect(x: 3468, y: 993, width: 104, height: 52),
        CGRect(x: 3404, y: 1025, width: 104, height: 52),
        CGRect(x: 3340, y: 1057, width: 104, height: 52),
        CGRect(x: 3276, y: 1089, width: 104, height: 52),
        CGRect(x: 3212, y: 1121, width: 104, height: 52),
        CGRect(x: 3148, y: 1153, width: 104, height: 52),
        CGRect(x: 3084, y: 1185, width: 104, height: 52),
        CGRect(x: 3020, y: 1217, width: 104, height: 52),
        CGRect(x: 2956, y: 1249, width: 104, height: 52),
        CGRect(x: 2892, y: 1281, width: 104, height: 52),
        CGRect(x: 2828, y: 1313, width: 104, height: 52),
        CGRect(x: 2764, y: 1345, width: 104, height: 52),
        CGRect(x: 2700, y: 1377, width: 104, height: 52),
        CGRect(x: 2636, y: 1409, width: 104, height: 52),
        CGRect(x: 2572, y: 1441, width: 104, height: 52),
        CGRect(x: 2508, y: 1473, width: 104, height: 52),
        CGRect(x: 2444, y: 1505, width: 104, height: 52),
        CGRect(x: 2380, y: 1537, width: 104, height: 52),
        CGRect(x: 2316, y: 1569, width: 104, height: 52),
        CGRect(x: 2252, y: 1601, width: 104, height: 52),
        CGRect(x: 2188, y: 1633, width: 104, height: 52),
        CGRect(x: 2124, y: 1665, width: 104, height: 52),
        CGRect(x: 2060, y: 1697, width: 104, height: 52),
        CGRect(x: 1996, y: 1729, width: 104, height: 52),
        CGRect(x: 1932, y: 1761, width: 104, height: 52),
        CGRect(x: 1868, y: 1793, width: 104, height: 52),
        CGRect(x: 1804, y: 1825, width: 104, height: 52),
        CGRect(x: 1740, y: 1857, width: 104, height: 52),
        CGRect(x: 1676, y: 1889, width: 104, height: 52),
        CGRect(x: 3660, y: 961, width: 104, height: 52),
        CGRect(x: 3596, y: 993, width: 104, height: 52),
        CGRect(x: 3532, y: 1025, width: 104, height: 52),
        CGRect(x: 3468, y: 1057, width: 104, height: 52),
        CGRect(x: 3404, y: 1089, width: 104, height: 52),
        CGRect(x: 3340, y: 1121, width: 104, height: 52),
        CGRect(x: 3276, y: 1153, width: 104, height: 52),
        CGRect(x: 3212, y: 1185, width: 104, height: 52),
        CGRect(x: 3148, y: 1217, width: 104, height: 52),
        CGRect(x: 3084, y: 1249, width: 104, height: 52),
        CGRect(x: 3020, y: 1281, width: 104, height: 52),
        CGRect(x: 2956, y: 1313, width: 104, height: 52),
        CGRect(x: 2892, y: 1345, width: 104, height: 52),
        CGRect(x: 2828, y: 1377, width: 104, height: 52),
        CGRect(x: 2764, y: 1409, width: 104, height: 52),
        CGRect(x: 2700, y: 1441, width: 104, height: 52),
        CGRect(x: 2636, y: 1473, width: 104, height: 52),
        CGRect(x: 2572, y: 1505, width: 104, height: 52),
        CGRect(x: 2508, y: 1537, width: 104, height: 52),
        CGRect(x: 2444, y: 1569, width: 104, height: 52),
        CGRect(x: 2380, y: 1601, width: 104, height: 52),
        CGRect(x: 2316, y: 1633, width: 104, height: 52),
        CGRect(x: 2252, y: 1665, width: 104, height: 52),
        CGRect(x: 2188, y: 1697, width: 104, height: 52),
        CGRect(x: 2124, y: 1729, width: 104, height: 52),
        CGRect(x: 2060, y: 1761, width: 104, height: 52),
        CGRect(x: 1996, y: 1793, width: 104, height: 52),
        CGRect(x: 1932, y: 1825, width: 104, height: 52),
        CGRect(x: 1868, y: 1857, width: 104, height: 52),
        CGRect(x: 1804, y: 1889, width: 104, height: 52),
        CGRect(x: 1740, y: 1921, width: 104, height: 52),
        CGRect(x: 3724, y: 993, width: 104, height: 52),
        CGRect(x: 3660, y: 1025, width: 104, height: 52),
        CGRect(x: 3596, y: 1057, width: 104, height: 52),
        CGRect(x: 3532, y: 1089, width: 104, height: 52),
        CGRect(x: 3468, y: 1121, width: 104, height: 52),
        CGRect(x: 3404, y: 1153, width: 104, height: 52),
        CGRect(x: 3340, y: 1185, width: 104, height: 52),
        CGRect(x: 3276, y: 1217, width: 104, height: 52),
        CGRect(x: 3212, y: 1249, width: 104, height: 52),
        CGRect(x: 3148, y: 1281, width: 104, height: 52),
        CGRect(x: 3084, y: 1313, width: 104, height: 52),
        CGRect(x: 3020, y: 1345, width: 104, height: 52),
        CGRect(x: 2956, y: 1377, width: 104, height: 52),
        CGRect(x: 2892, y: 1409, width: 104, height: 52),
        CGRect(x: 2828, y: 1441, width: 104, height: 52),
        CGRect(x: 2764, y: 1473, width: 104, height: 52),
        CGRect(x: 2700, y: 1505, width: 104, height: 52),
        CGRect(x: 2636, y: 1537, width: 104, height: 52),
        CGRect(x: 2572, y: 1569, width: 104, height: 52),
        CGRect(x: 2508, y: 1601, width: 104, height: 52),
        CGRect(x: 2444, y: 1633, width: 104, height: 52),
        CGRect(x: 2380, y: 1665, width: 104, height: 52),
        CGRect(x: 2316, y: 1697, width: 104, height: 52),
        CGRect(x: 2252, y: 1729, width: 104, height: 52),
        CGRect(x: 2188, y: 1761, width: 104, height: 52),
        CGRect(x: 2124, y: 1793, width: 104, height: 52),
        CGRect(x: 2060, y: 1825, width: 104, height: 52),
        CGRect(x: 1996, y: 1857, width: 104, height: 52),
        CGRect(x: 1932, y: 1889, width: 104, height: 52),
        CGRect(x: 1868, y: 1921, width: 104, height: 52),
        CGRect(x: 1804, y: 1953, width: 104, height: 52),
        CGRect(x: 3788, y: 1025, width: 104, height: 52),
        CGRect(x: 3724, y: 1057, width: 104, height: 52),
        CGRect(x: 3660, y: 1089, width: 104, height: 52),
        CGRect(x: 3596, y: 1121, width: 104, height: 52),
        CGRect(x: 3532, y: 1153, width: 104, height: 52),
        CGRect(x: 3468, y: 1185, width: 104, height: 52),
        CGRect(x: 3404, y: 1217, width: 104, height: 52),
        CGRect(x: 3340, y: 1249, width: 104, height: 52),
        CGRect(x: 3276, y: 1281, width: 104, height: 52),
        CGRect(x: 3212, y: 1313, width: 104, height: 52),
        CGRect(x: 3148, y: 1345, width: 104, height: 52),
        CGRect(x: 3084, y: 1377, width: 104, height: 52),
        CGRect(x: 3020, y: 1409, width: 104, height: 52),
        CGRect(x: 2956, y: 1441, width: 104, height: 52),
        CGRect(x: 2892, y: 1473, width: 104, height: 52),
        CGRect(x: 2828, y: 1505, width: 104, height: 52),
        CGRect(x: 2764, y: 1537, width: 104, height: 52),
        CGRect(x: 2700, y: 1569, width: 104, height: 52),
        CGRect(x: 2636, y: 1601, width: 104, height: 52),
        CGRect(x: 2572, y: 1633, width: 104, height: 52),
        CGRect(x: 2508, y: 1665, width: 104, height: 52),
        CGRect(x: 2444, y: 1697, width: 104, height: 52),
        CGRect(x: 2380, y: 1729, width: 104, height: 52),
        CGRect(x: 2316, y: 1761, width: 104, height: 52),
        CGRect(x: 2252, y: 1793, width: 104, height: 52),
        CGRect(x: 2188, y: 1825, width: 104, height: 52),
        CGRect(x: 2124, y: 1857, width: 104, height: 52),
        CGRect(x: 2060, y: 1889, width: 104, height: 52),
        CGRect(x: 1996, y: 1921, width: 104, height: 52),
        CGRect(x: 1932, y: 1953, width: 104, height: 52),
        CGRect(x: 1868, y: 1985, width: 104, height: 52),
        CGRect(x: 3852, y: 1057, width: 104, height: 52),
        CGRect(x: 3788, y: 1089, width: 104, height: 52),
        CGRect(x: 3724, y: 1121, width: 104, height: 52),
        CGRect(x: 3660, y: 1153, width: 104, height: 52),
        CGRect(x: 3596, y: 1185, width: 104, height: 52),
        CGRect(x: 3532, y: 1217, width: 104, height: 52),
        CGRect(x: 3468, y: 1249, width: 104, height: 52),
        CGRect(x: 3404, y: 1281, width: 104, height: 52),
        CGRect(x: 3340, y: 1313, width: 104, height: 52),
        CGRect(x: 3276, y: 1345, width: 104, height: 52),
        CGRect(x: 3212, y: 1377, width: 104, height: 52),
        CGRect(x: 3148, y: 1409, width: 104, height: 52),
        CGRect(x: 3084, y: 1441, width: 104, height: 52),
        CGRect(x: 3020, y: 1473, width: 104, height: 52),
        CGRect(x: 2956, y: 1505, width: 104, height: 52),
        CGRect(x: 2892, y: 1537, width: 104, height: 52),
        CGRect(x: 2828, y: 1569, width: 104, height: 52),
        CGRect(x: 2764, y: 1601, width: 104, height: 52),
        CGRect(x: 2700, y: 1633, width: 104, height: 52),
        CGRect(x: 2636, y: 1665, width: 104, height: 52),
        CGRect(x: 2572, y: 1697, width: 104, height: 52),
        CGRect(x: 2508, y: 1729, width: 104, height: 52),
        CGRect(x: 2444, y: 1761, width: 104, height: 52),
        CGRect(x: 2380, y: 1793, width: 104, height: 52),
        CGRect(x: 2316, y: 1825, width: 104, height: 52),
        CGRect(x: 2252, y: 1857, width: 104, height: 52),
        CGRect(x: 2188, y: 1889, width: 104, height: 52),
        CGRect(x: 2124, y: 1921, width: 104, height: 52),
        CGRect(x: 2060, y: 1953, width: 104, height: 52),
        CGRect(x: 1996, y: 1985, width: 104, height: 52),
        CGRect(x: 1932, y: 2017, width: 104, height: 52),
        CGRect(x: 3916, y: 1089, width: 104, height: 52),
        CGRect(x: 3852, y: 1121, width: 104, height: 52),
        CGRect(x: 3788, y: 1153, width: 104, height: 52),
        CGRect(x: 3724, y: 1185, width: 104, height: 52),
        CGRect(x: 3660, y: 1217, width: 104, height: 52),
        CGRect(x: 3596, y: 1249, width: 104, height: 52),
        CGRect(x: 3532, y: 1281, width: 104, height: 52),
        CGRect(x: 3468, y: 1313, width: 104, height: 52),
        CGRect(x: 3404, y: 1345, width: 104, height: 52),
        CGRect(x: 3340, y: 1377, width: 104, height: 52),
        CGRect(x: 3276, y: 1409, width: 104, height: 52),
        CGRect(x: 3212, y: 1441, width: 104, height: 52),
        CGRect(x: 3148, y: 1473, width: 104, height: 52),
        CGRect(x: 3084, y: 1505, width: 104, height: 52),
        CGRect(x: 3020, y: 1537, width: 104, height: 52),
        CGRect(x: 2956, y: 1569, width: 104, height: 52),
        CGRect(x: 2892, y: 1601, width: 104, height: 52),
        CGRect(x: 2828, y: 1633, width: 104, height: 52),
        CGRect(x: 2764, y: 1665, width: 104, height: 52),
        CGRect(x: 2700, y: 1697, width: 104, height: 52),
        CGRect(x: 2636, y: 1729, width: 104, height: 52),
        CGRect(x: 2572, y: 1761, width: 104, height: 52),
        CGRect(x: 2508, y: 1793, width: 104, height: 52),
        CGRect(x: 2444, y: 1825, width: 104, height: 52),
        CGRect(x: 2380, y: 1857, width: 104, height: 52),
        CGRect(x: 2316, y: 1889, width: 104, height: 52),
        CGRect(x: 2252, y: 1921, width: 104, height: 52),
        CGRect(x: 2188, y: 1953, width: 104, height: 52),
        CGRect(x: 2124, y: 1985, width: 104, height: 52),
        CGRect(x: 2060, y: 2017, width: 104, height: 52),
        CGRect(x: 1996, y: 2049, width: 104, height: 52),
    ]

    /// Partition solids, one per navigation cell, doorway cells omitted.
    static let authoredPartitionWallNorthObstacle = CGRect(x: 2252, y: 1089, width: 104, height: 52)
    static let authoredPartitionWallSouthObstacle = CGRect(x: 1676, y: 1377, width: 104, height: 52)
    static let authoredPartitionSegments: [CGRect] = [
        CGRect(x: 2252, y: 1089, width: 104, height: 52),
        CGRect(x: 2188, y: 1121, width: 104, height: 52),
        CGRect(x: 2124, y: 1153, width: 104, height: 52),
        CGRect(x: 2060, y: 1185, width: 104, height: 52),
        CGRect(x: 1996, y: 1217, width: 104, height: 52),
        CGRect(x: 1932, y: 1249, width: 104, height: 52),
        CGRect(x: 1868, y: 1281, width: 104, height: 52),
        CGRect(x: 1676, y: 1377, width: 104, height: 52),
    ]

    static let authoredSafeObstacle = CGRect(x: 1595, y: 1323, width: 64, height: 32)
    static let authoredFilingCabinetBObstacle = CGRect(x: 1559, y: 1303, width: 58, height: 29)
    static let authoredFilingCabinetObstacle = CGRect(x: 1523, y: 1283, width: 58, height: 29)
    static let authoredBookshelfObstacle = CGRect(x: 1458, y: 1249, width: 98, height: 48)
    static let authoredArchiveBoxAObstacle = CGRect(x: 1543, y: 1250, width: 52, height: 26)
    static let authoredRadiatorObstacle = CGRect(x: 1760, y: 1423, width: 78, height: 38)
    static let authoredPersonalSideboardObstacle = CGRect(x: 1681, y: 1374, width: 103, height: 51)
    static let authoredPersonalFanObstacle = CGRect(x: 1743, y: 1379, width: 54, height: 27)
    static let authoredDeskEnsembleObstacle = CGRect(x: 1831, y: 1180, width: 153, height: 76)
    static let authoredVisitorArmchairObstacle = CGRect(x: 1885, y: 1266, width: 70, height: 35)
    static let authoredVisitorArmchairBObstacle = CGRect(x: 1999, y: 1212, width: 70, height: 35)
    static let authoredWastebasketObstacle = CGRect(x: 1774, y: 1220, width: 43, height: 22)
    static let authoredCoatRackObstacle = CGRect(x: 2592, y: 1183, width: 64, height: 32)
    static let authoredUmbrellaStandObstacle = CGRect(x: 2557, y: 1196, width: 38, height: 19)
    static let authoredWaitingChairAObstacle = CGRect(x: 2279, y: 1260, width: 59, height: 30)
    static let authoredWaitingTableObstacle = CGRect(x: 2328, y: 1237, width: 59, height: 30)
    static let authoredWaitingChairBObstacle = CGRect(x: 2377, y: 1213, width: 59, height: 30)

    private static var authoredObstacles: [CGRect] {
        [authoredDoorObstacle, authoredForegroundWallObstacle]
            + authoredBoundarySegments
            + authoredPartitionSegments
            + [
                authoredSafeObstacle,
                authoredFilingCabinetBObstacle,
                authoredFilingCabinetObstacle,
                authoredBookshelfObstacle,
                authoredArchiveBoxAObstacle,
                authoredRadiatorObstacle,
                authoredPersonalSideboardObstacle,
                authoredPersonalFanObstacle,
                authoredDeskEnsembleObstacle,
                authoredVisitorArmchairObstacle,
                authoredVisitorArmchairBObstacle,
                authoredWastebasketObstacle,
                authoredCoatRackObstacle,
                authoredUmbrellaStandObstacle,
                authoredWaitingChairAObstacle,
                authoredWaitingTableObstacle,
                authoredWaitingChairBObstacle,
            ]
    }

    // MARK: - Sample points (interior to each obstacle)

    static let authoredSafeSamplePoints: [CGPoint] = [
        CGPoint(x: 1_627, y: 1_340),
        CGPoint(x: 1_614, y: 1_335),
        CGPoint(x: 1_640, y: 1_345),
    ]
    static let authoredFilingCabinetBSamplePoints: [CGPoint] = [
        CGPoint(x: 1_588, y: 1_318),
        CGPoint(x: 1_576, y: 1_313),
        CGPoint(x: 1_599, y: 1_322),
    ]
    static let authoredFilingCabinetSamplePoints: [CGPoint] = [
        CGPoint(x: 1_552, y: 1_298),
        CGPoint(x: 1_540, y: 1_293),
        CGPoint(x: 1_563, y: 1_302),
    ]
    static let authoredBookshelfSamplePoints: [CGPoint] = [
        CGPoint(x: 1_507, y: 1_273),
        CGPoint(x: 1_488, y: 1_266),
        CGPoint(x: 1_527, y: 1_280),
    ]
    static let authoredArchiveBoxASamplePoints: [CGPoint] = [
        CGPoint(x: 1_569, y: 1_263),
        CGPoint(x: 1_559, y: 1_260),
        CGPoint(x: 1_579, y: 1_267),
    ]
    static let authoredRadiatorSamplePoints: [CGPoint] = [
        CGPoint(x: 1_800, y: 1_442),
        CGPoint(x: 1_784, y: 1_436),
        CGPoint(x: 1_815, y: 1_447),
    ]
    static let authoredPersonalSideboardSamplePoints: [CGPoint] = [
        CGPoint(x: 1_732, y: 1_399),
        CGPoint(x: 1_712, y: 1_391),
        CGPoint(x: 1_753, y: 1_407),
    ]
    static let authoredPersonalFanSamplePoints: [CGPoint] = [
        CGPoint(x: 1_769, y: 1_393),
        CGPoint(x: 1_759, y: 1_389),
        CGPoint(x: 1_780, y: 1_397),
    ]
    static let authoredDeskEnsembleSamplePoints: [CGPoint] = [
        CGPoint(x: 1_907, y: 1_218),
        CGPoint(x: 1_877, y: 1_206),
        CGPoint(x: 1_938, y: 1_229),
    ]
    static let authoredVisitorArmchairSamplePoints: [CGPoint] = [
        CGPoint(x: 1_920, y: 1_284),
        CGPoint(x: 1_906, y: 1_278),
        CGPoint(x: 1_934, y: 1_289),
    ]
    static let authoredVisitorArmchairBSamplePoints: [CGPoint] = [
        CGPoint(x: 2_034, y: 1_230),
        CGPoint(x: 2_020, y: 1_224),
        CGPoint(x: 2_048, y: 1_235),
    ]
    static let authoredWastebasketSamplePoints: [CGPoint] = [
        CGPoint(x: 1_795, y: 1_231),
        CGPoint(x: 1_787, y: 1_227),
        CGPoint(x: 1_804, y: 1_234),
    ]
    static let authoredCoatRackSamplePoints: [CGPoint] = [
        CGPoint(x: 2_625, y: 1_199),
        CGPoint(x: 2_612, y: 1_194),
        CGPoint(x: 2_637, y: 1_204),
    ]
    static let authoredUmbrellaStandSamplePoints: [CGPoint] = [
        CGPoint(x: 2_575, y: 1_205),
        CGPoint(x: 2_568, y: 1_203),
        CGPoint(x: 2_583, y: 1_208),
    ]
    static let authoredWaitingChairASamplePoints: [CGPoint] = [
        CGPoint(x: 2_309, y: 1_275),
        CGPoint(x: 2_297, y: 1_270),
        CGPoint(x: 2_321, y: 1_279),
    ]
    static let authoredWaitingTableSamplePoints: [CGPoint] = [
        CGPoint(x: 2_357, y: 1_251),
        CGPoint(x: 2_346, y: 1_247),
        CGPoint(x: 2_369, y: 1_256),
    ]
    static let authoredWaitingChairBSamplePoints: [CGPoint] = [
        CGPoint(x: 2_406, y: 1_228),
        CGPoint(x: 2_394, y: 1_224),
        CGPoint(x: 2_418, y: 1_233),
    ]
    static let authoredDoorLeafSamplePoints: [CGPoint] = [
        CGPoint(x: 2_598, y: 1_235),
        CGPoint(x: 2_560, y: 1_217),
        CGPoint(x: 2_636, y: 1_253),
    ]
    static let authoredForegroundWallSamplePoints: [CGPoint] = [
        CGPoint(x: 2_478, y: 1_033),
        CGPoint(x: 2_457, y: 1_025),
        CGPoint(x: 2_499, y: 1_041),
    ]
    static let authoredPartitionWallNorthSamplePoints: [CGPoint] = [
        CGPoint(x: 2_304, y: 1_115),
        CGPoint(x: 2_283, y: 1_107),
        CGPoint(x: 2_325, y: 1_122),
    ]
    static let authoredPartitionWallSouthSamplePoints: [CGPoint] = [
        CGPoint(x: 1_728, y: 1_403),
        CGPoint(x: 1_707, y: 1_395),
        CGPoint(x: 1_749, y: 1_410),
    ]

    // MARK: - Placements

    enum AuthoredPlacement {
        /// Registered to the visual threshold baked into the shipping suite.
        static let doorLeaf = Architecture.entranceLeafAnchor
        static let window = Architecture.windowAnchor
        static let windowBlinds = window
        static let windowRotation: CGFloat = 0
        static let windowRainMask = CGRect(x: 1_745.7, y: 1_664.2, width: 45.6, height: 81.6)
        static let windowRainEmitter = CGPoint(x: 1_768.5, y: 1_748.2)
        /// Recentred on the fitted cramped room diamond.
        static let camera = CGPoint(x: 1_984, y: 1_227)

        static let safe = CGPoint(x: 1_627, y: 1_340)  // records run, east end
        static let filingCabinetB = CGPoint(x: 1_588, y: 1_318)
        static let filingCabinet = CGPoint(x: 1_552, y: 1_298)  // drawer half open
        static let bookshelf = CGPoint(x: 1_507, y: 1_273)
        static let archiveBoxOnCabinet = CGPoint(x: 1_588, y: 1_318)  // on cabinet B
        static let archiveStackOnCabinet = CGPoint(x: 1_552, y: 1_298)  // on cabinet A
        static let archiveBoxA = CGPoint(x: 1_569, y: 1_263)  // only floor stack
        static let radiator = CGPoint(x: 1_800, y: 1_442)
        static let personalSideboard = CGPoint(x: 1_732, y: 1_399)
        static let personalWashbasin = CGPoint(x: 1_702, y: 1_382)  // retired domestic fixture; placement retained for source lineage
        static let personalFan = CGPoint(x: 1_769, y: 1_393)
        static let personalBottle = CGPoint(x: 1_731, y: 1_395)  // on sideboard
        static let personalGlass = CGPoint(x: 1_741, y: 1_401)  // on sideboard
        static let deskEnsemble = CGPoint(x: 1_907, y: 1_218)
        static let deskChair = CGPoint(x: 1_866, y: 1_194)
        static let visitorArmchair = CGPoint(x: 1_920, y: 1_284)
        static let visitorArmchairB = CGPoint(x: 2_034, y: 1_230)
        static let wastebasket = CGPoint(x: 1_795, y: 1_231)
        static let coatRack = CGPoint(x: 2_625, y: 1_199)
        static let umbrellaStand = CGPoint(x: 2_575, y: 1_205)
        static let waitingChairA = CGPoint(x: 2_309, y: 1_275)
        static let waitingTable = CGPoint(x: 2_357, y: 1_251)
        static let waitingChairB = CGPoint(x: 2_406, y: 1_228)
        static let newspaper = CGPoint(x: 2_356, y: 1_256)  // on table
        static let waitingAshtray = CGPoint(x: 2_360, y: 1_246)  // on table

        static let wornRug = CGPoint(x: 1_874, y: 1_199)
        static let floorWear = deskEnsemble
        static let wallPhotos = CGPoint(x: 1_371, y: 1_511)
        static let caseBoard = CGPoint(x: 1_460, y: 1_656)
        static let wallCityMap = CGPoint(x: 1_582, y: 1_685)
        static let framedLicence = CGPoint(x: 1_682, y: 1_661)
        static let windowSpill = CGPoint(x: 1_847, y: 1_419)
        static let blindStripes = CGPoint(x: 1_873, y: 1_384)
        static let hallwayLight = CGPoint(x: 2_587, y: 1_229)
        static let floorTrashA = CGPoint(x: 1_812, y: 1_240)
        static let floorTrashB = CGPoint(x: 1_599, y: 1_255)
        static let entranceRunner = CGPoint(x: 2_540, y: 1_219)
        static let lampPool = deskEnsemble
        /// Leaf swung 90° into the private office, hinged on the up-run jamb.
        static let internalDoorLeaf = Architecture.internalLeafAnchor
    }

    private static let authoredApproachPoints: [String: CGPoint] = [
        "office.window": CGPoint(x: 1_863, y: 1_412),
        "office.desk": CGPoint(x: 2_054, y: 1_182),
        "office.phone": CGPoint(x: 2_032, y: 1_170),
        "office.files": CGPoint(x: 1_643, y: 1_254),
        "office.door": CGPoint(x: 2_304, y: 1_306),
    ]

    private static let authoredProjectionOrigin = CGPoint(x: 2_048, y: 155)
    private static let authoredTileSize = CGSize(width: 128, height: 64)

    static var actorStart: CGPoint { OfficeInteriorScale.mapPoint(authoredActorStart) }

    static var emptyDeskChairWorldPosition: CGPoint {
        let baseline = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
        let nudge = OfficeInteriorScale.ActorDisplay.seatedDeskNudge
        return CGPoint(x: baseline.x + nudge.x, y: baseline.y + nudge.y)
    }

    enum DeskDepth {
        /// Visitor chairs sit on the far side of the writing surface.
        static let visitorChairBias: CGFloat = -50
        static let topOccluderBias: CGFloat = -40
        /// Above seated Voss's lower layer, below a client passing camera-near.
        static let seatedFrontApronBias: CGFloat = 15
        static let standingFrontApronBias: CGFloat = 40
    }

    /// Exterior threshold crossing. This segment intentionally starts
    /// outside the navigation floor and passes through the fallen door leaf.
    static let clientDoorwayPath: [CGPoint] = [
        CGPoint(x: 2_618, y: 1_271),
        CGPoint(x: 2_463, y: 1_184),
    ].map(OfficeInteriorScale.mapPoint)

    /// Walkable waiting-room anchors, ending immediately before the
    /// framed internal doorway in the production suite plate.
    static let clientWaitingRoomPath: [CGPoint] = [
        CGPoint(x: 2_463, y: 1_184),
        CGPoint(x: 2_218, y: 1_358),
        CGPoint(x: 1_994, y: 1_367),
        CGPoint(x: 1_874, y: 1_395),
    ].map(OfficeInteriorScale.mapPoint)

    /// Explicit crossing through the real framed partition aperture.
    static let clientInternalDoorwayPath: [CGPoint] = [
        CGPoint(x: 1_874, y: 1_395),
        CGPoint(x: 1_820, y: 1_365),
        CGPoint(x: 1_772, y: 1_338),
    ].map(OfficeInteriorScale.mapPoint)

    /// Direct private-office approach after clearing the internal door.
    static let clientOfficeArrivalPath: [CGPoint] = [
        CGPoint(x: 1_772, y: 1_338),
        CGPoint(x: 1_877, y: 1_336),
    ].map(OfficeInteriorScale.mapPoint)

    static let clientInteriorArrivalPath: [CGPoint] = [
        clientWaitingRoomPath,
        Array(clientInternalDoorwayPath.dropFirst()),
        Array(clientOfficeArrivalPath.dropFirst()),
    ].flatMap { $0 }

    static var clientArrivalPath: [CGPoint] {
        Array(clientDoorwayPath.dropLast()) + clientInteriorArrivalPath
    }

    static var clientDeparturePath: [CGPoint] { Array(clientArrivalPath.reversed()) }

    /// Expand the complete interior anchor chain as one collision-checked
    /// polyline. The real partition doorway anchors prevent smoothing
    /// across either jamb while keeping the route direct.
    static func clientArrivalRoute(in navigation: NavigationGrid) -> [CGPoint] {
        guard let interior = navigation.waypoints(visiting: clientInteriorArrivalPath) else {
            // Stop safely inside the exterior door if a future layout
            // disconnects the rooms; never fall back to wall-cutting moves.
            return clientDoorwayPath
        }
        return Array(clientDoorwayPath.dropLast())
            + interior
    }

    static func clientDepartureRoute(in navigation: NavigationGrid) -> [CGPoint] {
        Array(clientArrivalRoute(in: navigation).reversed())
    }

    static let exteriorToInternalDoorPath: [CGPoint] = [
        Array(clientDoorwayPath.dropLast()),
        clientWaitingRoomPath,
        Array(clientInternalDoorwayPath.dropFirst()),
    ].flatMap { $0 }

    static let internalDoorToClientPath: [CGPoint] = [
        clientInternalDoorwayPath,
        Array(clientOfficeArrivalPath.dropFirst()),
    ].flatMap { $0 }

    static let recordsApproachPath: [CGPoint] = [
        CGPoint(x: 1_809, y: 1_230),
        CGPoint(x: 1_695, y: 1_250),
        CGPoint(x: 1_643, y: 1_254),
    ].map(OfficeInteriorScale.mapPoint)

    static var obstacles: [CGRect] { authoredObstacles.map(OfficeInteriorScale.mapRect) }

    static var safeObstacle: CGRect { OfficeInteriorScale.mapRect(authoredSafeObstacle) }
    static var filingCabinetBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetBObstacle) }
    static var filingCabinetObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetObstacle) }
    static var bookshelfObstacle: CGRect { OfficeInteriorScale.mapRect(authoredBookshelfObstacle) }
    static var archiveBoxAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredArchiveBoxAObstacle) }
    static var radiatorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredRadiatorObstacle) }
    static var personalSideboardObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalSideboardObstacle) }
    static var personalFanObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalFanObstacle) }
    static var deskEnsembleObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDeskEnsembleObstacle) }
    static var visitorArmchairObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairObstacle) }
    static var visitorArmchairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairBObstacle) }
    static var wastebasketObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWastebasketObstacle) }
    static var coatRackObstacle: CGRect { OfficeInteriorScale.mapRect(authoredCoatRackObstacle) }
    static var umbrellaStandObstacle: CGRect { OfficeInteriorScale.mapRect(authoredUmbrellaStandObstacle) }
    static var waitingChairAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairAObstacle) }
    static var waitingTableObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingTableObstacle) }
    static var waitingChairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairBObstacle) }
    static var doorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDoorObstacle) }
    static var foregroundWallObstacle: CGRect { OfficeInteriorScale.mapRect(authoredForegroundWallObstacle) }
    static var partitionWallNorthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallNorthObstacle) }
    static var partitionWallSouthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallSouthObstacle) }

    static var safeSamplePoints: [CGPoint] { authoredSafeSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetBSamplePoints: [CGPoint] { authoredFilingCabinetBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetSamplePoints: [CGPoint] { authoredFilingCabinetSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var bookshelfSamplePoints: [CGPoint] { authoredBookshelfSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var archiveBoxASamplePoints: [CGPoint] { authoredArchiveBoxASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var radiatorSamplePoints: [CGPoint] { authoredRadiatorSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalSideboardSamplePoints: [CGPoint] { authoredPersonalSideboardSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalFanSamplePoints: [CGPoint] { authoredPersonalFanSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var deskEnsembleSamplePoints: [CGPoint] { authoredDeskEnsembleSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairSamplePoints: [CGPoint] { authoredVisitorArmchairSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairBSamplePoints: [CGPoint] { authoredVisitorArmchairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var wastebasketSamplePoints: [CGPoint] { authoredWastebasketSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var coatRackSamplePoints: [CGPoint] { authoredCoatRackSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var umbrellaStandSamplePoints: [CGPoint] { authoredUmbrellaStandSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairASamplePoints: [CGPoint] { authoredWaitingChairASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingTableSamplePoints: [CGPoint] { authoredWaitingTableSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairBSamplePoints: [CGPoint] { authoredWaitingChairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var doorLeafSamplePoints: [CGPoint] { authoredDoorLeafSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var foregroundWallSamplePoints: [CGPoint] { authoredForegroundWallSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallNorthSamplePoints: [CGPoint] { authoredPartitionWallNorthSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallSouthSamplePoints: [CGPoint] { authoredPartitionWallSouthSamplePoints.map(OfficeInteriorScale.mapPoint) }

    static var majorPropSamplePoints: [CGPoint] {
        safeSamplePoints
            + filingCabinetBSamplePoints
            + filingCabinetSamplePoints
            + bookshelfSamplePoints
            + archiveBoxASamplePoints
            + radiatorSamplePoints
            + personalSideboardSamplePoints
            + personalFanSamplePoints
            + deskEnsembleSamplePoints
            + visitorArmchairSamplePoints
            + visitorArmchairBSamplePoints
            + wastebasketSamplePoints
            + coatRackSamplePoints
            + umbrellaStandSamplePoints
            + waitingChairASamplePoints
            + waitingTableSamplePoints
            + waitingChairBSamplePoints
            + doorLeafSamplePoints
            + foregroundWallSamplePoints
            + partitionWallNorthSamplePoints
            + partitionWallSouthSamplePoints
    }

    static var approachPoints: [String: CGPoint] {
        authoredApproachPoints.mapValues(OfficeInteriorScale.mapPoint)
    }

    /// Actual Voss stand-ins for architecture scale review: exterior door,
    /// desk, internal doorway, and waiting chair.
    static let authoredScaleReferenceStands: [CGPoint] = [
        CGPoint(x: 2_554, y: 1_210),
        CGPoint(x: 1_863, y: 1_193),
        CGPoint(x: 1_829, y: 1_370),
        CGPoint(x: 2_325, y: 1_267),
    ]

    static var scaleReferenceStands: [CGPoint] {
        authoredScaleReferenceStands.map(OfficeInteriorScale.mapPoint)
    }

    static var deskSamplePoints: [CGPoint] { deskEnsembleSamplePoints }
    static var deskObstacle: CGRect { deskEnsembleObstacle }
    static var authoredDeskObstacle: CGRect { authoredDeskEnsembleObstacle }

    static let authoredHotspots: [(id: String, name: String, hitArea: CGRect, observation: String)] = [
        (
            "office.window",
            "Rain-streaked window",
            CGRect(x: 1_174, y: 1_758, width: 92, height: 160),
            "The rain had been working the glass harder than I had worked a case."
        ),
        (
            "office.desk",
            "Desk",
            deskHitArea,
            "Three old cases, two unpaid bills, one clean page."
        ),
        (
            "office.phone",
            "Telephone",
            phoneHitArea,
            "Quiet. For once it had the decency to look guilty."
        ),
        (
            "office.files",
            "Case files",
            filesHitArea,
            "Closed, abandoned, and one I still lied about."
        ),
        (
            "office.door",
            "Office door",
            CGRect(x: 3_000, y: 1_400, width: 240, height: 480),
            "The hall smelled worse, but at least it led somewhere."
        )
    ]

    private static var deskHitArea: CGRect {
        authoredDeskEnsembleObstacle.insetBy(dx: -90, dy: -70)
    }

    private static var phoneHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.deskEnsemble.x - 40,
            y: AuthoredPlacement.deskEnsemble.y + 40,
            width: 200,
            height: 150
        )
    }

    private static var filesHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.filingCabinet.x - 110,
            y: AuthoredPlacement.filingCabinet.y - 20,
            width: 300,
            height: 220
        )
    }


    enum DialogueCameraFraming {
        static let legacyDownwardOffset: CGFloat = 55
        static let priorDownwardOffset: CGFloat = 28
        static let cameraBelowActorMidpoint: CGFloat = 110
        static let lateralBiasTowardClient: CGFloat = 24

        static var actorFocusPoint: CGPoint {
            let voss = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
            let lila = clientArrivalPath.last
                ?? OfficeInteriorScale.mapPoint(AuthoredPlacement.visitorArmchair)
            return CGPoint(
                x: (voss.x + lila.x) * 0.5 + lateralBiasTowardClient,
                y: (voss.y + lila.y) * 0.5
            )
        }

        static var dialogueCameraWorldPosition: CGPoint {
            let focus = actorFocusPoint
            return CGPoint(x: focus.x, y: focus.y - cameraBelowActorMidpoint)
        }

        static func dialogueCameraPosition(playCamera: CGPoint) -> CGPoint {
            _ = playCamera
            return dialogueCameraWorldPosition
        }

        static var downwardOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return play.y - dialogueCameraWorldPosition.y
        }

        static var lateralOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return dialogueCameraWorldPosition.x - play.x
        }
    }

    static func makeGrid() -> NavigationGrid {
        NavigationGrid(
            projection: .dimetric(
                origin: OfficeInteriorScale.mapPoint(authoredProjectionOrigin),
                tileSize: OfficeInteriorScale.mapSize(authoredTileSize)
            ),
            columns: 31,
            rows: 31,
            obstacles: obstacles,
            agentProfile: .officeDetective
        )
    }

    static func isBlocked(_ point: CGPoint) -> Bool {
        obstacles.contains { $0.contains(point) }
    }
}
