import CoreGraphics

/// Generated by `ArtSource/Processing/office_layout_plan.py` — edit the
/// layout there and re-run, so art, navigation and previews stay in step.
///
/// Placements are authored in the shell's floor-plan basis: every prop sits on
/// a measured room axis, so furniture lines up with the painted walls.
enum OfficeNavigationLayout {
    enum Architecture {
        /// Shell-authoritative centre of the painted exterior threshold.
        static let entranceAnchor = CGPoint(x: 2_719.343, y: 1_151.621)
        /// Window insert centre on the painted left-wall recess.
        static let windowAnchor = CGPoint(x: 1_707.000, y: 1_725.400)
        /// Interior partition: one wall on the room's north-east axis (a = 0.39),
        /// with a single framed doorway as the only connection between rooms.
        static let partitionLineA: CGFloat = 0.39
        static let partitionThicknessA: CGFloat = 0.05334857421115952
        static let partitionDoorB0: CGFloat = 0.752
        static let partitionDoorB1: CGFloat = 0.8
        static let partitionReturnB1: CGFloat = 0.8300000000000001
        static let wallThicknessPx: CGFloat = 14.7
        static let axisNW = CGVector(dx: -678.3, dy: 380.8)
        static let axisNE = CGVector(dx: 991.8, dy: 471.6)
        static let rearCorner = CGPoint(x: 1906.1, y: 1538.3)

        /// Partition plate geometry in shell art pixels (y down), so the scene can
        /// slice the painted wall into depth-sorted columns that sort like props
        /// standing on the wall's own ground line.
        static let partitionPlateX0: CGFloat = 1593
        static let partitionPlateX1: CGFloat = 2597
        static let partitionPlateFaceHeight: CGFloat = 377
        static let partitionPlateCapHeight: CGFloat = 6

        /// Ground line of the partition face at a shell-art x (y down).
        static func partitionPlateBaseY(atPlateX x: CGFloat) -> CGFloat {
            928.9 + (x - 1593) * 0.4755
        }

        /// Clear exterior opening measured from the shipping suite plate.
        static let entranceOpeningPlateSize = CGSize(width: 113.600, height: 206.0)
        /// 206 plate px × environment = 81.37 world units against a 70.31-unit adult. Matches the ~1.16× real door-to-adult ratio.
        static let entranceOpeningToDetectiveRatio: CGFloat = 1.157
        static let entranceHandleHeightToDetective: CGFloat = 0.521

        /// Exterior leaf/frame projected onto the sloped NE wall opening.
        /// Uniform height-fit (keeps sheared master aspect; no X-squash).
        static let entranceLeafDisplayScale: CGFloat = 0.1275
        static let entranceLeafDisplayScaleX: CGFloat = entranceLeafDisplayScale
        static let entranceLeafDisplayScaleY: CGFloat = entranceLeafDisplayScale
        static let entranceLeafAnchorY: CGFloat = 0.08903
        static let entranceLeafAnchor = CGPoint(x: 2_722.500, y: 1_284.800)
        static let entranceFrameDisplayScale: CGFloat = 0.1273
        static let entranceFrameDisplayScaleX: CGFloat = entranceFrameDisplayScale
        static let entranceFrameDisplayScaleY: CGFloat = entranceFrameDisplayScale
        static let entranceFrameAnchorX: CGFloat = 0.49155
        static let entranceFrameAnchorY: CGFloat = 0.11529
        /// Floor-projected presentation used after the leaf breaks free.
        static let entranceFallenLeafScaleRatio: CGFloat = 0.92
        /// The upright art grows slightly as its top swings toward the camera.
        /// This is only the transition silhouette; the landed art has an
        /// explicit world-space size below.
        static let entranceFallingTransitionScale: CGFloat =
            0.17 * OfficeInteriorScale.ActorDisplay.visualBodyRatio
        /// Purpose-built 768×512 landed-state art. The transparent source
        /// canvas stays centered so this scale yields a door body proportional
        /// to the upright leaf it fell from.
        static let entranceFallenArtworkCanvasSize = CGSize(width: 768, height: 512)
        static let entranceFallenArtworkDisplayScale: CGFloat =
            0.17 * OfficeInteriorScale.ActorDisplay.visualBodyRatio
        static let entranceFallenArtworkDisplaySize = CGSize(
            width: entranceFallenArtworkCanvasSize.width
                * entranceFallenArtworkDisplayScale,
            height: entranceFallenArtworkCanvasSize.height
                * entranceFallenArtworkDisplayScale
        )
        /// Internal open leaf registered to the shipping partition hinge.
        static let internalHingePlateX: CGFloat = 2351.2
        static let internalHingePlateHeight: CGFloat = 206.0
        /// Height-fit to `internalHingePlateHeight` × environment / hinge texture.
        static let internalLeafDisplayScale: CGFloat = 0.2352
        static let internalLeafAnchor = CGPoint(x: 2298.509, y: 994.078)
    }

    /// Walkable chair-side stand point (camera-near of the kneehole).
    /// Kept outside the desk obstacle so leave-seat never starts on the
    /// visitor/rear side of the writing surface.
    private static let authoredActorStart = CGPoint(
        x: AuthoredPlacement.deskChair.x,
        y: AuthoredPlacement.deskChair.y - 30
    )

    // MARK: - Obstacles (authored AABBs around each floor footprint)

    /// One cell of the camera-near boundary, kept named for the layout tests.
    static let authoredForegroundWallObstacle = CGRect(x: 2521, y: 879, width: 104, height: 52)
    static let authoredDoorObstacle = CGRect(x: 2604, y: 1080, width: 231, height: 144)

    /// Room boundary: the rear and side walls plus the camera-near cutaway
    /// wall, one solid per navigation cell outside the painted floor.
    static let authoredBoundarySegments: [CGRect] = [
        CGRect(x: 1996, y: 115, width: 104, height: 52),
        CGRect(x: 1932, y: 147, width: 104, height: 52),
        CGRect(x: 1868, y: 179, width: 104, height: 52),
        CGRect(x: 1804, y: 211, width: 104, height: 52),
        CGRect(x: 1740, y: 243, width: 104, height: 52),
        CGRect(x: 1676, y: 275, width: 104, height: 52),
        CGRect(x: 1612, y: 307, width: 104, height: 52),
        CGRect(x: 1548, y: 339, width: 104, height: 52),
        CGRect(x: 1484, y: 371, width: 104, height: 52),
        CGRect(x: 1420, y: 403, width: 104, height: 52),
        CGRect(x: 1356, y: 435, width: 104, height: 52),
        CGRect(x: 1292, y: 467, width: 104, height: 52),
        CGRect(x: 1228, y: 499, width: 104, height: 52),
        CGRect(x: 1164, y: 531, width: 104, height: 52),
        CGRect(x: 1100, y: 563, width: 104, height: 52),
        CGRect(x: 1036, y: 595, width: 104, height: 52),
        CGRect(x: 972, y: 627, width: 104, height: 52),
        CGRect(x: 908, y: 659, width: 104, height: 52),
        CGRect(x: 844, y: 691, width: 104, height: 52),
        CGRect(x: 780, y: 723, width: 104, height: 52),
        CGRect(x: 716, y: 755, width: 104, height: 52),
        CGRect(x: 652, y: 787, width: 104, height: 52),
        CGRect(x: 588, y: 819, width: 104, height: 52),
        CGRect(x: 524, y: 851, width: 104, height: 52),
        CGRect(x: 460, y: 883, width: 104, height: 52),
        CGRect(x: 396, y: 915, width: 104, height: 52),
        CGRect(x: 332, y: 947, width: 104, height: 52),
        CGRect(x: 268, y: 979, width: 104, height: 52),
        CGRect(x: 204, y: 1011, width: 104, height: 52),
        CGRect(x: 140, y: 1043, width: 104, height: 52),
        CGRect(x: 76, y: 1075, width: 104, height: 52),
        CGRect(x: 2060, y: 147, width: 104, height: 52),
        CGRect(x: 1996, y: 179, width: 104, height: 52),
        CGRect(x: 1932, y: 211, width: 104, height: 52),
        CGRect(x: 1868, y: 243, width: 104, height: 52),
        CGRect(x: 1804, y: 275, width: 104, height: 52),
        CGRect(x: 1740, y: 307, width: 104, height: 52),
        CGRect(x: 1676, y: 339, width: 104, height: 52),
        CGRect(x: 1612, y: 371, width: 104, height: 52),
        CGRect(x: 1548, y: 403, width: 104, height: 52),
        CGRect(x: 1484, y: 435, width: 104, height: 52),
        CGRect(x: 1420, y: 467, width: 104, height: 52),
        CGRect(x: 1356, y: 499, width: 104, height: 52),
        CGRect(x: 1292, y: 531, width: 104, height: 52),
        CGRect(x: 1228, y: 563, width: 104, height: 52),
        CGRect(x: 1164, y: 595, width: 104, height: 52),
        CGRect(x: 1100, y: 627, width: 104, height: 52),
        CGRect(x: 1036, y: 659, width: 104, height: 52),
        CGRect(x: 972, y: 691, width: 104, height: 52),
        CGRect(x: 908, y: 723, width: 104, height: 52),
        CGRect(x: 844, y: 755, width: 104, height: 52),
        CGRect(x: 780, y: 787, width: 104, height: 52),
        CGRect(x: 716, y: 819, width: 104, height: 52),
        CGRect(x: 652, y: 851, width: 104, height: 52),
        CGRect(x: 588, y: 883, width: 104, height: 52),
        CGRect(x: 524, y: 915, width: 104, height: 52),
        CGRect(x: 460, y: 947, width: 104, height: 52),
        CGRect(x: 396, y: 979, width: 104, height: 52),
        CGRect(x: 332, y: 1011, width: 104, height: 52),
        CGRect(x: 268, y: 1043, width: 104, height: 52),
        CGRect(x: 204, y: 1075, width: 104, height: 52),
        CGRect(x: 140, y: 1107, width: 104, height: 52),
        CGRect(x: 2124, y: 179, width: 104, height: 52),
        CGRect(x: 2060, y: 211, width: 104, height: 52),
        CGRect(x: 1996, y: 243, width: 104, height: 52),
        CGRect(x: 1932, y: 275, width: 104, height: 52),
        CGRect(x: 1868, y: 307, width: 104, height: 52),
        CGRect(x: 1804, y: 339, width: 104, height: 52),
        CGRect(x: 1740, y: 371, width: 104, height: 52),
        CGRect(x: 1676, y: 403, width: 104, height: 52),
        CGRect(x: 1612, y: 435, width: 104, height: 52),
        CGRect(x: 1548, y: 467, width: 104, height: 52),
        CGRect(x: 1484, y: 499, width: 104, height: 52),
        CGRect(x: 1420, y: 531, width: 104, height: 52),
        CGRect(x: 1356, y: 563, width: 104, height: 52),
        CGRect(x: 1292, y: 595, width: 104, height: 52),
        CGRect(x: 1228, y: 627, width: 104, height: 52),
        CGRect(x: 1164, y: 659, width: 104, height: 52),
        CGRect(x: 1100, y: 691, width: 104, height: 52),
        CGRect(x: 1036, y: 723, width: 104, height: 52),
        CGRect(x: 972, y: 755, width: 104, height: 52),
        CGRect(x: 908, y: 787, width: 104, height: 52),
        CGRect(x: 844, y: 819, width: 104, height: 52),
        CGRect(x: 780, y: 851, width: 104, height: 52),
        CGRect(x: 716, y: 883, width: 104, height: 52),
        CGRect(x: 652, y: 915, width: 104, height: 52),
        CGRect(x: 588, y: 947, width: 104, height: 52),
        CGRect(x: 524, y: 979, width: 104, height: 52),
        CGRect(x: 460, y: 1011, width: 104, height: 52),
        CGRect(x: 396, y: 1043, width: 104, height: 52),
        CGRect(x: 332, y: 1075, width: 104, height: 52),
        CGRect(x: 268, y: 1107, width: 104, height: 52),
        CGRect(x: 204, y: 1139, width: 104, height: 52),
        CGRect(x: 2188, y: 211, width: 104, height: 52),
        CGRect(x: 2124, y: 243, width: 104, height: 52),
        CGRect(x: 2060, y: 275, width: 104, height: 52),
        CGRect(x: 1996, y: 307, width: 104, height: 52),
        CGRect(x: 1932, y: 339, width: 104, height: 52),
        CGRect(x: 1868, y: 371, width: 104, height: 52),
        CGRect(x: 1804, y: 403, width: 104, height: 52),
        CGRect(x: 1740, y: 435, width: 104, height: 52),
        CGRect(x: 1676, y: 467, width: 104, height: 52),
        CGRect(x: 1612, y: 499, width: 104, height: 52),
        CGRect(x: 1548, y: 531, width: 104, height: 52),
        CGRect(x: 1484, y: 563, width: 104, height: 52),
        CGRect(x: 1420, y: 595, width: 104, height: 52),
        CGRect(x: 1356, y: 627, width: 104, height: 52),
        CGRect(x: 1292, y: 659, width: 104, height: 52),
        CGRect(x: 1228, y: 691, width: 104, height: 52),
        CGRect(x: 1164, y: 723, width: 104, height: 52),
        CGRect(x: 1100, y: 755, width: 104, height: 52),
        CGRect(x: 1036, y: 787, width: 104, height: 52),
        CGRect(x: 972, y: 819, width: 104, height: 52),
        CGRect(x: 908, y: 851, width: 104, height: 52),
        CGRect(x: 844, y: 883, width: 104, height: 52),
        CGRect(x: 780, y: 915, width: 104, height: 52),
        CGRect(x: 716, y: 947, width: 104, height: 52),
        CGRect(x: 652, y: 979, width: 104, height: 52),
        CGRect(x: 588, y: 1011, width: 104, height: 52),
        CGRect(x: 524, y: 1043, width: 104, height: 52),
        CGRect(x: 460, y: 1075, width: 104, height: 52),
        CGRect(x: 396, y: 1107, width: 104, height: 52),
        CGRect(x: 332, y: 1139, width: 104, height: 52),
        CGRect(x: 268, y: 1171, width: 104, height: 52),
        CGRect(x: 2252, y: 243, width: 104, height: 52),
        CGRect(x: 2188, y: 275, width: 104, height: 52),
        CGRect(x: 2124, y: 307, width: 104, height: 52),
        CGRect(x: 2060, y: 339, width: 104, height: 52),
        CGRect(x: 1996, y: 371, width: 104, height: 52),
        CGRect(x: 1932, y: 403, width: 104, height: 52),
        CGRect(x: 1868, y: 435, width: 104, height: 52),
        CGRect(x: 1804, y: 467, width: 104, height: 52),
        CGRect(x: 1740, y: 499, width: 104, height: 52),
        CGRect(x: 1676, y: 531, width: 104, height: 52),
        CGRect(x: 1612, y: 563, width: 104, height: 52),
        CGRect(x: 1548, y: 595, width: 104, height: 52),
        CGRect(x: 1484, y: 627, width: 104, height: 52),
        CGRect(x: 1420, y: 659, width: 104, height: 52),
        CGRect(x: 1356, y: 691, width: 104, height: 52),
        CGRect(x: 1292, y: 723, width: 104, height: 52),
        CGRect(x: 1228, y: 755, width: 104, height: 52),
        CGRect(x: 1164, y: 787, width: 104, height: 52),
        CGRect(x: 1100, y: 819, width: 104, height: 52),
        CGRect(x: 1036, y: 851, width: 104, height: 52),
        CGRect(x: 972, y: 883, width: 104, height: 52),
        CGRect(x: 908, y: 915, width: 104, height: 52),
        CGRect(x: 844, y: 947, width: 104, height: 52),
        CGRect(x: 780, y: 979, width: 104, height: 52),
        CGRect(x: 716, y: 1011, width: 104, height: 52),
        CGRect(x: 652, y: 1043, width: 104, height: 52),
        CGRect(x: 588, y: 1075, width: 104, height: 52),
        CGRect(x: 524, y: 1107, width: 104, height: 52),
        CGRect(x: 460, y: 1139, width: 104, height: 52),
        CGRect(x: 396, y: 1171, width: 104, height: 52),
        CGRect(x: 332, y: 1203, width: 104, height: 52),
        CGRect(x: 2316, y: 275, width: 104, height: 52),
        CGRect(x: 2252, y: 307, width: 104, height: 52),
        CGRect(x: 2188, y: 339, width: 104, height: 52),
        CGRect(x: 2124, y: 371, width: 104, height: 52),
        CGRect(x: 2060, y: 403, width: 104, height: 52),
        CGRect(x: 1996, y: 435, width: 104, height: 52),
        CGRect(x: 1932, y: 467, width: 104, height: 52),
        CGRect(x: 1868, y: 499, width: 104, height: 52),
        CGRect(x: 1804, y: 531, width: 104, height: 52),
        CGRect(x: 1740, y: 563, width: 104, height: 52),
        CGRect(x: 1676, y: 595, width: 104, height: 52),
        CGRect(x: 1612, y: 627, width: 104, height: 52),
        CGRect(x: 1548, y: 659, width: 104, height: 52),
        CGRect(x: 1484, y: 691, width: 104, height: 52),
        CGRect(x: 1420, y: 723, width: 104, height: 52),
        CGRect(x: 1356, y: 755, width: 104, height: 52),
        CGRect(x: 1292, y: 787, width: 104, height: 52),
        CGRect(x: 1228, y: 819, width: 104, height: 52),
        CGRect(x: 1164, y: 851, width: 104, height: 52),
        CGRect(x: 1100, y: 883, width: 104, height: 52),
        CGRect(x: 1036, y: 915, width: 104, height: 52),
        CGRect(x: 972, y: 947, width: 104, height: 52),
        CGRect(x: 908, y: 979, width: 104, height: 52),
        CGRect(x: 844, y: 1011, width: 104, height: 52),
        CGRect(x: 780, y: 1043, width: 104, height: 52),
        CGRect(x: 716, y: 1075, width: 104, height: 52),
        CGRect(x: 652, y: 1107, width: 104, height: 52),
        CGRect(x: 588, y: 1139, width: 104, height: 52),
        CGRect(x: 524, y: 1171, width: 104, height: 52),
        CGRect(x: 460, y: 1203, width: 104, height: 52),
        CGRect(x: 396, y: 1235, width: 104, height: 52),
        CGRect(x: 2380, y: 307, width: 104, height: 52),
        CGRect(x: 2316, y: 339, width: 104, height: 52),
        CGRect(x: 2252, y: 371, width: 104, height: 52),
        CGRect(x: 2188, y: 403, width: 104, height: 52),
        CGRect(x: 2124, y: 435, width: 104, height: 52),
        CGRect(x: 2060, y: 467, width: 104, height: 52),
        CGRect(x: 1996, y: 499, width: 104, height: 52),
        CGRect(x: 1932, y: 531, width: 104, height: 52),
        CGRect(x: 1868, y: 563, width: 104, height: 52),
        CGRect(x: 1804, y: 595, width: 104, height: 52),
        CGRect(x: 1740, y: 627, width: 104, height: 52),
        CGRect(x: 1676, y: 659, width: 104, height: 52),
        CGRect(x: 1612, y: 691, width: 104, height: 52),
        CGRect(x: 1548, y: 723, width: 104, height: 52),
        CGRect(x: 1484, y: 755, width: 104, height: 52),
        CGRect(x: 1420, y: 787, width: 104, height: 52),
        CGRect(x: 1356, y: 819, width: 104, height: 52),
        CGRect(x: 1292, y: 851, width: 104, height: 52),
        CGRect(x: 1228, y: 883, width: 104, height: 52),
        CGRect(x: 1164, y: 915, width: 104, height: 52),
        CGRect(x: 1100, y: 947, width: 104, height: 52),
        CGRect(x: 1036, y: 979, width: 104, height: 52),
        CGRect(x: 972, y: 1011, width: 104, height: 52),
        CGRect(x: 908, y: 1043, width: 104, height: 52),
        CGRect(x: 844, y: 1075, width: 104, height: 52),
        CGRect(x: 780, y: 1107, width: 104, height: 52),
        CGRect(x: 716, y: 1139, width: 104, height: 52),
        CGRect(x: 652, y: 1171, width: 104, height: 52),
        CGRect(x: 588, y: 1203, width: 104, height: 52),
        CGRect(x: 524, y: 1235, width: 104, height: 52),
        CGRect(x: 460, y: 1267, width: 104, height: 52),
        CGRect(x: 2444, y: 339, width: 104, height: 52),
        CGRect(x: 2380, y: 371, width: 104, height: 52),
        CGRect(x: 2316, y: 403, width: 104, height: 52),
        CGRect(x: 2252, y: 435, width: 104, height: 52),
        CGRect(x: 2188, y: 467, width: 104, height: 52),
        CGRect(x: 2124, y: 499, width: 104, height: 52),
        CGRect(x: 2060, y: 531, width: 104, height: 52),
        CGRect(x: 1996, y: 563, width: 104, height: 52),
        CGRect(x: 1932, y: 595, width: 104, height: 52),
        CGRect(x: 1868, y: 627, width: 104, height: 52),
        CGRect(x: 1804, y: 659, width: 104, height: 52),
        CGRect(x: 1740, y: 691, width: 104, height: 52),
        CGRect(x: 1676, y: 723, width: 104, height: 52),
        CGRect(x: 1612, y: 755, width: 104, height: 52),
        CGRect(x: 1548, y: 787, width: 104, height: 52),
        CGRect(x: 1484, y: 819, width: 104, height: 52),
        CGRect(x: 1420, y: 851, width: 104, height: 52),
        CGRect(x: 1356, y: 883, width: 104, height: 52),
        CGRect(x: 1292, y: 915, width: 104, height: 52),
        CGRect(x: 1228, y: 947, width: 104, height: 52),
        CGRect(x: 1164, y: 979, width: 104, height: 52),
        CGRect(x: 1100, y: 1011, width: 104, height: 52),
        CGRect(x: 1036, y: 1043, width: 104, height: 52),
        CGRect(x: 972, y: 1075, width: 104, height: 52),
        CGRect(x: 908, y: 1107, width: 104, height: 52),
        CGRect(x: 844, y: 1139, width: 104, height: 52),
        CGRect(x: 780, y: 1171, width: 104, height: 52),
        CGRect(x: 716, y: 1203, width: 104, height: 52),
        CGRect(x: 652, y: 1235, width: 104, height: 52),
        CGRect(x: 588, y: 1267, width: 104, height: 52),
        CGRect(x: 524, y: 1299, width: 104, height: 52),
        CGRect(x: 2508, y: 371, width: 104, height: 52),
        CGRect(x: 2444, y: 403, width: 104, height: 52),
        CGRect(x: 2380, y: 435, width: 104, height: 52),
        CGRect(x: 2316, y: 467, width: 104, height: 52),
        CGRect(x: 2252, y: 499, width: 104, height: 52),
        CGRect(x: 2188, y: 531, width: 104, height: 52),
        CGRect(x: 2124, y: 563, width: 104, height: 52),
        CGRect(x: 2060, y: 595, width: 104, height: 52),
        CGRect(x: 1996, y: 627, width: 104, height: 52),
        CGRect(x: 1932, y: 659, width: 104, height: 52),
        CGRect(x: 1868, y: 691, width: 104, height: 52),
        CGRect(x: 1804, y: 723, width: 104, height: 52),
        CGRect(x: 1740, y: 755, width: 104, height: 52),
        CGRect(x: 1676, y: 787, width: 104, height: 52),
        CGRect(x: 1612, y: 819, width: 104, height: 52),
        CGRect(x: 1548, y: 851, width: 104, height: 52),
        CGRect(x: 1484, y: 883, width: 104, height: 52),
        CGRect(x: 1420, y: 915, width: 104, height: 52),
        CGRect(x: 1356, y: 947, width: 104, height: 52),
        CGRect(x: 1292, y: 979, width: 104, height: 52),
        CGRect(x: 1228, y: 1011, width: 104, height: 52),
        CGRect(x: 1164, y: 1043, width: 104, height: 52),
        CGRect(x: 1100, y: 1075, width: 104, height: 52),
        CGRect(x: 1036, y: 1107, width: 104, height: 52),
        CGRect(x: 972, y: 1139, width: 104, height: 52),
        CGRect(x: 908, y: 1171, width: 104, height: 52),
        CGRect(x: 844, y: 1203, width: 104, height: 52),
        CGRect(x: 780, y: 1235, width: 104, height: 52),
        CGRect(x: 716, y: 1267, width: 104, height: 52),
        CGRect(x: 652, y: 1299, width: 104, height: 52),
        CGRect(x: 588, y: 1331, width: 104, height: 52),
        CGRect(x: 2572, y: 403, width: 104, height: 52),
        CGRect(x: 2508, y: 435, width: 104, height: 52),
        CGRect(x: 2444, y: 467, width: 104, height: 52),
        CGRect(x: 2380, y: 499, width: 104, height: 52),
        CGRect(x: 2316, y: 531, width: 104, height: 52),
        CGRect(x: 2252, y: 563, width: 104, height: 52),
        CGRect(x: 2188, y: 595, width: 104, height: 52),
        CGRect(x: 2124, y: 627, width: 104, height: 52),
        CGRect(x: 2060, y: 659, width: 104, height: 52),
        CGRect(x: 1996, y: 691, width: 104, height: 52),
        CGRect(x: 1932, y: 723, width: 104, height: 52),
        CGRect(x: 1868, y: 755, width: 104, height: 52),
        CGRect(x: 1804, y: 787, width: 104, height: 52),
        CGRect(x: 1740, y: 819, width: 104, height: 52),
        CGRect(x: 1676, y: 851, width: 104, height: 52),
        CGRect(x: 1612, y: 883, width: 104, height: 52),
        CGRect(x: 1548, y: 915, width: 104, height: 52),
        CGRect(x: 1484, y: 947, width: 104, height: 52),
        CGRect(x: 1420, y: 979, width: 104, height: 52),
        CGRect(x: 1356, y: 1011, width: 104, height: 52),
        CGRect(x: 1292, y: 1043, width: 104, height: 52),
        CGRect(x: 1228, y: 1075, width: 104, height: 52),
        CGRect(x: 1164, y: 1107, width: 104, height: 52),
        CGRect(x: 1100, y: 1139, width: 104, height: 52),
        CGRect(x: 1036, y: 1171, width: 104, height: 52),
        CGRect(x: 972, y: 1203, width: 104, height: 52),
        CGRect(x: 908, y: 1235, width: 104, height: 52),
        CGRect(x: 844, y: 1267, width: 104, height: 52),
        CGRect(x: 780, y: 1299, width: 104, height: 52),
        CGRect(x: 716, y: 1331, width: 104, height: 52),
        CGRect(x: 652, y: 1363, width: 104, height: 52),
        CGRect(x: 2636, y: 435, width: 104, height: 52),
        CGRect(x: 2572, y: 467, width: 104, height: 52),
        CGRect(x: 2508, y: 499, width: 104, height: 52),
        CGRect(x: 2444, y: 531, width: 104, height: 52),
        CGRect(x: 2380, y: 563, width: 104, height: 52),
        CGRect(x: 2316, y: 595, width: 104, height: 52),
        CGRect(x: 2252, y: 627, width: 104, height: 52),
        CGRect(x: 2188, y: 659, width: 104, height: 52),
        CGRect(x: 2124, y: 691, width: 104, height: 52),
        CGRect(x: 2060, y: 723, width: 104, height: 52),
        CGRect(x: 1996, y: 755, width: 104, height: 52),
        CGRect(x: 1932, y: 787, width: 104, height: 52),
        CGRect(x: 1868, y: 819, width: 104, height: 52),
        CGRect(x: 1804, y: 851, width: 104, height: 52),
        CGRect(x: 1740, y: 883, width: 104, height: 52),
        CGRect(x: 1676, y: 915, width: 104, height: 52),
        CGRect(x: 1612, y: 947, width: 104, height: 52),
        CGRect(x: 1548, y: 979, width: 104, height: 52),
        CGRect(x: 1484, y: 1011, width: 104, height: 52),
        CGRect(x: 1420, y: 1043, width: 104, height: 52),
        CGRect(x: 1356, y: 1075, width: 104, height: 52),
        CGRect(x: 1292, y: 1107, width: 104, height: 52),
        CGRect(x: 1228, y: 1139, width: 104, height: 52),
        CGRect(x: 1164, y: 1171, width: 104, height: 52),
        CGRect(x: 1100, y: 1203, width: 104, height: 52),
        CGRect(x: 1036, y: 1235, width: 104, height: 52),
        CGRect(x: 972, y: 1267, width: 104, height: 52),
        CGRect(x: 908, y: 1299, width: 104, height: 52),
        CGRect(x: 844, y: 1331, width: 104, height: 52),
        CGRect(x: 780, y: 1363, width: 104, height: 52),
        CGRect(x: 716, y: 1395, width: 104, height: 52),
        CGRect(x: 2700, y: 467, width: 104, height: 52),
        CGRect(x: 2636, y: 499, width: 104, height: 52),
        CGRect(x: 2572, y: 531, width: 104, height: 52),
        CGRect(x: 2508, y: 563, width: 104, height: 52),
        CGRect(x: 2444, y: 595, width: 104, height: 52),
        CGRect(x: 2380, y: 627, width: 104, height: 52),
        CGRect(x: 2316, y: 659, width: 104, height: 52),
        CGRect(x: 2252, y: 691, width: 104, height: 52),
        CGRect(x: 1292, y: 1171, width: 104, height: 52),
        CGRect(x: 1228, y: 1203, width: 104, height: 52),
        CGRect(x: 1164, y: 1235, width: 104, height: 52),
        CGRect(x: 1100, y: 1267, width: 104, height: 52),
        CGRect(x: 1036, y: 1299, width: 104, height: 52),
        CGRect(x: 972, y: 1331, width: 104, height: 52),
        CGRect(x: 908, y: 1363, width: 104, height: 52),
        CGRect(x: 844, y: 1395, width: 104, height: 52),
        CGRect(x: 780, y: 1427, width: 104, height: 52),
        CGRect(x: 2764, y: 499, width: 104, height: 52),
        CGRect(x: 2700, y: 531, width: 104, height: 52),
        CGRect(x: 2636, y: 563, width: 104, height: 52),
        CGRect(x: 2572, y: 595, width: 104, height: 52),
        CGRect(x: 2508, y: 627, width: 104, height: 52),
        CGRect(x: 2444, y: 659, width: 104, height: 52),
        CGRect(x: 2380, y: 691, width: 104, height: 52),
        CGRect(x: 2316, y: 723, width: 104, height: 52),
        CGRect(x: 2252, y: 755, width: 104, height: 52),
        CGRect(x: 1356, y: 1203, width: 104, height: 52),
        CGRect(x: 1292, y: 1235, width: 104, height: 52),
        CGRect(x: 1228, y: 1267, width: 104, height: 52),
        CGRect(x: 1164, y: 1299, width: 104, height: 52),
        CGRect(x: 1100, y: 1331, width: 104, height: 52),
        CGRect(x: 1036, y: 1363, width: 104, height: 52),
        CGRect(x: 972, y: 1395, width: 104, height: 52),
        CGRect(x: 908, y: 1427, width: 104, height: 52),
        CGRect(x: 844, y: 1459, width: 104, height: 52),
        CGRect(x: 2828, y: 531, width: 104, height: 52),
        CGRect(x: 2764, y: 563, width: 104, height: 52),
        CGRect(x: 2700, y: 595, width: 104, height: 52),
        CGRect(x: 2636, y: 627, width: 104, height: 52),
        CGRect(x: 2572, y: 659, width: 104, height: 52),
        CGRect(x: 2508, y: 691, width: 104, height: 52),
        CGRect(x: 2444, y: 723, width: 104, height: 52),
        CGRect(x: 2380, y: 755, width: 104, height: 52),
        CGRect(x: 2316, y: 787, width: 104, height: 52),
        CGRect(x: 1420, y: 1235, width: 104, height: 52),
        CGRect(x: 1356, y: 1267, width: 104, height: 52),
        CGRect(x: 1292, y: 1299, width: 104, height: 52),
        CGRect(x: 1228, y: 1331, width: 104, height: 52),
        CGRect(x: 1164, y: 1363, width: 104, height: 52),
        CGRect(x: 1100, y: 1395, width: 104, height: 52),
        CGRect(x: 1036, y: 1427, width: 104, height: 52),
        CGRect(x: 972, y: 1459, width: 104, height: 52),
        CGRect(x: 908, y: 1491, width: 104, height: 52),
        CGRect(x: 2892, y: 563, width: 104, height: 52),
        CGRect(x: 2828, y: 595, width: 104, height: 52),
        CGRect(x: 2764, y: 627, width: 104, height: 52),
        CGRect(x: 2700, y: 659, width: 104, height: 52),
        CGRect(x: 2636, y: 691, width: 104, height: 52),
        CGRect(x: 2572, y: 723, width: 104, height: 52),
        CGRect(x: 2508, y: 755, width: 104, height: 52),
        CGRect(x: 2444, y: 787, width: 104, height: 52),
        CGRect(x: 2380, y: 819, width: 104, height: 52),
        CGRect(x: 1484, y: 1267, width: 104, height: 52),
        CGRect(x: 1420, y: 1299, width: 104, height: 52),
        CGRect(x: 1356, y: 1331, width: 104, height: 52),
        CGRect(x: 1292, y: 1363, width: 104, height: 52),
        CGRect(x: 1228, y: 1395, width: 104, height: 52),
        CGRect(x: 1164, y: 1427, width: 104, height: 52),
        CGRect(x: 1100, y: 1459, width: 104, height: 52),
        CGRect(x: 1036, y: 1491, width: 104, height: 52),
        CGRect(x: 972, y: 1523, width: 104, height: 52),
        CGRect(x: 2956, y: 595, width: 104, height: 52),
        CGRect(x: 2892, y: 627, width: 104, height: 52),
        CGRect(x: 2828, y: 659, width: 104, height: 52),
        CGRect(x: 2764, y: 691, width: 104, height: 52),
        CGRect(x: 2700, y: 723, width: 104, height: 52),
        CGRect(x: 2636, y: 755, width: 104, height: 52),
        CGRect(x: 2572, y: 787, width: 104, height: 52),
        CGRect(x: 2508, y: 819, width: 104, height: 52),
        CGRect(x: 2444, y: 851, width: 104, height: 52),
        CGRect(x: 1548, y: 1299, width: 104, height: 52),
        CGRect(x: 1484, y: 1331, width: 104, height: 52),
        CGRect(x: 1420, y: 1363, width: 104, height: 52),
        CGRect(x: 1356, y: 1395, width: 104, height: 52),
        CGRect(x: 1292, y: 1427, width: 104, height: 52),
        CGRect(x: 1228, y: 1459, width: 104, height: 52),
        CGRect(x: 1164, y: 1491, width: 104, height: 52),
        CGRect(x: 1100, y: 1523, width: 104, height: 52),
        CGRect(x: 1036, y: 1555, width: 104, height: 52),
        CGRect(x: 3020, y: 627, width: 104, height: 52),
        CGRect(x: 2956, y: 659, width: 104, height: 52),
        CGRect(x: 2892, y: 691, width: 104, height: 52),
        CGRect(x: 2828, y: 723, width: 104, height: 52),
        CGRect(x: 2764, y: 755, width: 104, height: 52),
        CGRect(x: 2700, y: 787, width: 104, height: 52),
        CGRect(x: 2636, y: 819, width: 104, height: 52),
        CGRect(x: 2572, y: 851, width: 104, height: 52),
        CGRect(x: 2508, y: 883, width: 104, height: 52),
        CGRect(x: 1548, y: 1363, width: 104, height: 52),
        CGRect(x: 1484, y: 1395, width: 104, height: 52),
        CGRect(x: 1420, y: 1427, width: 104, height: 52),
        CGRect(x: 1356, y: 1459, width: 104, height: 52),
        CGRect(x: 1292, y: 1491, width: 104, height: 52),
        CGRect(x: 1228, y: 1523, width: 104, height: 52),
        CGRect(x: 1164, y: 1555, width: 104, height: 52),
        CGRect(x: 1100, y: 1587, width: 104, height: 52),
        CGRect(x: 3084, y: 659, width: 104, height: 52),
        CGRect(x: 3020, y: 691, width: 104, height: 52),
        CGRect(x: 2956, y: 723, width: 104, height: 52),
        CGRect(x: 2892, y: 755, width: 104, height: 52),
        CGRect(x: 2828, y: 787, width: 104, height: 52),
        CGRect(x: 2764, y: 819, width: 104, height: 52),
        CGRect(x: 2700, y: 851, width: 104, height: 52),
        CGRect(x: 2636, y: 883, width: 104, height: 52),
        CGRect(x: 2572, y: 915, width: 104, height: 52),
        CGRect(x: 1612, y: 1395, width: 104, height: 52),
        CGRect(x: 1548, y: 1427, width: 104, height: 52),
        CGRect(x: 1484, y: 1459, width: 104, height: 52),
        CGRect(x: 1420, y: 1491, width: 104, height: 52),
        CGRect(x: 1356, y: 1523, width: 104, height: 52),
        CGRect(x: 1292, y: 1555, width: 104, height: 52),
        CGRect(x: 1228, y: 1587, width: 104, height: 52),
        CGRect(x: 1164, y: 1619, width: 104, height: 52),
        CGRect(x: 3148, y: 691, width: 104, height: 52),
        CGRect(x: 3084, y: 723, width: 104, height: 52),
        CGRect(x: 3020, y: 755, width: 104, height: 52),
        CGRect(x: 2956, y: 787, width: 104, height: 52),
        CGRect(x: 2892, y: 819, width: 104, height: 52),
        CGRect(x: 2828, y: 851, width: 104, height: 52),
        CGRect(x: 2764, y: 883, width: 104, height: 52),
        CGRect(x: 2700, y: 915, width: 104, height: 52),
        CGRect(x: 2636, y: 947, width: 104, height: 52),
        CGRect(x: 1676, y: 1427, width: 104, height: 52),
        CGRect(x: 1612, y: 1459, width: 104, height: 52),
        CGRect(x: 1548, y: 1491, width: 104, height: 52),
        CGRect(x: 1484, y: 1523, width: 104, height: 52),
        CGRect(x: 1420, y: 1555, width: 104, height: 52),
        CGRect(x: 1356, y: 1587, width: 104, height: 52),
        CGRect(x: 1292, y: 1619, width: 104, height: 52),
        CGRect(x: 1228, y: 1651, width: 104, height: 52),
        CGRect(x: 3212, y: 723, width: 104, height: 52),
        CGRect(x: 3148, y: 755, width: 104, height: 52),
        CGRect(x: 3084, y: 787, width: 104, height: 52),
        CGRect(x: 3020, y: 819, width: 104, height: 52),
        CGRect(x: 2956, y: 851, width: 104, height: 52),
        CGRect(x: 2892, y: 883, width: 104, height: 52),
        CGRect(x: 2828, y: 915, width: 104, height: 52),
        CGRect(x: 2764, y: 947, width: 104, height: 52),
        CGRect(x: 2700, y: 979, width: 104, height: 52),
        CGRect(x: 1740, y: 1459, width: 104, height: 52),
        CGRect(x: 1676, y: 1491, width: 104, height: 52),
        CGRect(x: 1612, y: 1523, width: 104, height: 52),
        CGRect(x: 1548, y: 1555, width: 104, height: 52),
        CGRect(x: 1484, y: 1587, width: 104, height: 52),
        CGRect(x: 1420, y: 1619, width: 104, height: 52),
        CGRect(x: 1356, y: 1651, width: 104, height: 52),
        CGRect(x: 1292, y: 1683, width: 104, height: 52),
        CGRect(x: 3276, y: 755, width: 104, height: 52),
        CGRect(x: 3212, y: 787, width: 104, height: 52),
        CGRect(x: 3148, y: 819, width: 104, height: 52),
        CGRect(x: 3084, y: 851, width: 104, height: 52),
        CGRect(x: 3020, y: 883, width: 104, height: 52),
        CGRect(x: 2956, y: 915, width: 104, height: 52),
        CGRect(x: 2892, y: 947, width: 104, height: 52),
        CGRect(x: 2828, y: 979, width: 104, height: 52),
        CGRect(x: 2764, y: 1011, width: 104, height: 52),
        CGRect(x: 1804, y: 1491, width: 104, height: 52),
        CGRect(x: 1740, y: 1523, width: 104, height: 52),
        CGRect(x: 1676, y: 1555, width: 104, height: 52),
        CGRect(x: 1612, y: 1587, width: 104, height: 52),
        CGRect(x: 1548, y: 1619, width: 104, height: 52),
        CGRect(x: 1484, y: 1651, width: 104, height: 52),
        CGRect(x: 1420, y: 1683, width: 104, height: 52),
        CGRect(x: 1356, y: 1715, width: 104, height: 52),
        CGRect(x: 3340, y: 787, width: 104, height: 52),
        CGRect(x: 3276, y: 819, width: 104, height: 52),
        CGRect(x: 3212, y: 851, width: 104, height: 52),
        CGRect(x: 3148, y: 883, width: 104, height: 52),
        CGRect(x: 3084, y: 915, width: 104, height: 52),
        CGRect(x: 3020, y: 947, width: 104, height: 52),
        CGRect(x: 2956, y: 979, width: 104, height: 52),
        CGRect(x: 2892, y: 1011, width: 104, height: 52),
        CGRect(x: 2828, y: 1043, width: 104, height: 52),
        CGRect(x: 2764, y: 1075, width: 104, height: 52),
        CGRect(x: 2700, y: 1107, width: 104, height: 52),
        CGRect(x: 2636, y: 1139, width: 104, height: 52),
        CGRect(x: 2572, y: 1171, width: 104, height: 52),
        CGRect(x: 2508, y: 1203, width: 104, height: 52),
        CGRect(x: 2444, y: 1235, width: 104, height: 52),
        CGRect(x: 2380, y: 1267, width: 104, height: 52),
        CGRect(x: 2316, y: 1299, width: 104, height: 52),
        CGRect(x: 2252, y: 1331, width: 104, height: 52),
        CGRect(x: 2188, y: 1363, width: 104, height: 52),
        CGRect(x: 2124, y: 1395, width: 104, height: 52),
        CGRect(x: 2060, y: 1427, width: 104, height: 52),
        CGRect(x: 1996, y: 1459, width: 104, height: 52),
        CGRect(x: 1932, y: 1491, width: 104, height: 52),
        CGRect(x: 1868, y: 1523, width: 104, height: 52),
        CGRect(x: 1804, y: 1555, width: 104, height: 52),
        CGRect(x: 1740, y: 1587, width: 104, height: 52),
        CGRect(x: 1676, y: 1619, width: 104, height: 52),
        CGRect(x: 1612, y: 1651, width: 104, height: 52),
        CGRect(x: 1548, y: 1683, width: 104, height: 52),
        CGRect(x: 1484, y: 1715, width: 104, height: 52),
        CGRect(x: 1420, y: 1747, width: 104, height: 52),
        CGRect(x: 3404, y: 819, width: 104, height: 52),
        CGRect(x: 3340, y: 851, width: 104, height: 52),
        CGRect(x: 3276, y: 883, width: 104, height: 52),
        CGRect(x: 3212, y: 915, width: 104, height: 52),
        CGRect(x: 3148, y: 947, width: 104, height: 52),
        CGRect(x: 3084, y: 979, width: 104, height: 52),
        CGRect(x: 3020, y: 1011, width: 104, height: 52),
        CGRect(x: 2956, y: 1043, width: 104, height: 52),
        CGRect(x: 2892, y: 1075, width: 104, height: 52),
        CGRect(x: 2828, y: 1107, width: 104, height: 52),
        CGRect(x: 2764, y: 1139, width: 104, height: 52),
        CGRect(x: 2700, y: 1171, width: 104, height: 52),
        CGRect(x: 2636, y: 1203, width: 104, height: 52),
        CGRect(x: 2572, y: 1235, width: 104, height: 52),
        CGRect(x: 2508, y: 1267, width: 104, height: 52),
        CGRect(x: 2444, y: 1299, width: 104, height: 52),
        CGRect(x: 2380, y: 1331, width: 104, height: 52),
        CGRect(x: 2316, y: 1363, width: 104, height: 52),
        CGRect(x: 2252, y: 1395, width: 104, height: 52),
        CGRect(x: 2188, y: 1427, width: 104, height: 52),
        CGRect(x: 2124, y: 1459, width: 104, height: 52),
        CGRect(x: 2060, y: 1491, width: 104, height: 52),
        CGRect(x: 1996, y: 1523, width: 104, height: 52),
        CGRect(x: 1932, y: 1555, width: 104, height: 52),
        CGRect(x: 1868, y: 1587, width: 104, height: 52),
        CGRect(x: 1804, y: 1619, width: 104, height: 52),
        CGRect(x: 1740, y: 1651, width: 104, height: 52),
        CGRect(x: 1676, y: 1683, width: 104, height: 52),
        CGRect(x: 1612, y: 1715, width: 104, height: 52),
        CGRect(x: 1548, y: 1747, width: 104, height: 52),
        CGRect(x: 1484, y: 1779, width: 104, height: 52),
        CGRect(x: 3468, y: 851, width: 104, height: 52),
        CGRect(x: 3404, y: 883, width: 104, height: 52),
        CGRect(x: 3340, y: 915, width: 104, height: 52),
        CGRect(x: 3276, y: 947, width: 104, height: 52),
        CGRect(x: 3212, y: 979, width: 104, height: 52),
        CGRect(x: 3148, y: 1011, width: 104, height: 52),
        CGRect(x: 3084, y: 1043, width: 104, height: 52),
        CGRect(x: 3020, y: 1075, width: 104, height: 52),
        CGRect(x: 2956, y: 1107, width: 104, height: 52),
        CGRect(x: 2892, y: 1139, width: 104, height: 52),
        CGRect(x: 2828, y: 1171, width: 104, height: 52),
        CGRect(x: 2764, y: 1203, width: 104, height: 52),
        CGRect(x: 2700, y: 1235, width: 104, height: 52),
        CGRect(x: 2636, y: 1267, width: 104, height: 52),
        CGRect(x: 2572, y: 1299, width: 104, height: 52),
        CGRect(x: 2508, y: 1331, width: 104, height: 52),
        CGRect(x: 2444, y: 1363, width: 104, height: 52),
        CGRect(x: 2380, y: 1395, width: 104, height: 52),
        CGRect(x: 2316, y: 1427, width: 104, height: 52),
        CGRect(x: 2252, y: 1459, width: 104, height: 52),
        CGRect(x: 2188, y: 1491, width: 104, height: 52),
        CGRect(x: 2124, y: 1523, width: 104, height: 52),
        CGRect(x: 2060, y: 1555, width: 104, height: 52),
        CGRect(x: 1996, y: 1587, width: 104, height: 52),
        CGRect(x: 1932, y: 1619, width: 104, height: 52),
        CGRect(x: 1868, y: 1651, width: 104, height: 52),
        CGRect(x: 1804, y: 1683, width: 104, height: 52),
        CGRect(x: 1740, y: 1715, width: 104, height: 52),
        CGRect(x: 1676, y: 1747, width: 104, height: 52),
        CGRect(x: 1612, y: 1779, width: 104, height: 52),
        CGRect(x: 1548, y: 1811, width: 104, height: 52),
        CGRect(x: 3532, y: 883, width: 104, height: 52),
        CGRect(x: 3468, y: 915, width: 104, height: 52),
        CGRect(x: 3404, y: 947, width: 104, height: 52),
        CGRect(x: 3340, y: 979, width: 104, height: 52),
        CGRect(x: 3276, y: 1011, width: 104, height: 52),
        CGRect(x: 3212, y: 1043, width: 104, height: 52),
        CGRect(x: 3148, y: 1075, width: 104, height: 52),
        CGRect(x: 3084, y: 1107, width: 104, height: 52),
        CGRect(x: 3020, y: 1139, width: 104, height: 52),
        CGRect(x: 2956, y: 1171, width: 104, height: 52),
        CGRect(x: 2892, y: 1203, width: 104, height: 52),
        CGRect(x: 2828, y: 1235, width: 104, height: 52),
        CGRect(x: 2764, y: 1267, width: 104, height: 52),
        CGRect(x: 2700, y: 1299, width: 104, height: 52),
        CGRect(x: 2636, y: 1331, width: 104, height: 52),
        CGRect(x: 2572, y: 1363, width: 104, height: 52),
        CGRect(x: 2508, y: 1395, width: 104, height: 52),
        CGRect(x: 2444, y: 1427, width: 104, height: 52),
        CGRect(x: 2380, y: 1459, width: 104, height: 52),
        CGRect(x: 2316, y: 1491, width: 104, height: 52),
        CGRect(x: 2252, y: 1523, width: 104, height: 52),
        CGRect(x: 2188, y: 1555, width: 104, height: 52),
        CGRect(x: 2124, y: 1587, width: 104, height: 52),
        CGRect(x: 2060, y: 1619, width: 104, height: 52),
        CGRect(x: 1996, y: 1651, width: 104, height: 52),
        CGRect(x: 1932, y: 1683, width: 104, height: 52),
        CGRect(x: 1868, y: 1715, width: 104, height: 52),
        CGRect(x: 1804, y: 1747, width: 104, height: 52),
        CGRect(x: 1740, y: 1779, width: 104, height: 52),
        CGRect(x: 1676, y: 1811, width: 104, height: 52),
        CGRect(x: 1612, y: 1843, width: 104, height: 52),
        CGRect(x: 3596, y: 915, width: 104, height: 52),
        CGRect(x: 3532, y: 947, width: 104, height: 52),
        CGRect(x: 3468, y: 979, width: 104, height: 52),
        CGRect(x: 3404, y: 1011, width: 104, height: 52),
        CGRect(x: 3340, y: 1043, width: 104, height: 52),
        CGRect(x: 3276, y: 1075, width: 104, height: 52),
        CGRect(x: 3212, y: 1107, width: 104, height: 52),
        CGRect(x: 3148, y: 1139, width: 104, height: 52),
        CGRect(x: 3084, y: 1171, width: 104, height: 52),
        CGRect(x: 3020, y: 1203, width: 104, height: 52),
        CGRect(x: 2956, y: 1235, width: 104, height: 52),
        CGRect(x: 2892, y: 1267, width: 104, height: 52),
        CGRect(x: 2828, y: 1299, width: 104, height: 52),
        CGRect(x: 2764, y: 1331, width: 104, height: 52),
        CGRect(x: 2700, y: 1363, width: 104, height: 52),
        CGRect(x: 2636, y: 1395, width: 104, height: 52),
        CGRect(x: 2572, y: 1427, width: 104, height: 52),
        CGRect(x: 2508, y: 1459, width: 104, height: 52),
        CGRect(x: 2444, y: 1491, width: 104, height: 52),
        CGRect(x: 2380, y: 1523, width: 104, height: 52),
        CGRect(x: 2316, y: 1555, width: 104, height: 52),
        CGRect(x: 2252, y: 1587, width: 104, height: 52),
        CGRect(x: 2188, y: 1619, width: 104, height: 52),
        CGRect(x: 2124, y: 1651, width: 104, height: 52),
        CGRect(x: 2060, y: 1683, width: 104, height: 52),
        CGRect(x: 1996, y: 1715, width: 104, height: 52),
        CGRect(x: 1932, y: 1747, width: 104, height: 52),
        CGRect(x: 1868, y: 1779, width: 104, height: 52),
        CGRect(x: 1804, y: 1811, width: 104, height: 52),
        CGRect(x: 1740, y: 1843, width: 104, height: 52),
        CGRect(x: 1676, y: 1875, width: 104, height: 52),
        CGRect(x: 3660, y: 947, width: 104, height: 52),
        CGRect(x: 3596, y: 979, width: 104, height: 52),
        CGRect(x: 3532, y: 1011, width: 104, height: 52),
        CGRect(x: 3468, y: 1043, width: 104, height: 52),
        CGRect(x: 3404, y: 1075, width: 104, height: 52),
        CGRect(x: 3340, y: 1107, width: 104, height: 52),
        CGRect(x: 3276, y: 1139, width: 104, height: 52),
        CGRect(x: 3212, y: 1171, width: 104, height: 52),
        CGRect(x: 3148, y: 1203, width: 104, height: 52),
        CGRect(x: 3084, y: 1235, width: 104, height: 52),
        CGRect(x: 3020, y: 1267, width: 104, height: 52),
        CGRect(x: 2956, y: 1299, width: 104, height: 52),
        CGRect(x: 2892, y: 1331, width: 104, height: 52),
        CGRect(x: 2828, y: 1363, width: 104, height: 52),
        CGRect(x: 2764, y: 1395, width: 104, height: 52),
        CGRect(x: 2700, y: 1427, width: 104, height: 52),
        CGRect(x: 2636, y: 1459, width: 104, height: 52),
        CGRect(x: 2572, y: 1491, width: 104, height: 52),
        CGRect(x: 2508, y: 1523, width: 104, height: 52),
        CGRect(x: 2444, y: 1555, width: 104, height: 52),
        CGRect(x: 2380, y: 1587, width: 104, height: 52),
        CGRect(x: 2316, y: 1619, width: 104, height: 52),
        CGRect(x: 2252, y: 1651, width: 104, height: 52),
        CGRect(x: 2188, y: 1683, width: 104, height: 52),
        CGRect(x: 2124, y: 1715, width: 104, height: 52),
        CGRect(x: 2060, y: 1747, width: 104, height: 52),
        CGRect(x: 1996, y: 1779, width: 104, height: 52),
        CGRect(x: 1932, y: 1811, width: 104, height: 52),
        CGRect(x: 1868, y: 1843, width: 104, height: 52),
        CGRect(x: 1804, y: 1875, width: 104, height: 52),
        CGRect(x: 1740, y: 1907, width: 104, height: 52),
        CGRect(x: 3724, y: 979, width: 104, height: 52),
        CGRect(x: 3660, y: 1011, width: 104, height: 52),
        CGRect(x: 3596, y: 1043, width: 104, height: 52),
        CGRect(x: 3532, y: 1075, width: 104, height: 52),
        CGRect(x: 3468, y: 1107, width: 104, height: 52),
        CGRect(x: 3404, y: 1139, width: 104, height: 52),
        CGRect(x: 3340, y: 1171, width: 104, height: 52),
        CGRect(x: 3276, y: 1203, width: 104, height: 52),
        CGRect(x: 3212, y: 1235, width: 104, height: 52),
        CGRect(x: 3148, y: 1267, width: 104, height: 52),
        CGRect(x: 3084, y: 1299, width: 104, height: 52),
        CGRect(x: 3020, y: 1331, width: 104, height: 52),
        CGRect(x: 2956, y: 1363, width: 104, height: 52),
        CGRect(x: 2892, y: 1395, width: 104, height: 52),
        CGRect(x: 2828, y: 1427, width: 104, height: 52),
        CGRect(x: 2764, y: 1459, width: 104, height: 52),
        CGRect(x: 2700, y: 1491, width: 104, height: 52),
        CGRect(x: 2636, y: 1523, width: 104, height: 52),
        CGRect(x: 2572, y: 1555, width: 104, height: 52),
        CGRect(x: 2508, y: 1587, width: 104, height: 52),
        CGRect(x: 2444, y: 1619, width: 104, height: 52),
        CGRect(x: 2380, y: 1651, width: 104, height: 52),
        CGRect(x: 2316, y: 1683, width: 104, height: 52),
        CGRect(x: 2252, y: 1715, width: 104, height: 52),
        CGRect(x: 2188, y: 1747, width: 104, height: 52),
        CGRect(x: 2124, y: 1779, width: 104, height: 52),
        CGRect(x: 2060, y: 1811, width: 104, height: 52),
        CGRect(x: 1996, y: 1843, width: 104, height: 52),
        CGRect(x: 1932, y: 1875, width: 104, height: 52),
        CGRect(x: 1868, y: 1907, width: 104, height: 52),
        CGRect(x: 1804, y: 1939, width: 104, height: 52),
        CGRect(x: 3788, y: 1011, width: 104, height: 52),
        CGRect(x: 3724, y: 1043, width: 104, height: 52),
        CGRect(x: 3660, y: 1075, width: 104, height: 52),
        CGRect(x: 3596, y: 1107, width: 104, height: 52),
        CGRect(x: 3532, y: 1139, width: 104, height: 52),
        CGRect(x: 3468, y: 1171, width: 104, height: 52),
        CGRect(x: 3404, y: 1203, width: 104, height: 52),
        CGRect(x: 3340, y: 1235, width: 104, height: 52),
        CGRect(x: 3276, y: 1267, width: 104, height: 52),
        CGRect(x: 3212, y: 1299, width: 104, height: 52),
        CGRect(x: 3148, y: 1331, width: 104, height: 52),
        CGRect(x: 3084, y: 1363, width: 104, height: 52),
        CGRect(x: 3020, y: 1395, width: 104, height: 52),
        CGRect(x: 2956, y: 1427, width: 104, height: 52),
        CGRect(x: 2892, y: 1459, width: 104, height: 52),
        CGRect(x: 2828, y: 1491, width: 104, height: 52),
        CGRect(x: 2764, y: 1523, width: 104, height: 52),
        CGRect(x: 2700, y: 1555, width: 104, height: 52),
        CGRect(x: 2636, y: 1587, width: 104, height: 52),
        CGRect(x: 2572, y: 1619, width: 104, height: 52),
        CGRect(x: 2508, y: 1651, width: 104, height: 52),
        CGRect(x: 2444, y: 1683, width: 104, height: 52),
        CGRect(x: 2380, y: 1715, width: 104, height: 52),
        CGRect(x: 2316, y: 1747, width: 104, height: 52),
        CGRect(x: 2252, y: 1779, width: 104, height: 52),
        CGRect(x: 2188, y: 1811, width: 104, height: 52),
        CGRect(x: 2124, y: 1843, width: 104, height: 52),
        CGRect(x: 2060, y: 1875, width: 104, height: 52),
        CGRect(x: 1996, y: 1907, width: 104, height: 52),
        CGRect(x: 1932, y: 1939, width: 104, height: 52),
        CGRect(x: 1868, y: 1971, width: 104, height: 52),
        CGRect(x: 3852, y: 1043, width: 104, height: 52),
        CGRect(x: 3788, y: 1075, width: 104, height: 52),
        CGRect(x: 3724, y: 1107, width: 104, height: 52),
        CGRect(x: 3660, y: 1139, width: 104, height: 52),
        CGRect(x: 3596, y: 1171, width: 104, height: 52),
        CGRect(x: 3532, y: 1203, width: 104, height: 52),
        CGRect(x: 3468, y: 1235, width: 104, height: 52),
        CGRect(x: 3404, y: 1267, width: 104, height: 52),
        CGRect(x: 3340, y: 1299, width: 104, height: 52),
        CGRect(x: 3276, y: 1331, width: 104, height: 52),
        CGRect(x: 3212, y: 1363, width: 104, height: 52),
        CGRect(x: 3148, y: 1395, width: 104, height: 52),
        CGRect(x: 3084, y: 1427, width: 104, height: 52),
        CGRect(x: 3020, y: 1459, width: 104, height: 52),
        CGRect(x: 2956, y: 1491, width: 104, height: 52),
        CGRect(x: 2892, y: 1523, width: 104, height: 52),
        CGRect(x: 2828, y: 1555, width: 104, height: 52),
        CGRect(x: 2764, y: 1587, width: 104, height: 52),
        CGRect(x: 2700, y: 1619, width: 104, height: 52),
        CGRect(x: 2636, y: 1651, width: 104, height: 52),
        CGRect(x: 2572, y: 1683, width: 104, height: 52),
        CGRect(x: 2508, y: 1715, width: 104, height: 52),
        CGRect(x: 2444, y: 1747, width: 104, height: 52),
        CGRect(x: 2380, y: 1779, width: 104, height: 52),
        CGRect(x: 2316, y: 1811, width: 104, height: 52),
        CGRect(x: 2252, y: 1843, width: 104, height: 52),
        CGRect(x: 2188, y: 1875, width: 104, height: 52),
        CGRect(x: 2124, y: 1907, width: 104, height: 52),
        CGRect(x: 2060, y: 1939, width: 104, height: 52),
        CGRect(x: 1996, y: 1971, width: 104, height: 52),
        CGRect(x: 1932, y: 2003, width: 104, height: 52),
        CGRect(x: 3916, y: 1075, width: 104, height: 52),
        CGRect(x: 3852, y: 1107, width: 104, height: 52),
        CGRect(x: 3788, y: 1139, width: 104, height: 52),
        CGRect(x: 3724, y: 1171, width: 104, height: 52),
        CGRect(x: 3660, y: 1203, width: 104, height: 52),
        CGRect(x: 3596, y: 1235, width: 104, height: 52),
        CGRect(x: 3532, y: 1267, width: 104, height: 52),
        CGRect(x: 3468, y: 1299, width: 104, height: 52),
        CGRect(x: 3404, y: 1331, width: 104, height: 52),
        CGRect(x: 3340, y: 1363, width: 104, height: 52),
        CGRect(x: 3276, y: 1395, width: 104, height: 52),
        CGRect(x: 3212, y: 1427, width: 104, height: 52),
        CGRect(x: 3148, y: 1459, width: 104, height: 52),
        CGRect(x: 3084, y: 1491, width: 104, height: 52),
        CGRect(x: 3020, y: 1523, width: 104, height: 52),
        CGRect(x: 2956, y: 1555, width: 104, height: 52),
        CGRect(x: 2892, y: 1587, width: 104, height: 52),
        CGRect(x: 2828, y: 1619, width: 104, height: 52),
        CGRect(x: 2764, y: 1651, width: 104, height: 52),
        CGRect(x: 2700, y: 1683, width: 104, height: 52),
        CGRect(x: 2636, y: 1715, width: 104, height: 52),
        CGRect(x: 2572, y: 1747, width: 104, height: 52),
        CGRect(x: 2508, y: 1779, width: 104, height: 52),
        CGRect(x: 2444, y: 1811, width: 104, height: 52),
        CGRect(x: 2380, y: 1843, width: 104, height: 52),
        CGRect(x: 2316, y: 1875, width: 104, height: 52),
        CGRect(x: 2252, y: 1907, width: 104, height: 52),
        CGRect(x: 2188, y: 1939, width: 104, height: 52),
        CGRect(x: 2124, y: 1971, width: 104, height: 52),
        CGRect(x: 2060, y: 2003, width: 104, height: 52),
        CGRect(x: 1996, y: 2035, width: 104, height: 52),
    ]

    /// Partition solids: overlapping tight AABBs along the wall; doorway open.
    static let authoredPartitionWallNorthObstacle = CGRect(x: 1586, y: 1391, width: 40, height: 20)
    static let authoredPartitionWallSouthObstacle = CGRect(x: 2614, y: 876, width: 40, height: 20)
    static let authoredPartitionSegments: [CGRect] = [
        CGRect(x: 1586, y: 1391, width: 40, height: 20),
        CGRect(x: 1574, y: 1384, width: 40, height: 20),
        CGRect(x: 1561, y: 1377, width: 40, height: 20),
        CGRect(x: 1601, y: 1384, width: 40, height: 20),
        CGRect(x: 1589, y: 1377, width: 40, height: 20),
        CGRect(x: 1576, y: 1370, width: 40, height: 20),
        CGRect(x: 1616, y: 1377, width: 40, height: 20),
        CGRect(x: 1603, y: 1370, width: 40, height: 20),
        CGRect(x: 1591, y: 1363, width: 40, height: 20),
        CGRect(x: 1631, y: 1370, width: 40, height: 20),
        CGRect(x: 1618, y: 1363, width: 40, height: 20),
        CGRect(x: 1606, y: 1355, width: 40, height: 20),
        CGRect(x: 1646, y: 1363, width: 40, height: 20),
        CGRect(x: 1633, y: 1355, width: 40, height: 20),
        CGRect(x: 1621, y: 1348, width: 40, height: 20),
        CGRect(x: 1661, y: 1356, width: 40, height: 20),
        CGRect(x: 1648, y: 1348, width: 40, height: 20),
        CGRect(x: 1635, y: 1341, width: 40, height: 20),
        CGRect(x: 1676, y: 1348, width: 40, height: 20),
        CGRect(x: 1663, y: 1341, width: 40, height: 20),
        CGRect(x: 1650, y: 1334, width: 40, height: 20),
        CGRect(x: 1691, y: 1341, width: 40, height: 20),
        CGRect(x: 1678, y: 1334, width: 40, height: 20),
        CGRect(x: 1665, y: 1327, width: 40, height: 20),
        CGRect(x: 1705, y: 1334, width: 40, height: 20),
        CGRect(x: 1693, y: 1327, width: 40, height: 20),
        CGRect(x: 1680, y: 1320, width: 40, height: 20),
        CGRect(x: 1720, y: 1327, width: 40, height: 20),
        CGRect(x: 1708, y: 1320, width: 40, height: 20),
        CGRect(x: 1695, y: 1313, width: 40, height: 20),
        CGRect(x: 1735, y: 1320, width: 40, height: 20),
        CGRect(x: 1722, y: 1313, width: 40, height: 20),
        CGRect(x: 1710, y: 1306, width: 40, height: 20),
        CGRect(x: 1750, y: 1313, width: 40, height: 20),
        CGRect(x: 1737, y: 1306, width: 40, height: 20),
        CGRect(x: 1725, y: 1299, width: 40, height: 20),
        CGRect(x: 1765, y: 1306, width: 40, height: 20),
        CGRect(x: 1752, y: 1299, width: 40, height: 20),
        CGRect(x: 1740, y: 1292, width: 40, height: 20),
        CGRect(x: 1780, y: 1299, width: 40, height: 20),
        CGRect(x: 1767, y: 1292, width: 40, height: 20),
        CGRect(x: 1754, y: 1285, width: 40, height: 20),
        CGRect(x: 1795, y: 1292, width: 40, height: 20),
        CGRect(x: 1782, y: 1285, width: 40, height: 20),
        CGRect(x: 1769, y: 1278, width: 40, height: 20),
        CGRect(x: 1810, y: 1285, width: 40, height: 20),
        CGRect(x: 1797, y: 1278, width: 40, height: 20),
        CGRect(x: 1784, y: 1271, width: 40, height: 20),
        CGRect(x: 1824, y: 1278, width: 40, height: 20),
        CGRect(x: 1812, y: 1271, width: 40, height: 20),
        CGRect(x: 1799, y: 1263, width: 40, height: 20),
        CGRect(x: 1839, y: 1271, width: 40, height: 20),
        CGRect(x: 1827, y: 1264, width: 40, height: 20),
        CGRect(x: 1814, y: 1256, width: 40, height: 20),
        CGRect(x: 1854, y: 1264, width: 40, height: 20),
        CGRect(x: 1841, y: 1256, width: 40, height: 20),
        CGRect(x: 1829, y: 1249, width: 40, height: 20),
        CGRect(x: 1869, y: 1256, width: 40, height: 20),
        CGRect(x: 1856, y: 1249, width: 40, height: 20),
        CGRect(x: 1844, y: 1242, width: 40, height: 20),
        CGRect(x: 1884, y: 1249, width: 40, height: 20),
        CGRect(x: 1871, y: 1242, width: 40, height: 20),
        CGRect(x: 1859, y: 1235, width: 40, height: 20),
        CGRect(x: 1899, y: 1242, width: 40, height: 20),
        CGRect(x: 1886, y: 1235, width: 40, height: 20),
        CGRect(x: 1873, y: 1228, width: 40, height: 20),
        CGRect(x: 1914, y: 1235, width: 40, height: 20),
        CGRect(x: 1901, y: 1228, width: 40, height: 20),
        CGRect(x: 1888, y: 1221, width: 40, height: 20),
        CGRect(x: 1929, y: 1228, width: 40, height: 20),
        CGRect(x: 1916, y: 1221, width: 40, height: 20),
        CGRect(x: 1903, y: 1214, width: 40, height: 20),
        CGRect(x: 1943, y: 1221, width: 40, height: 20),
        CGRect(x: 1931, y: 1214, width: 40, height: 20),
        CGRect(x: 1918, y: 1207, width: 40, height: 20),
        CGRect(x: 1958, y: 1214, width: 40, height: 20),
        CGRect(x: 1946, y: 1207, width: 40, height: 20),
        CGRect(x: 1933, y: 1200, width: 40, height: 20),
        CGRect(x: 1973, y: 1207, width: 40, height: 20),
        CGRect(x: 1960, y: 1200, width: 40, height: 20),
        CGRect(x: 1948, y: 1193, width: 40, height: 20),
        CGRect(x: 1988, y: 1200, width: 40, height: 20),
        CGRect(x: 1975, y: 1193, width: 40, height: 20),
        CGRect(x: 1963, y: 1186, width: 40, height: 20),
        CGRect(x: 2003, y: 1193, width: 40, height: 20),
        CGRect(x: 1990, y: 1186, width: 40, height: 20),
        CGRect(x: 1978, y: 1179, width: 40, height: 20),
        CGRect(x: 2018, y: 1186, width: 40, height: 20),
        CGRect(x: 2005, y: 1179, width: 40, height: 20),
        CGRect(x: 1992, y: 1172, width: 40, height: 20),
        CGRect(x: 2033, y: 1179, width: 40, height: 20),
        CGRect(x: 2020, y: 1172, width: 40, height: 20),
        CGRect(x: 2007, y: 1164, width: 40, height: 20),
        CGRect(x: 2048, y: 1172, width: 40, height: 20),
        CGRect(x: 2035, y: 1165, width: 40, height: 20),
        CGRect(x: 2022, y: 1157, width: 40, height: 20),
        CGRect(x: 2062, y: 1165, width: 40, height: 20),
        CGRect(x: 2050, y: 1157, width: 40, height: 20),
        CGRect(x: 2037, y: 1150, width: 40, height: 20),
        CGRect(x: 2077, y: 1157, width: 40, height: 20),
        CGRect(x: 2065, y: 1150, width: 40, height: 20),
        CGRect(x: 2052, y: 1143, width: 40, height: 20),
        CGRect(x: 2092, y: 1150, width: 40, height: 20),
        CGRect(x: 2080, y: 1143, width: 40, height: 20),
        CGRect(x: 2067, y: 1136, width: 40, height: 20),
        CGRect(x: 2107, y: 1143, width: 40, height: 20),
        CGRect(x: 2094, y: 1136, width: 40, height: 20),
        CGRect(x: 2082, y: 1129, width: 40, height: 20),
        CGRect(x: 2122, y: 1136, width: 40, height: 20),
        CGRect(x: 2109, y: 1129, width: 40, height: 20),
        CGRect(x: 2097, y: 1122, width: 40, height: 20),
        CGRect(x: 2137, y: 1129, width: 40, height: 20),
        CGRect(x: 2124, y: 1122, width: 40, height: 20),
        CGRect(x: 2111, y: 1115, width: 40, height: 20),
        CGRect(x: 2152, y: 1122, width: 40, height: 20),
        CGRect(x: 2139, y: 1115, width: 40, height: 20),
        CGRect(x: 2126, y: 1108, width: 40, height: 20),
        CGRect(x: 2167, y: 1115, width: 40, height: 20),
        CGRect(x: 2154, y: 1108, width: 40, height: 20),
        CGRect(x: 2141, y: 1101, width: 40, height: 20),
        CGRect(x: 2181, y: 1108, width: 40, height: 20),
        CGRect(x: 2169, y: 1101, width: 40, height: 20),
        CGRect(x: 2156, y: 1094, width: 40, height: 20),
        CGRect(x: 2196, y: 1101, width: 40, height: 20),
        CGRect(x: 2184, y: 1094, width: 40, height: 20),
        CGRect(x: 2171, y: 1087, width: 40, height: 20),
        CGRect(x: 2211, y: 1094, width: 40, height: 20),
        CGRect(x: 2199, y: 1087, width: 40, height: 20),
        CGRect(x: 2186, y: 1080, width: 40, height: 20),
        CGRect(x: 2226, y: 1087, width: 40, height: 20),
        CGRect(x: 2213, y: 1080, width: 40, height: 20),
        CGRect(x: 2201, y: 1073, width: 40, height: 20),
        CGRect(x: 2241, y: 1080, width: 40, height: 20),
        CGRect(x: 2228, y: 1073, width: 40, height: 20),
        CGRect(x: 2216, y: 1065, width: 40, height: 20),
        CGRect(x: 2256, y: 1073, width: 40, height: 20),
        CGRect(x: 2243, y: 1065, width: 40, height: 20),
        CGRect(x: 2230, y: 1058, width: 40, height: 20),
        CGRect(x: 2271, y: 1066, width: 40, height: 20),
        CGRect(x: 2258, y: 1058, width: 40, height: 20),
        CGRect(x: 2245, y: 1051, width: 40, height: 20),
        CGRect(x: 2286, y: 1058, width: 40, height: 20),
        CGRect(x: 2273, y: 1051, width: 40, height: 20),
        CGRect(x: 2260, y: 1044, width: 40, height: 20),
        CGRect(x: 2300, y: 1051, width: 40, height: 20),
        CGRect(x: 2288, y: 1044, width: 40, height: 20),
        CGRect(x: 2275, y: 1037, width: 40, height: 20),
        CGRect(x: 2315, y: 1044, width: 40, height: 20),
        CGRect(x: 2303, y: 1037, width: 40, height: 20),
        CGRect(x: 2290, y: 1030, width: 40, height: 20),
        CGRect(x: 2330, y: 1037, width: 40, height: 20),
        CGRect(x: 2318, y: 1030, width: 40, height: 20),
        CGRect(x: 2305, y: 1023, width: 40, height: 20),
        CGRect(x: 2345, y: 1030, width: 40, height: 20),
        CGRect(x: 2332, y: 1023, width: 40, height: 20),
        CGRect(x: 2320, y: 1016, width: 40, height: 20),
        CGRect(x: 2431, y: 989, width: 40, height: 20),
        CGRect(x: 2419, y: 982, width: 40, height: 20),
        CGRect(x: 2406, y: 975, width: 40, height: 20),
        CGRect(x: 2446, y: 982, width: 40, height: 20),
        CGRect(x: 2434, y: 975, width: 40, height: 20),
        CGRect(x: 2421, y: 968, width: 40, height: 20),
        CGRect(x: 2461, y: 975, width: 40, height: 20),
        CGRect(x: 2448, y: 968, width: 40, height: 20),
        CGRect(x: 2436, y: 961, width: 40, height: 20),
        CGRect(x: 2476, y: 968, width: 40, height: 20),
        CGRect(x: 2463, y: 961, width: 40, height: 20),
        CGRect(x: 2451, y: 954, width: 40, height: 20),
        CGRect(x: 2491, y: 961, width: 40, height: 20),
        CGRect(x: 2478, y: 954, width: 40, height: 20),
        CGRect(x: 2466, y: 947, width: 40, height: 20),
        CGRect(x: 2506, y: 954, width: 40, height: 20),
        CGRect(x: 2493, y: 947, width: 40, height: 20),
        CGRect(x: 2480, y: 940, width: 40, height: 20),
        CGRect(x: 2521, y: 947, width: 40, height: 20),
        CGRect(x: 2508, y: 940, width: 40, height: 20),
        CGRect(x: 2495, y: 932, width: 40, height: 20),
        CGRect(x: 2535, y: 940, width: 40, height: 20),
        CGRect(x: 2523, y: 932, width: 40, height: 20),
        CGRect(x: 2510, y: 925, width: 40, height: 20),
        CGRect(x: 2550, y: 933, width: 40, height: 20),
        CGRect(x: 2538, y: 925, width: 40, height: 20),
        CGRect(x: 2525, y: 918, width: 40, height: 20),
        CGRect(x: 2565, y: 925, width: 40, height: 20),
        CGRect(x: 2553, y: 918, width: 40, height: 20),
        CGRect(x: 2540, y: 911, width: 40, height: 20),
        CGRect(x: 2580, y: 918, width: 40, height: 20),
        CGRect(x: 2567, y: 911, width: 40, height: 20),
        CGRect(x: 2555, y: 904, width: 40, height: 20),
        CGRect(x: 2595, y: 911, width: 40, height: 20),
        CGRect(x: 2582, y: 904, width: 40, height: 20),
        CGRect(x: 2570, y: 897, width: 40, height: 20),
        CGRect(x: 2610, y: 904, width: 40, height: 20),
        CGRect(x: 2597, y: 897, width: 40, height: 20),
        CGRect(x: 2585, y: 890, width: 40, height: 20),
        CGRect(x: 2625, y: 897, width: 40, height: 20),
        CGRect(x: 2612, y: 890, width: 40, height: 20),
        CGRect(x: 2599, y: 883, width: 40, height: 20),
        CGRect(x: 2640, y: 890, width: 40, height: 20),
        CGRect(x: 2627, y: 883, width: 40, height: 20),
        CGRect(x: 2614, y: 876, width: 40, height: 20),
    ]

    static let authoredSafeObstacle = CGRect(x: 1494, y: 1260, width: 78, height: 40)
    static let authoredFilingCabinetBObstacle = CGRect(x: 1450, y: 1235, width: 71, height: 36)
    static let authoredFilingCabinetObstacle = CGRect(x: 1406, y: 1210, width: 71, height: 36)
    static let authoredBookshelfObstacle = CGRect(x: 1328, y: 1169, width: 119, height: 58)
    static let authoredArchiveBoxAObstacle = CGRect(x: 1431, y: 1171, width: 63, height: 32)
    static let authoredRadiatorObstacle = CGRect(x: 1697, y: 1381, width: 95, height: 46)
    static let authoredPersonalSideboardObstacle = CGRect(x: 1599, y: 1321, width: 126, height: 62)
    static let authoredPersonalFanObstacle = CGRect(x: 1675, y: 1328, width: 65, height: 33)
    static let authoredDeskEnsembleObstacle = CGRect(x: 1782, y: 1084, width: 187, height: 92)
    static let authoredVisitorArmchairObstacle = CGRect(x: 1849, y: 1190, width: 85, height: 43)
    static let authoredVisitorArmchairBObstacle = CGRect(x: 1988, y: 1124, width: 85, height: 43)
    static let authoredWastebasketObstacle = CGRect(x: 1713, y: 1133, width: 52, height: 26)
    static let authoredCoatRackObstacle = CGRect(x: 2712, y: 1088, width: 78, height: 40)
    static let authoredUmbrellaStandObstacle = CGRect(x: 2669, y: 1104, width: 46, height: 23)
    static let authoredWaitingChairAObstacle = CGRect(x: 2330, y: 1182, width: 72, height: 36)
    static let authoredWaitingTableObstacle = CGRect(x: 2390, y: 1154, width: 72, height: 36)
    static let authoredWaitingChairBObstacle = CGRect(x: 2449, y: 1125, width: 72, height: 36)

    private static var authoredObstacles: [CGRect] {
        [authoredDoorObstacle, authoredForegroundWallObstacle]
            + authoredBoundarySegments
            + authoredPartitionSegments
            + [
                authoredSafeObstacle,
                authoredFilingCabinetBObstacle,
                authoredFilingCabinetObstacle,
                authoredBookshelfObstacle,
                authoredArchiveBoxAObstacle,
                authoredRadiatorObstacle,
                authoredPersonalSideboardObstacle,
                authoredPersonalFanObstacle,
                authoredDeskEnsembleObstacle,
                authoredVisitorArmchairObstacle,
                authoredVisitorArmchairBObstacle,
                authoredWastebasketObstacle,
                authoredCoatRackObstacle,
                authoredUmbrellaStandObstacle,
                authoredWaitingChairAObstacle,
                authoredWaitingTableObstacle,
                authoredWaitingChairBObstacle,
            ]
    }

    // MARK: - Sample points (interior to each obstacle)

    static let authoredSafeSamplePoints: [CGPoint] = [
        CGPoint(x: 1_533, y: 1_280),
        CGPoint(x: 1_517, y: 1_274),
        CGPoint(x: 1_549, y: 1_286),
    ]
    static let authoredFilingCabinetBSamplePoints: [CGPoint] = [
        CGPoint(x: 1_486, y: 1_253),
        CGPoint(x: 1_472, y: 1_248),
        CGPoint(x: 1_500, y: 1_258),
    ]
    static let authoredFilingCabinetSamplePoints: [CGPoint] = [
        CGPoint(x: 1_442, y: 1_228),
        CGPoint(x: 1_427, y: 1_223),
        CGPoint(x: 1_456, y: 1_234),
    ]
    static let authoredBookshelfSamplePoints: [CGPoint] = [
        CGPoint(x: 1_387, y: 1_198),
        CGPoint(x: 1_363, y: 1_189),
        CGPoint(x: 1_411, y: 1_206),
    ]
    static let authoredArchiveBoxASamplePoints: [CGPoint] = [
        CGPoint(x: 1_463, y: 1_187),
        CGPoint(x: 1_450, y: 1_182),
        CGPoint(x: 1_475, y: 1_191),
    ]
    static let authoredRadiatorSamplePoints: [CGPoint] = [
        CGPoint(x: 1_744, y: 1_404),
        CGPoint(x: 1_725, y: 1_397),
        CGPoint(x: 1_763, y: 1_411),
    ]
    static let authoredPersonalSideboardSamplePoints: [CGPoint] = [
        CGPoint(x: 1_662, y: 1_352),
        CGPoint(x: 1_637, y: 1_343),
        CGPoint(x: 1_687, y: 1_361),
    ]
    static let authoredPersonalFanSamplePoints: [CGPoint] = [
        CGPoint(x: 1_707, y: 1_344),
        CGPoint(x: 1_694, y: 1_340),
        CGPoint(x: 1_720, y: 1_349),
    ]
    static let authoredDeskEnsembleSamplePoints: [CGPoint] = [
        CGPoint(x: 1_876, y: 1_131),
        CGPoint(x: 1_839, y: 1_117),
        CGPoint(x: 1_913, y: 1_144),
    ]
    static let authoredVisitorArmchairSamplePoints: [CGPoint] = [
        CGPoint(x: 1_891, y: 1_211),
        CGPoint(x: 1_874, y: 1_205),
        CGPoint(x: 1_908, y: 1_218),
    ]
    static let authoredVisitorArmchairBSamplePoints: [CGPoint] = [
        CGPoint(x: 2_030, y: 1_145),
        CGPoint(x: 2_013, y: 1_139),
        CGPoint(x: 2_047, y: 1_152),
    ]
    static let authoredWastebasketSamplePoints: [CGPoint] = [
        CGPoint(x: 1_739, y: 1_146),
        CGPoint(x: 1_729, y: 1_142),
        CGPoint(x: 1_750, y: 1_150),
    ]
    static let authoredCoatRackSamplePoints: [CGPoint] = [
        CGPoint(x: 2_752, y: 1_108),
        CGPoint(x: 2_736, y: 1_102),
        CGPoint(x: 2_767, y: 1_114),
    ]
    static let authoredUmbrellaStandSamplePoints: [CGPoint] = [
        CGPoint(x: 2_692, y: 1_116),
        CGPoint(x: 2_683, y: 1_112),
        CGPoint(x: 2_701, y: 1_119),
    ]
    static let authoredWaitingChairASamplePoints: [CGPoint] = [
        CGPoint(x: 2_366, y: 1_200),
        CGPoint(x: 2_352, y: 1_195),
        CGPoint(x: 2_380, y: 1_206),
    ]
    static let authoredWaitingTableSamplePoints: [CGPoint] = [
        CGPoint(x: 2_426, y: 1_172),
        CGPoint(x: 2_411, y: 1_166),
        CGPoint(x: 2_440, y: 1_177),
    ]
    static let authoredWaitingChairBSamplePoints: [CGPoint] = [
        CGPoint(x: 2_485, y: 1_143),
        CGPoint(x: 2_471, y: 1_138),
        CGPoint(x: 2_499, y: 1_149),
    ]
    static let authoredDoorLeafSamplePoints: [CGPoint] = [
        CGPoint(x: 2_719, y: 1_152),
        CGPoint(x: 2_673, y: 1_130),
        CGPoint(x: 2_765, y: 1_173),
    ]
    static let authoredForegroundWallSamplePoints: [CGPoint] = [
        CGPoint(x: 2_573, y: 905),
        CGPoint(x: 2_552, y: 897),
        CGPoint(x: 2_594, y: 913),
    ]
    static let authoredPartitionWallNorthSamplePoints: [CGPoint] = [
        CGPoint(x: 1_606, y: 1_401),
        CGPoint(x: 1_598, y: 1_398),
        CGPoint(x: 1_614, y: 1_404),
    ]
    static let authoredPartitionWallSouthSamplePoints: [CGPoint] = [
        CGPoint(x: 2_634, y: 886),
        CGPoint(x: 2_626, y: 883),
        CGPoint(x: 2_642, y: 889),
    ]

    // MARK: - Placements

    enum AuthoredPlacement {
        /// Registered to the visual threshold baked into the shipping suite.
        static let doorLeaf = Architecture.entranceLeafAnchor
        static let window = Architecture.windowAnchor
        static let windowBlinds = window
        static let windowRotation: CGFloat = 0
        static let windowRainMask = CGRect(x: 1_679.1, y: 1_675.6, width: 55.7, height: 99.7)
        static let windowRainEmitter = CGPoint(x: 1_707.0, y: 1_778.2)
        /// Recentred on the fitted cramped room diamond.
        static let camera = CGPoint(x: 1_970, y: 1_142)

        static let safe = CGPoint(x: 1_533, y: 1_280)  // records run, east end
        static let filingCabinetB = CGPoint(x: 1_486, y: 1_253)
        static let filingCabinet = CGPoint(x: 1_442, y: 1_228)  // drawer half open
        static let bookshelf = CGPoint(x: 1_387, y: 1_198)
        static let archiveBoxOnCabinet = CGPoint(x: 1_486, y: 1_253)  // on cabinet B
        static let archiveStackOnCabinet = CGPoint(x: 1_442, y: 1_228)  // on cabinet A
        static let archiveBoxA = CGPoint(x: 1_463, y: 1_187)  // only floor stack
        static let radiator = CGPoint(x: 1_744, y: 1_404)
        static let personalSideboard = CGPoint(x: 1_662, y: 1_352)
        static let personalWashbasin = CGPoint(x: 1_625, y: 1_331)  // retired domestic fixture; placement retained for source lineage
        static let personalFan = CGPoint(x: 1_707, y: 1_344)
        static let personalBottle = CGPoint(x: 1_661, y: 1_347)  // on sideboard
        static let personalGlass = CGPoint(x: 1_673, y: 1_354)  // on sideboard
        static let deskEnsemble = CGPoint(x: 1_876, y: 1_131)
        static let deskChair = CGPoint(x: 1_825, y: 1_102)
        static let visitorArmchair = CGPoint(x: 1_891, y: 1_211)
        static let visitorArmchairB = CGPoint(x: 2_030, y: 1_145)
        static let wastebasket = CGPoint(x: 1_739, y: 1_146)
        static let coatRack = CGPoint(x: 2_752, y: 1_108)
        static let umbrellaStand = CGPoint(x: 2_692, y: 1_116)
        static let waitingChairA = CGPoint(x: 2_366, y: 1_200)
        static let waitingTable = CGPoint(x: 2_426, y: 1_172)
        static let waitingChairB = CGPoint(x: 2_485, y: 1_143)
        static let newspaper = CGPoint(x: 2_424, y: 1_177)  // on table
        static let waitingAshtray = CGPoint(x: 2_428, y: 1_165)  // on table

        static let wornRug = CGPoint(x: 1_835, y: 1_108)
        static let floorWear = deskEnsemble
        static let wallPhotos = CGPoint(x: 1_221, y: 1_489)
        static let caseBoard = CGPoint(x: 1_330, y: 1_666)
        static let wallCityMap = CGPoint(x: 1_479, y: 1_701)
        static let framedLicence = CGPoint(x: 1_601, y: 1_672)
        static let windowSpill = CGPoint(x: 1_802, y: 1_377)
        static let blindStripes = CGPoint(x: 1_834, y: 1_333)
        static let hallwayLight = CGPoint(x: 2_706, y: 1_144)
        static let floorTrashA = CGPoint(x: 1_760, y: 1_158)
        static let floorTrashB = CGPoint(x: 1_499, y: 1_176)
        static let entranceRunner = CGPoint(x: 2_649, y: 1_132)
        static let lampPool = deskEnsemble
        /// Leaf swung 90° into the private office, hinged on the up-run jamb.
        static let internalDoorLeaf = Architecture.internalLeafAnchor
    }

    private static let authoredApproachPoints: [String: CGPoint] = [
        "office.window": CGPoint(x: 1_822, y: 1_367),
        "office.desk": CGPoint(x: 2_056, y: 1_087),
        "office.phone": CGPoint(x: 2_028, y: 1_072),
        "office.files": CGPoint(x: 1_553, y: 1_175),
        "office.door": CGPoint(x: 2_360, y: 1_238),
    ]

    private static let authoredProjectionOrigin = CGPoint(x: 2_048, y: 141)
    private static let authoredTileSize = CGSize(width: 128, height: 64)

    static var actorStart: CGPoint { OfficeInteriorScale.mapPoint(authoredActorStart) }

    static var emptyDeskChairWorldPosition: CGPoint {
        let baseline = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
        let nudge = OfficeInteriorScale.ActorDisplay.seatedDeskNudge
        return CGPoint(x: baseline.x + nudge.x, y: baseline.y + nudge.y)
    }

    enum DeskDepth {
        /// Visitor chairs sit on the far side of the writing surface.
        static let visitorChairBias: CGFloat = -50
        static let topOccluderBias: CGFloat = -40
        /// Above seated Voss's lower layer, below a client passing camera-near.
        static let seatedFrontApronBias: CGFloat = 15
        static let standingFrontApronBias: CGFloat = 40
    }

    /// Exterior threshold crossing. This segment intentionally starts
    /// outside the navigation floor and passes through the fallen door leaf.
    static let clientDoorwayPath: [CGPoint] = [
        CGPoint(x: 2_774, y: 1_182),
        CGPoint(x: 2_584, y: 1_075),
    ].map(OfficeInteriorScale.mapPoint)

    /// Walkable waiting-room anchors, ending immediately before the
    /// framed internal doorway in the production suite plate.
    static let clientWaitingRoomPath: [CGPoint] = [
        CGPoint(x: 2_584, y: 1_075),
        CGPoint(x: 2_506, y: 1_063),
        CGPoint(x: 2_493, y: 1_070),
        CGPoint(x: 2_459, y: 1_051),
    ].map(OfficeInteriorScale.mapPoint)

    /// Explicit crossing through the real framed partition aperture.
    static let clientInternalDoorwayPath: [CGPoint] = [
        CGPoint(x: 2_459, y: 1_051),
        CGPoint(x: 2_393, y: 1_014),
        CGPoint(x: 2_334, y: 981),
    ].map(OfficeInteriorScale.mapPoint)

    /// Direct private-office approach after clearing the internal door:
    /// one step along the aperture b to clear the jamb, then on to the
    /// desk's camera-near corner where the visitor stands to talk.
    static let clientOfficeArrivalPath: [CGPoint] = [
        CGPoint(x: 2_334, y: 981),
        CGPoint(x: 2_296, y: 959),
        CGPoint(x: 2_047, y: 1_088),
    ].map(OfficeInteriorScale.mapPoint)

    static let clientInteriorArrivalPath: [CGPoint] = [
        clientWaitingRoomPath,
        Array(clientInternalDoorwayPath.dropFirst()),
        Array(clientOfficeArrivalPath.dropFirst()),
    ].flatMap { $0 }

    static var clientArrivalPath: [CGPoint] {
        Array(clientDoorwayPath.dropLast()) + clientInteriorArrivalPath
    }

    static var clientDeparturePath: [CGPoint] { Array(clientArrivalPath.reversed()) }

    /// Authored aperture polyline through the shipping painted doorway.
    /// Do not A*-expand: snapping interior anchors onto nearest walkable
    /// cells can walk the coat through frosted glass beside the real opening.
    /// Anchors are collision-checked at layout generation.
    static func clientArrivalRoute(in navigation: NavigationMap) -> [CGPoint] {
        _ = navigation
        return clientArrivalPath
    }

    static func clientDepartureRoute(in navigation: NavigationMap) -> [CGPoint] {
        Array(clientArrivalRoute(in: navigation).reversed())
    }

    static let exteriorToInternalDoorPath: [CGPoint] = [
        Array(clientDoorwayPath.dropLast()),
        clientWaitingRoomPath,
        Array(clientInternalDoorwayPath.dropFirst()),
    ].flatMap { $0 }

    static let internalDoorToClientPath: [CGPoint] = [
        clientInternalDoorwayPath,
        Array(clientOfficeArrivalPath.dropFirst()),
    ].flatMap { $0 }

    static let recordsApproachPath: [CGPoint] = [
        CGPoint(x: 1_756, y: 1_146),
        CGPoint(x: 1_616, y: 1_170),
        CGPoint(x: 1_553, y: 1_175),
    ].map(OfficeInteriorScale.mapPoint)

    static var obstacles: [CGRect] { authoredObstacles.map(OfficeInteriorScale.mapRect) }

    static var safeObstacle: CGRect { OfficeInteriorScale.mapRect(authoredSafeObstacle) }
    static var filingCabinetBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetBObstacle) }
    static var filingCabinetObstacle: CGRect { OfficeInteriorScale.mapRect(authoredFilingCabinetObstacle) }
    static var bookshelfObstacle: CGRect { OfficeInteriorScale.mapRect(authoredBookshelfObstacle) }
    static var archiveBoxAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredArchiveBoxAObstacle) }
    static var radiatorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredRadiatorObstacle) }
    static var personalSideboardObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalSideboardObstacle) }
    static var personalFanObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPersonalFanObstacle) }
    static var deskEnsembleObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDeskEnsembleObstacle) }
    static var visitorArmchairObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairObstacle) }
    static var visitorArmchairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredVisitorArmchairBObstacle) }
    static var wastebasketObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWastebasketObstacle) }
    static var coatRackObstacle: CGRect { OfficeInteriorScale.mapRect(authoredCoatRackObstacle) }
    static var umbrellaStandObstacle: CGRect { OfficeInteriorScale.mapRect(authoredUmbrellaStandObstacle) }
    static var waitingChairAObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairAObstacle) }
    static var waitingTableObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingTableObstacle) }
    static var waitingChairBObstacle: CGRect { OfficeInteriorScale.mapRect(authoredWaitingChairBObstacle) }
    static var doorObstacle: CGRect { OfficeInteriorScale.mapRect(authoredDoorObstacle) }
    static var foregroundWallObstacle: CGRect { OfficeInteriorScale.mapRect(authoredForegroundWallObstacle) }
    static var partitionWallNorthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallNorthObstacle) }
    static var partitionWallSouthObstacle: CGRect { OfficeInteriorScale.mapRect(authoredPartitionWallSouthObstacle) }

    static var safeSamplePoints: [CGPoint] { authoredSafeSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetBSamplePoints: [CGPoint] { authoredFilingCabinetBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var filingCabinetSamplePoints: [CGPoint] { authoredFilingCabinetSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var bookshelfSamplePoints: [CGPoint] { authoredBookshelfSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var archiveBoxASamplePoints: [CGPoint] { authoredArchiveBoxASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var radiatorSamplePoints: [CGPoint] { authoredRadiatorSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalSideboardSamplePoints: [CGPoint] { authoredPersonalSideboardSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var personalFanSamplePoints: [CGPoint] { authoredPersonalFanSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var deskEnsembleSamplePoints: [CGPoint] { authoredDeskEnsembleSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairSamplePoints: [CGPoint] { authoredVisitorArmchairSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var visitorArmchairBSamplePoints: [CGPoint] { authoredVisitorArmchairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var wastebasketSamplePoints: [CGPoint] { authoredWastebasketSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var coatRackSamplePoints: [CGPoint] { authoredCoatRackSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var umbrellaStandSamplePoints: [CGPoint] { authoredUmbrellaStandSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairASamplePoints: [CGPoint] { authoredWaitingChairASamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingTableSamplePoints: [CGPoint] { authoredWaitingTableSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var waitingChairBSamplePoints: [CGPoint] { authoredWaitingChairBSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var doorLeafSamplePoints: [CGPoint] { authoredDoorLeafSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var foregroundWallSamplePoints: [CGPoint] { authoredForegroundWallSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallNorthSamplePoints: [CGPoint] { authoredPartitionWallNorthSamplePoints.map(OfficeInteriorScale.mapPoint) }
    static var partitionWallSouthSamplePoints: [CGPoint] { authoredPartitionWallSouthSamplePoints.map(OfficeInteriorScale.mapPoint) }

    static var majorPropSamplePoints: [CGPoint] {
        safeSamplePoints
            + filingCabinetBSamplePoints
            + filingCabinetSamplePoints
            + bookshelfSamplePoints
            + archiveBoxASamplePoints
            + radiatorSamplePoints
            + personalSideboardSamplePoints
            + personalFanSamplePoints
            + deskEnsembleSamplePoints
            + visitorArmchairSamplePoints
            + visitorArmchairBSamplePoints
            + wastebasketSamplePoints
            + coatRackSamplePoints
            + umbrellaStandSamplePoints
            + waitingChairASamplePoints
            + waitingTableSamplePoints
            + waitingChairBSamplePoints
            + doorLeafSamplePoints
            + foregroundWallSamplePoints
            + partitionWallNorthSamplePoints
            + partitionWallSouthSamplePoints
    }

    static var approachPoints: [String: CGPoint] {
        authoredApproachPoints.mapValues(OfficeInteriorScale.mapPoint)
    }

    /// Actual Voss stand-ins for architecture scale review: exterior door,
    /// desk, internal doorway, and waiting chair.
    static let authoredScaleReferenceStands: [CGPoint] = [
        CGPoint(x: 2_665, y: 1_121),
        CGPoint(x: 1_822, y: 1_100),
        CGPoint(x: 2_404, y: 1_020),
        CGPoint(x: 2_386, y: 1_191),
    ]

    static var scaleReferenceStands: [CGPoint] {
        authoredScaleReferenceStands.map(OfficeInteriorScale.mapPoint)
    }

    static var deskSamplePoints: [CGPoint] { deskEnsembleSamplePoints }
    static var deskObstacle: CGRect { deskEnsembleObstacle }
    static var authoredDeskObstacle: CGRect { authoredDeskEnsembleObstacle }

    static let authoredHotspots: [(id: String, name: String, hitArea: CGRect, observation: String)] = [
        (
            "office.window",
            "Rain-streaked window",
            CGRect(x: 1_174, y: 1_758, width: 92, height: 160),
            "The rain had been working the glass harder than I had worked a case."
        ),
        (
            "office.desk",
            "Desk",
            deskHitArea,
            "Three old cases, two unpaid bills, one clean page."
        ),
        (
            "office.phone",
            "Telephone",
            phoneHitArea,
            "Quiet. For once it had the decency to look guilty."
        ),
        (
            "office.files",
            "Case files",
            filesHitArea,
            "Closed, abandoned, and one I still lied about."
        ),
        (
            "office.door",
            "Office door",
            doorHitArea,
            "The hall smelled worse, but at least it led somewhere."
        )
    ]

    /// BG-style authored loot for searchable office containers (resolve-once on area entry).
    static let lootContainers: [LootContainerDefinition] = [
        LootContainerDefinition(
            id: "office.desk",
            entries: [
                .coins(pence: 36), // 3s loose change in the drawer
                .randomCoins(table: RandomCoinTable(penceForRolls2to20: [
                    1, 2, 3, 4, 6, 6, 8, 8, 12, 12, 12, 18, 18, 24, 24, 30, 36, 36, 48
                ]))
            ]
        ),
        LootContainerDefinition(
            id: "office.files",
            entries: [
                .randomCoins(table: RandomCoinTable(penceForRolls2to20: [
                    1, 1, 2, 2, 3, 3, 4, 4, 6, 6, 6, 8, 8, 12, 12, 12, 18, 18, 24
                ]))
            ]
        )
    ]

    static func lootContainer(for hotspotID: String) -> LootContainerDefinition? {
        lootContainers.first { $0.id == hotspotID }
    }

    /// Tall aperture covering the entrance leaf and threshold obstacle.
    private static var doorHitArea: CGRect {
        CGRect(x: 2_600, y: 1_100, width: 293, height: 586)
    }

    private static var deskHitArea: CGRect {
        authoredDeskEnsembleObstacle.insetBy(dx: -90, dy: -70)
    }

    private static var phoneHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.deskEnsemble.x - 40,
            y: AuthoredPlacement.deskEnsemble.y + 40,
            width: 200,
            height: 150
        )
    }

    private static var filesHitArea: CGRect {
        CGRect(
            x: AuthoredPlacement.filingCabinet.x - 110,
            y: AuthoredPlacement.filingCabinet.y - 20,
            width: 300,
            height: 220
        )
    }


    enum DialogueCameraFraming {
        static let legacyDownwardOffset: CGFloat = 55
        static let priorDownwardOffset: CGFloat = 28
        /// Scaled with the BG:EE mid-band camera (~9% rendered body) so dialogue
        /// framing keeps the prior on-screen downward bias after the zoom-out.
        static let cameraBelowActorMidpoint: CGFloat = 142
        static let lateralBiasTowardClient: CGFloat = 24

        static var actorFocusPoint: CGPoint {
            let voss = OfficeInteriorScale.mapPoint(AuthoredPlacement.deskChair)
            let lila = clientArrivalPath.last
                ?? OfficeInteriorScale.mapPoint(AuthoredPlacement.visitorArmchair)
            return CGPoint(
                x: (voss.x + lila.x) * 0.5 + lateralBiasTowardClient,
                y: (voss.y + lila.y) * 0.5
            )
        }

        static var dialogueCameraWorldPosition: CGPoint {
            let focus = actorFocusPoint
            return CGPoint(x: focus.x, y: focus.y - cameraBelowActorMidpoint)
        }

        static func dialogueCameraPosition(playCamera: CGPoint) -> CGPoint {
            _ = playCamera
            return dialogueCameraWorldPosition
        }

        static var downwardOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return play.y - dialogueCameraWorldPosition.y
        }

        static var lateralOffsetFromPlayCamera: CGFloat {
            let play = OfficeInteriorScale.mapPoint(AuthoredPlacement.camera)
            return dialogueCameraWorldPosition.x - play.x
        }
    }

    /// World-space bounds of the scaled office plate (BG search-map frame).
    static var navigationWorldBounds: CGRect {
        CGRect(origin: OfficeInteriorScale.shellOrigin, size: OfficeInteriorScale.scaledArtSize)
    }

    /// - Parameter entranceDoorBlocking: When false, exterior door cells are
    ///   clear (door has fallen / opening is open). Toggle later via
    ///   `NavigationMap.setEntranceDoorBlocking` without rebuilding.
    static func makeGrid(entranceDoorBlocking: Bool = true) -> NavigationMap {
        NavigationMap(
            worldBounds: navigationWorldBounds,
            obstacles: obstacles,
            agentProfile: .officeDetective,
            doorObstacles: [doorObstacle],
            entranceDoorBlocking: entranceDoorBlocking,
            maxNodes: 96_000
        )
    }

    static func isBlocked(_ point: CGPoint) -> Bool {
        obstacles.contains { $0.contains(point) }
    }
}
